#!/usr/bin/env python3
"""Drive Lazarus's capture routine over the gateway and record what it produced.

Lazarus's ``capture`` command takes its RPC URL in argv and sends no request
header, while the gateway that serves these boundaries authenticates with a
bearer header. This driver reads the gateway URL and the bearer from named
environment variables inside the process, hands them to
``lazarus_lib.capture.capture_fixture`` as its ``rpc_url`` argument and an
``authorization`` header, and maps the plan's two anchor sources to
environment variable names. Neither value enters argv, a file or the printed
output. The output is Lazarus's own terminal result, which Lazarus redacts
against its provider-secret union, wrapped with the measured elapsed seconds
that the capture record needs and Lazarus does not report.

``capture`` refuses when a named environment variable is unset or empty, when
the plan's digest is not the one ``plans.json`` records for the generation, and
when ``--out`` exists or is a symlink. A capture failure leaves no fixture;
Lazarus's failure result names the stage and the counts reached.

``record`` reads a finished fixture offline, verifies it in process with
Lazarus's verifier and writes the capture record: the plan identity, the
fixture manifest digest, each component's path, byte count and SHA-256, the
verify report and the terminal result. It refuses an output path that exists
and a terminal result that is not a completed capture of that fixture.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parents[1] / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
from lazarus_lib.canonical import load  # noqa: E402
from lazarus_lib.capture import (  # noqa: E402
    capture_failure_terminal_result,
    capture_fixture,
)
from lazarus_lib.errors import LazarusError  # noqa: E402
from lazarus_lib.scrub import redact_text  # noqa: E402
from lazarus_lib.verifier import verify_fixture  # noqa: E402

PLANS = HERE / "plans.json"
GATEWAY_URL_VARIABLE = "ALEXANDRIA_COMPOUND_RPC_URL"
GATEWAY_HEADER_VARIABLE = "ALEXANDRIA_RPC_BEARER"
DEFAULT_ANCHOR_ENV = ("local-archive=RETH_RPC_URL", "public-archive=PUBLIC_ARCHIVE_RPC_URL")
ENVIRONMENT_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")
TERMINAL_SCHEMA = "wildcat-boundary-capture-terminal/v1"
RECORD_SCHEMA = "wildcat-boundary-capture-record/v1"
MANIFEST = "manifest.json"
MAX_TERMINAL_BYTES = 1_048_576


def refuse(message: str) -> int:
    print(f"refusing: {message}", file=sys.stderr)
    return 2


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def plan_record(generation: str) -> dict:
    return json.loads(PLANS.read_text(encoding="utf-8"))["plans"][generation]


def fresh_output(path: Path) -> str | None:
    """A fresh regular path in an existing real directory, or the reason it is not."""
    if path.is_symlink():
        return f"{path} is a symlink"
    if os.path.lexists(path):
        return f"{path} already exists"
    if path.parent.is_symlink() or not path.parent.is_dir():
        return f"{path.parent} is not a real directory"
    return None


def plan_problem(generation: str, plan_path: Path) -> str | None:
    """The plan must be the regenerated bytes ``plans.json`` records."""
    if plan_path.is_symlink() or not plan_path.is_file():
        return f"{plan_path} is not a regular file"
    expected = plan_record(generation)
    data = plan_path.read_bytes()
    if len(data) != expected["bytes"] or sha256(data) != expected["sha256"]:
        return f"{plan_path} is not the {generation} plan that plans.json records"
    return None


def emit(stream, document: dict, *, secrets: set[str]) -> bool:
    """Print one JSON document only when redaction would leave it unchanged."""
    # Lazarus's canonical encoder refuses floats; the measured seconds are one.
    text = json.dumps(document, sort_keys=True, separators=(",", ":"))
    if redact_text(text, secrets=secrets) != text:
        print("refusing: output would carry a provider value", file=sys.stderr)
        return False
    stream.write(text + "\n")
    stream.flush()
    return True


def run_capture(args, *, environment, routine) -> int:
    for name in (args.url_env, args.bearer_env):
        if ENVIRONMENT_NAME.fullmatch(name) is None:
            return refuse("environment variable names match [A-Za-z_][A-Za-z0-9_]*")
    url = environment.get(args.url_env, "")
    bearer = environment.get(args.bearer_env, "")
    if not url:
        return refuse(f"environment variable {args.url_env} is unset")
    if not bearer:
        return refuse(f"environment variable {args.bearer_env} is unset")
    problem = fresh_output(args.out) or plan_problem(args.generation, args.plan)
    if problem is not None:
        return refuse(problem)
    secrets = {url, bearer}
    envelope = {
        "schema": TERMINAL_SCHEMA,
        "generation": args.generation,
        "plan_sha256": plan_record(args.generation)["sha256"],
    }
    terminal_context: dict = {}
    started = time.monotonic()
    try:
        report = routine(
            args.plan,
            url,
            args.out,
            headers={"authorization": "Bearer " + bearer},
            anchor_rpc_env=list(args.anchor_env),
            terminal_context=terminal_context,
        )
    except LazarusError as error:
        envelope["elapsed_seconds"] = round(time.monotonic() - started, 3)
        failure = capture_failure_terminal_result(terminal_context, error)
        if failure is None:
            # The plan was refused before Lazarus built its terminal context.
            failure = {
                "event": "lazarus.capture.failed",
                "stage": "plan-validation",
                "failure": redact_text(str(error), secrets=secrets),
            }
        envelope["terminal_result"] = failure
        emit(sys.stderr, envelope, secrets=secrets)
        return 1
    envelope["elapsed_seconds"] = round(time.monotonic() - started, 3)
    envelope["terminal_result"] = report["terminal_result"]
    return 0 if emit(sys.stdout, envelope, secrets=secrets) else 3


def run_record(args) -> int:
    problem = fresh_output(args.out)
    if problem is not None:
        return refuse(problem)
    expected = plan_record(args.generation)
    if args.terminal.is_symlink() or not args.terminal.is_file():
        return refuse(f"{args.terminal} is not a regular file")
    terminal_bytes = args.terminal.read_bytes()
    if len(terminal_bytes) > MAX_TERMINAL_BYTES:
        return refuse("the terminal result exceeds its size cap")
    text = terminal_bytes.decode("utf-8")
    if redact_text(text) != text:
        return refuse("the terminal result carries a provider pattern")
    try:
        # The envelope is this driver's own output and carries a non-integer
        # elapsed-seconds value, which Lazarus's strict loader would reject.
        envelope = json.loads(text)
    except ValueError:
        return refuse("the terminal result is not JSON")
    terminal = envelope.get("terminal_result") if isinstance(envelope, dict) else None
    if (
        not isinstance(terminal, dict)
        or envelope.get("schema") != TERMINAL_SCHEMA
        or envelope.get("generation") != args.generation
        or envelope.get("plan_sha256") != expected["sha256"]
        or not isinstance(envelope.get("elapsed_seconds"), (int, float))
        or terminal.get("event") != "lazarus.capture.completed"
        or terminal.get("stage") != "fixture-finalised"
    ):
        return refuse("the terminal result is not a completed capture of this generation")
    try:
        report = verify_fixture(args.fixture)
    except LazarusError as error:
        return refuse("fixture verification failed: " + redact_text(str(error)))
    manifest = report["manifest"]
    if terminal.get("fixture_digest") != manifest["fixture_digest"]:
        return refuse("the terminal result names another fixture")
    plan = load(args.fixture / "plan.json")
    counted = {
        "block_number": int(plan["block"]["number"], 16),
        "block_hash": plan["block"]["hash"],
        "requests": len(plan["requests"]),
        "proof_targets": len(plan["proof_targets"]),
        "slots": sum(len(target["slots"]) for target in plan["proof_targets"]),
        "max_elapsed_seconds": plan["limits"]["max_elapsed_seconds"],
    }
    for key, value in counted.items():
        if expected[key] != value:
            return refuse(f"the fixture's plan disagrees with plans.json on {key}")
    manifest_bytes = (args.fixture / MANIFEST).read_bytes()
    record = {
        "schema": RECORD_SCHEMA,
        "generation": args.generation,
        "plan": expected,
        "fixture": {
            "fixture_digest": manifest["fixture_digest"],
            "manifest": {
                "path": MANIFEST,
                "bytes": len(manifest_bytes),
                "sha256": sha256(manifest_bytes),
            },
            "components": manifest["components"],
        },
        "verify": report,
        "capture": {
            "elapsed_seconds": envelope["elapsed_seconds"],
            "terminal_result": terminal,
        },
    }
    encoded = json.dumps(record, indent=1, sort_keys=True).encode("utf-8") + b"\n"
    if redact_text(encoded.decode("utf-8")) != encoded.decode("utf-8"):
        return refuse("the record would carry a provider pattern")
    with open(args.out, "xb") as handle:
        handle.write(encoded)
    print(json.dumps({
        "generation": args.generation,
        "fixture_digest": manifest["fixture_digest"],
        "components": len(manifest["components"]),
        "evidence_counts": report["evidence_counts"],
        "record_sha256": sha256(encoded),
    }, sort_keys=True))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True)
    capture = commands.add_parser("capture", help="capture one estate's fixture over the gateway")
    capture.add_argument("--generation", choices=("v1", "v2"), required=True)
    capture.add_argument("--plan", type=Path, required=True,
                         help="a plan regenerated to the digest plans.json records")
    capture.add_argument("--out", type=Path, required=True,
                         help="a fresh fixture path in an existing directory; never a symlink")
    capture.add_argument("--url-env", default=GATEWAY_URL_VARIABLE, metavar="NAME",
                         help="environment variable holding the gateway URL")
    capture.add_argument("--bearer-env", default=GATEWAY_HEADER_VARIABLE, metavar="NAME",
                         help="environment variable holding the gateway bearer")
    capture.add_argument("--anchor-env", action="append", metavar="SOURCE_ID=ENV_VAR",
                         help="anchor source mapping; defaults to both plan sources")
    record = commands.add_parser("record", help="write the capture record for a finished fixture")
    record.add_argument("--generation", choices=("v1", "v2"), required=True)
    record.add_argument("--fixture", type=Path, required=True, help="the finished fixture")
    record.add_argument("--terminal", type=Path, required=True,
                        help="the capture command's printed output, saved to a file")
    record.add_argument("--out", type=Path, required=True, help="a fresh record path")
    return parser


def main(argv=None, *, environment=None, routine=capture_fixture) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "capture":
        if not args.anchor_env:
            args.anchor_env = list(DEFAULT_ANCHOR_ENV)
        return run_capture(
            args,
            environment=os.environ if environment is None else environment,
            routine=routine,
        )
    return run_record(args)


if __name__ == "__main__":
    sys.exit(main())
