"""Every classifier rule earns its entry, and every near-miss stays readable."""

from pathlib import Path
import hashlib
import os
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "skills" / "horos" / "scripts"))  # noqa: E402  (locates horos.py)

import horos  # noqa: E402


def write(root, relpath, content):
    path = Path(root) / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        content = content.encode("utf-8")
    path.write_bytes(content)
    return path


class ClassifyTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = self._tmp.name
        self.addCleanup(self._tmp.cleanup)

    def entries(self):
        return {entry["path"]: entry for entry in horos.scan_tree(self.root)["entries"]}

    def candidates(self):
        return {
            entry["path"]: entry
            for entry in horos.scan_tree(self.root)["candidates"]
        }

    def test_a_null_byte_in_the_prefix_is_a_binary_candidate(self):
        # A null byte without a known signature is candidate-grade evidence.
        write(self.root, "blob.dat", b"xx\x00\x1ayy")
        entry = self.candidates()["blob.dat"]
        self.assertEqual(entry["category"], "binary")
        self.assertEqual(entry["grade"], "candidate")

    def test_plain_text_is_not_binary(self):
        write(self.root, "notes.txt", "plain words\n")
        self.assertNotIn("notes.txt", self.entries())

    def test_a_lockfile_is_named_as_such(self):
        write(self.root, "package-lock.json", '{"lockfileVersion": 3}\n')
        entry = self.entries()["package-lock.json"]
        self.assertEqual(entry["category"], "lockfile")
        self.assertIn("package-lock.json", entry["evidence"])

    def test_an_ordinary_json_file_is_not_a_lockfile(self):
        write(self.root, "config.json", '{"a": 1}\n')
        self.assertNotIn("config.json", self.entries())

    def test_a_generation_marker_in_the_prefix_is_generated(self):
        write(self.root, "api.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
        entry = self.entries()["api.py"]
        self.assertEqual(entry["category"], "generated")
        self.assertIn("on a comment-led line in the first 4096 bytes", entry["evidence"])

    def test_a_marker_beyond_the_prefix_stays_readable(self):
        write(self.root, "deep.py", "x = 1\n" * 1000 + "# DO NOT EDIT\n")
        self.assertNotIn("deep.py", self.entries())

    def test_a_corroborated_generated_directory_excludes_hard(self):
        write(self.root, "dist/app.js", "// Code generated by webpack. DO NOT EDIT.\nvar a=1;\n")
        write(self.root, "dist/nested/app.css", "/* Code generated by webpack. */\nbody{}\n")
        entry = self.entries()["dist/"]
        self.assertEqual(entry["category"], "generated")
        self.assertEqual(entry["grade"], "hard")
        self.assertEqual(entry["files"], 2)
        self.assertIn("corroborated by sample", entry["evidence"])

    def test_an_uncorroborated_directory_name_is_a_candidate(self):
        write(self.root, "build/util.py", "def helper():\n    return 1\n")
        entries = self.entries()
        self.assertNotIn("build/", entries)
        self.assertNotIn("build/util.py", entries)
        candidate = self.candidates()["build/"]
        self.assertEqual(candidate["grade"], "candidate")
        self.assertIn("uncorroborated", candidate["evidence"])

    def test_a_near_miss_directory_name_stays_readable(self):
        write(self.root, "builder/main.py", "x = 1\n")
        self.assertNotIn("builder/", self.entries())
        self.assertNotIn("builder/main.py", self.entries())

    def test_a_package_manager_directory_excludes_hard(self):
        write(self.root, "node_modules/left-pad/package.json", '{"name": "left-pad"}\n')
        write(self.root, "node_modules/left-pad/index.js", "module.exports = 1\n")
        entry = self.entries()["node_modules/"]
        self.assertEqual(entry["category"], "vendored")
        self.assertEqual(entry["grade"], "hard")
        self.assertIn("package-manager structure", entry["evidence"])

    def test_a_sourcemap_is_generated(self):
        write(self.root, "app.js.map", '{"version":3,"mappings":"AAAA"}')
        self.assertEqual(self.entries()["app.js.map"]["category"], "generated")

    def test_a_map_file_without_mappings_stays_readable(self):
        write(self.root, "site.map", "sitemap: not a sourcemap\n")
        self.assertNotIn("site.map", self.entries())

    def test_a_large_single_line_file_is_a_blob_candidate(self):
        write(self.root, "data.json", "x" * (horos.BLOB_MIN_BYTES + 1))
        entry = self.candidates()["data.json"]
        self.assertEqual(entry["category"], "blob")
        self.assertEqual(entry["grade"], "candidate")
        self.assertIn("no newline", entry["evidence"])

    def test_a_small_single_line_file_stays_readable(self):
        write(self.root, "small.json", "x" * 100)
        self.assertNotIn("small.json", self.entries())

    def test_minified_line_geometry_is_a_blob_candidate(self):
        line = "a" * 800 + "\n"
        write(self.root, "bundle.js", line * 40)
        entry = self.candidates()["bundle.js"]
        self.assertEqual(entry["category"], "blob")
        self.assertEqual(entry["grade"], "candidate")
        self.assertIn("mean line length", entry["evidence"])

    def test_a_late_marker_is_found_by_a_window(self):
        body = "x = 1\n" * 20000 + "# Code generated by protoc. DO NOT EDIT.\n"
        write(self.root, "late.py", body)
        entry = self.entries()["late.py"]
        self.assertEqual(entry["category"], "generated")
        self.assertEqual(entry["grade"], "hard")
        self.assertIn("window", entry["evidence"])

    def test_ordinary_code_geometry_stays_readable(self):
        write(self.root, "module.py", ("x = 1\n" * 40) * 100)
        self.assertNotIn("module.py", self.entries())

    def test_gitattributes_vendored_patterns_are_honoured(self):
        write(self.root, ".gitattributes", "lib/** linguist-vendored\n")
        write(self.root, "lib/dep.py", "x = 1\n")
        entry = self.entries()["lib/"]
        self.assertEqual(entry["category"], "vendored")
        self.assertIn(".gitattributes", entry["evidence"])

    def test_an_svg_with_a_root_element_is_an_asset_candidate(self):
        write(self.root, "icons/logo.svg", '<?xml version="1.0"?>\n<svg xmlns="x"></svg>\n')
        entry = self.candidates()["icons/logo.svg"]
        self.assertEqual(entry["category"], "asset")
        self.assertEqual(entry["grade"], "candidate")
        self.assertIn("svg root element", entry["evidence"])

    def test_an_svg_file_without_the_root_element_stays_readable(self):
        write(self.root, "notes.svg", "not actually vector art\n")
        self.assertNotIn("notes.svg", self.entries())

    def test_an_svg_fragment_under_another_name_stays_readable(self):
        write(self.root, "snippet.html", "<div><svg></svg></div>\n")
        self.assertNotIn("snippet.html", self.entries())

    def test_sql_under_a_migrations_segment_is_a_candidate(self):
        write(self.root, "prisma/migrations/0001_init/migration.sql", "CREATE TABLE a (id int);\n")
        entry = self.candidates()["prisma/migrations/0001_init/migration.sql"]
        self.assertEqual(entry["category"], "generated")
        self.assertEqual(entry["grade"], "candidate")
        self.assertIn("migrations directory segment", entry["evidence"])

    def test_sql_outside_a_migrations_segment_stays_readable(self):
        write(self.root, "queries/report.sql", "SELECT 1;\n")
        self.assertNotIn("queries/report.sql", self.entries())

    def test_non_sql_inside_a_migrations_segment_stays_readable(self):
        write(self.root, "prisma/migrations/README.md", "how we migrate\n")
        self.assertNotIn("prisma/migrations/README.md", self.entries())

    def test_a_nested_gitattributes_classifies_its_own_subtree(self):
        # A directory pattern aggregates the subtree into one entry, with
        # the nested attributes file named as the evidence.
        write(self.root, "packages/sdk/.gitattributes", "abi/** linguist-generated\n")
        write(self.root, "packages/sdk/abi/Market.json", '{"abi": []}\n')
        entry = self.entries()["packages/sdk/abi/"]
        self.assertEqual(entry["category"], "generated")
        self.assertIn("packages/sdk/.gitattributes", entry["evidence"])

    def test_a_nested_gitattributes_does_not_reach_a_sibling(self):
        write(self.root, "a/.gitattributes", "*.json linguist-generated\n")
        write(self.root, "a/data.json", '{"x": 1}\n')
        write(self.root, "b/data.json", '{"x": 1}\n')
        entries = self.entries()
        self.assertIn("a/data.json", entries)
        self.assertNotIn("b/data.json", entries)

    def test_the_innermost_scope_speaks_first(self):
        # Both scopes match the file; the deeper attributes file wins.
        write(self.root, ".gitattributes", "*.json linguist-vendored\n")
        write(self.root, "deep/.gitattributes", "*.json linguist-generated\n")
        write(self.root, "deep/data.json", '{"x": 1}\n')
        entry = self.entries()["deep/data.json"]
        self.assertEqual(entry["category"], "generated")
        self.assertIn("deep/.gitattributes", entry["evidence"])

    def test_file_signatures_classify_binary_by_name(self):
        cases = {
            "img.png": b"\x89PNG\r\n\x1a\n" + b"x" * 8,
            "archive.zip": b"PK\x03\x04" + b"x" * 8,
            "doc.pdf": b"%PDF-1.7\n" + b"x" * 8,
            "mod.wasm": b"\x00asm\x01\x00\x00\x00",
            "font.woff2": b"wOF2" + b"x" * 8,
        }
        for name, content in cases.items():
            write(self.root, name, content)
        entries = self.entries()
        for name in cases:
            with self.subTest(file=name):
                self.assertEqual(entries[name]["category"], "binary")
                self.assertIn("file signature", entries[name]["evidence"])

    def test_a_text_file_matches_no_signature(self):
        write(self.root, "notes.txt", "PDF is mentioned but this is text\n")
        self.assertNotIn("notes.txt", self.entries())

    def test_a_symlink_out_of_the_root_is_never_followed(self):
        outside = tempfile.TemporaryDirectory()
        self.addCleanup(outside.cleanup)
        write(outside.name, "secret.bin", b"\x00" * 20)
        os.symlink(outside.name, os.path.join(self.root, "escape"))
        os.symlink(
            os.path.join(outside.name, "secret.bin"),
            os.path.join(self.root, "alias.bin"),
        )
        result = horos.scan_tree(self.root)
        self.assertEqual(result["entries"], [])
        self.assertEqual(result["counts"]["files_walked"], 0)

    def test_undecodable_bytes_never_raise(self):
        write(self.root, "latin.txt", b"caf\xe9 " * 3000)
        horos.scan_tree(self.root)

    def test_git_and_horos_directories_are_never_scanned(self):
        write(self.root, ".git/objects/blob", b"\x00")
        write(self.root, ".horos/boundary.json", "{}")
        write(self.root, "__pycache__/mod.cpython-311.pyc", b"\x00")
        result = horos.scan_tree(self.root)
        self.assertEqual(result["entries"], [])
        self.assertEqual(result["counts"]["files_walked"], 0)

    def test_the_walk_is_deterministic(self):
        write(self.root, "b/data.bin", b"\x00")
        write(self.root, "a/yarn.lock", "lock\n")
        write(self.root, "dist/x.js", "var a;\n")
        first = horos.scan_tree(self.root)
        second = horos.scan_tree(self.root)
        self.assertEqual(first, second)
        paths = [entry["path"] for entry in first["entries"]]
        self.assertEqual(paths, sorted(paths))

    def test_an_unreadable_file_is_counted_as_skipped_not_readable(self):
        path = write(self.root, "locked.txt", "cannot read me\n")
        os.chmod(path, 0)
        self.addCleanup(os.chmod, path, 0o644)
        result = horos.scan_tree(self.root)
        self.assertEqual(result["counts"]["files_skipped_unreadable"], 1)
        self.assertEqual(result["entries"], [])

    def test_counts_report_hard_bytes_per_category(self):
        write(self.root, "a.wasm", b"\x00asm" + b"\x00" * 6)
        write(self.root, "yarn.lock", "lock\n")
        write(self.root, "x.dat", b"zz\x00zz")
        counts = horos.scan_tree(self.root)["counts"]
        self.assertEqual(counts["bytes_binary"], 10)
        self.assertEqual(counts["bytes_lockfile"], 5)
        self.assertEqual(counts["files_walked"], 3)
        self.assertNotIn("bytes_blob", counts)


class ContentAddressedTests(unittest.TestCase):
    """A store that names files by their own digest proves its own entries."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = self._tmp.name
        self.addCleanup(self._tmp.cleanup)

    def entries(self):
        return {entry["path"]: entry for entry in horos.scan_tree(self.root)["entries"]}

    def classified(self):
        result = horos.scan_tree(self.root)
        return {entry["path"] for entry in result["entries"] + result["candidates"]}

    def store(self, payload, sharded=True, algorithm="sha256", name=None):
        """Write payload into a store and return its path."""
        digest = hashlib.new(algorithm, payload).hexdigest()
        filename = digest if name is None else name
        if sharded:
            relpath = f"objects/{algorithm}/{filename[:2]}/{filename}"
        else:
            relpath = f"blobs/{algorithm}/{filename}"
        write(self.root, relpath, payload)
        return relpath

    def test_a_sharded_object_is_hard_evidence(self):
        relpath = self.store(b"a captured response\n")
        entry = self.entries()[relpath]
        self.assertEqual(entry["category"], "content_addressed")
        self.assertEqual(entry["grade"], "hard")
        self.assertIn("sha256 digest", entry["evidence"])

    def test_a_flat_oci_style_blob_is_hard_evidence(self):
        relpath = self.store(b"a released layer\n", sharded=False)
        self.assertEqual(self.entries()[relpath]["category"], "content_addressed")

    def test_every_supported_algorithm_verifies(self):
        for algorithm in ("sha1", "sha256", "sha384", "sha512"):
            with self.subTest(algorithm=algorithm):
                relpath = self.store(f"payload for {algorithm}\n".encode(), algorithm=algorithm)
                self.assertEqual(
                    self.entries()[relpath]["category"], "content_addressed"
                )

    def test_a_name_whose_digest_does_not_match_stays_readable(self):
        # The shape is right and the width is right; only the bytes disagree.
        digest = hashlib.sha256(b"the bytes that were promised\n").hexdigest()
        relpath = f"objects/sha256/{digest[:2]}/{digest}"
        write(self.root, relpath, "the bytes that arrived\n")
        self.assertNotIn(relpath, self.classified())

    def test_a_shard_that_does_not_prefix_its_digest_stays_readable(self):
        payload = b"filed under the wrong shard\n"
        digest = hashlib.sha256(payload).hexdigest()
        shard = "ff" if not digest.startswith("ff") else "00"
        relpath = f"objects/sha256/{shard}/{digest}"
        write(self.root, relpath, payload)
        self.assertNotIn(relpath, self.classified())

    def test_an_algorithm_directory_needs_an_objects_or_blobs_parent(self):
        payload = b"a digest-named file that is not in a store\n"
        digest = hashlib.sha256(payload).hexdigest()
        relpath = f"docs/sha256/{digest[:2]}/{digest}"
        write(self.root, relpath, payload)
        self.assertNotIn(relpath, self.classified())

    def test_a_git_style_object_store_does_not_verify(self):
        # Git names no algorithm and digests a header the bytes do not carry,
        # so its objects fall through to the other rules rather than verify.
        payload = b"blob 5\x00hello"
        digest = hashlib.sha1(payload).hexdigest()
        relpath = f"objects/{digest[:2]}/{digest[2:]}"
        write(self.root, relpath, payload)
        self.assertNotIn(relpath, self.entries())

    def test_uppercase_hex_stays_readable(self):
        payload = b"shouted digest\n"
        digest = hashlib.sha256(payload).hexdigest().upper()
        relpath = f"objects/sha256/{digest[:2]}/{digest}"
        write(self.root, relpath, payload)
        self.assertNotIn(relpath, self.classified())

    def test_a_wrong_width_name_is_never_hashed(self):
        # Shape gates the read: a short name is refused before any hashing.
        self.assertIsNone(horos.content_addressed_algorithm("objects/sha256/ab/abcd"))

    def test_counts_report_content_addressed_bytes(self):
        payload = b"counted by category\n"
        self.store(payload)
        counts = horos.scan_tree(self.root)["counts"]
        self.assertEqual(counts["bytes_content_addressed"], len(payload))


COMMENT_LED_BANNERS = {
    "#": "# do not edit: regenerate with make api\nx = 1\n",
    "//": "// Code generated by webpack. DO NOT EDIT.\nvar a = 1;\n",
    "/*": "/* @generated */\nbody {}\n",
    "*": " * @generated by codegen\n */\nint x;\n",
    "<!--": "<!-- auto-generated, changes will be overwritten -->\n<html></html>\n",
    "--": "-- automatically generated migration\nSELECT 1;\n",
    ";": "; autogenerated listing\nmov eax, 1\n",
    "%": "% auto-generated by matlab\ny = 2\n",
}

STRING_LITERAL_BODY = 'MARKERS = ("do not edit", "auto-generated")\n'
CALL_ARGUMENT_BODY = 'write(root, "gen.py", "# Code generated by protoc. DO NOT EDIT.")\n'
JSON_VALUE_BODY = '{"evidence": "marker \'do not edit\' in the first 4096 bytes"}\n'

# Enough unclassifiable filler to push a file past the large-file threshold,
# so the window pass runs over whatever is appended after it.
WINDOW_FILLER = "x = 1\n" * 20000


class CommentLedMarkerGateTests(unittest.TestCase):
    """A marker binds only where its line declares itself as commentary."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = self._tmp.name
        self.addCleanup(self._tmp.cleanup)

    def entries(self):
        return {entry["path"]: entry for entry in horos.scan_tree(self.root)["entries"]}

    def candidates(self):
        return {
            entry["path"]: entry
            for entry in horos.scan_tree(self.root)["candidates"]
        }

    def test_a_comment_led_banner_binds_in_the_prefix_under_every_leader(self):
        for index, (leader, body) in enumerate(sorted(COMMENT_LED_BANNERS.items())):
            with self.subTest(leader=leader):
                name = f"banner_{index}.txt"
                write(self.root, name, body)
                entry = self.entries()[name]
                self.assertEqual(entry["category"], "generated")
                self.assertEqual(entry["grade"], "hard")
                self.assertIn(
                    "on a comment-led line in the first 4096 bytes",
                    entry["evidence"],
                )

    def test_a_comment_led_banner_binds_in_a_window_under_every_leader(self):
        for index, (leader, body) in enumerate(sorted(COMMENT_LED_BANNERS.items())):
            with self.subTest(leader=leader):
                name = f"late_banner_{index}.txt"
                write(self.root, name, WINDOW_FILLER + body)
                entry = self.entries()[name]
                self.assertEqual(entry["category"], "generated")
                self.assertEqual(entry["grade"], "hard")
                self.assertIn(
                    "on a comment-led line in a 2048-byte window at offset",
                    entry["evidence"],
                )

    def test_a_marker_inside_a_string_literal_stays_readable_in_the_prefix(self):
        write(self.root, "markers.py", STRING_LITERAL_BODY)
        self.assertNotIn("markers.py", self.entries())

    def test_a_marker_inside_a_call_argument_stays_readable_in_the_prefix(self):
        write(self.root, "fixture.py", CALL_ARGUMENT_BODY)
        self.assertNotIn("fixture.py", self.entries())

    def test_a_marker_inside_a_json_value_stays_readable_in_the_prefix(self):
        write(self.root, "evidence.json", JSON_VALUE_BODY)
        self.assertNotIn("evidence.json", self.entries())

    def test_a_marker_inside_code_or_data_stays_readable_in_a_window(self):
        shapes = {
            "string_literal.py": STRING_LITERAL_BODY,
            "call_argument.py": CALL_ARGUMENT_BODY,
            "json_value.json": JSON_VALUE_BODY,
        }
        for name, body in sorted(shapes.items()):
            with self.subTest(shape=name):
                write(self.root, name, WINDOW_FILLER + body)
                self.assertNotIn(name, self.entries())

    def test_a_banner_straddling_a_window_edge_binds_through_contained_lines_only(self):
        head = "x = 1\n" * 8332 + "yy\n"
        line = "# qq do not edit straddles\n"
        tail = "x = 1\n" * 8329 + "end\n"
        body = head + line + tail
        size = len(body)
        mid = size // 2
        marker_at = body.lower().find("do not edit")
        # The line starts before the middle window and its marker sits wholly
        # inside it, so only substring matching over the raw window text, the
        # behaviour under repair, can bind this fixture.
        self.assertGreater(size, horos.LARGE_FILE_BYTES)
        self.assertLess(len(head), mid)
        self.assertGreaterEqual(marker_at, mid)
        self.assertLess(marker_at + len("do not edit"), mid + horos.WINDOW_BYTES)
        self.assertLess(marker_at + len("do not edit"), size - horos.WINDOW_BYTES)
        write(self.root, "straddle.py", body)
        self.assertNotIn("straddle.py", self.entries())

    def test_a_banner_wholly_inside_a_middle_window_binds(self):
        head = "x = 1\n" * 8335
        line = "# do not edit contained\n"
        tail = "x = 1\n" * 8327 + "end\n"
        body = head + line + tail
        size = len(body)
        mid = size // 2
        self.assertGreater(size, horos.LARGE_FILE_BYTES)
        self.assertGreaterEqual(len(head), mid)
        self.assertLessEqual(len(head) + len(line), mid + horos.WINDOW_BYTES)
        write(self.root, "contained.py", body)
        entry = self.entries()["contained.py"]
        self.assertEqual(entry["category"], "generated")
        self.assertIn(
            f"on a comment-led line in a 2048-byte window at offset {mid}",
            entry["evidence"],
        )

    def test_the_narrowed_rule_binds_a_subset_of_what_substring_matching_bound(self):
        corpus = list(COMMENT_LED_BANNERS.values()) + [
            STRING_LITERAL_BODY,
            CALL_ARGUMENT_BODY,
            JSON_VALUE_BODY,
            "plain words\n",
            "x = 1\n" * 40,
        ]
        for body in corpus:
            prefix = body.encode("utf-8")[: horos.PREFIX_BYTES]
            verdict = horos.classify_content("corpus.txt", len(body), prefix)
            binds_marker = (
                verdict is not None
                and verdict[0] == "generated"
                and "marker" in verdict[1]
            )
            if binds_marker:
                self.assertTrue(
                    any(marker in body.lower() for marker in horos.GENERATED_MARKERS),
                    body,
                )

    def test_a_directory_corroborated_only_by_string_literal_markers_no_longer_excludes(self):
        write(self.root, "dist/a.py", STRING_LITERAL_BODY)
        write(self.root, "dist/b.py", CALL_ARGUMENT_BODY)
        entries = self.entries()
        self.assertNotIn("dist/", entries)
        self.assertNotIn("dist/a.py", entries)
        candidate = self.candidates()["dist/"]
        self.assertEqual(candidate["grade"], "candidate")
        self.assertIn("uncorroborated", candidate["evidence"])


class SelfExclusionTests(unittest.TestCase):
    """The tree that defines the marker rule never excludes its own source."""

    def test_this_repository_excludes_no_marker_defining_source(self):
        repo_root = Path(__file__).resolve().parents[3]
        entries = {
            entry["path"]: entry
            for entry in horos.scan_tree(str(repo_root))["entries"]
        }

        def excluded(relpath):
            if relpath in entries:
                return True
            return any(
                path.endswith("/") and relpath.startswith(path) for path in entries
            )

        self.assertFalse(excluded("plugins/horos/skills/horos/scripts/horos.py"))
        self.assertFalse(excluded("plugins/horos/tests/test_classify.py"))
        self.assertEqual(entries["CONTRIBUTORS.md"]["category"], "generated")
        self.assertEqual(
            entries["plugins/horos/examples/fixture/gen/api.py"]["category"],
            "generated",
        )


if __name__ == "__main__":
    unittest.main()
