#!/usr/bin/env python3
"""Rank the repository's human contributors from resolved GitHub identity.

CONTRIBUTORS.md and the thanks block in README.md are generated by this script.
Do not hand-edit either one: the weekly refresh overwrites whatever is there.

This module holds the classification primitives. Which identities are runtime
hosts rather than contributors is decided by ADR-016, and the mechanical set it
refers to lives in plugins/hexaemeron/skills/fiat/scripts/hexctl.py. The copy
below is kept equal to that one by tests/test_contributors.py, which fails when
either side is edited alone.

The Wildcat-Origin trailer is deliberately not part of the classification. It
records which tool performed the work, not who decided it: every commit by this
repository's external human contributors carries it, and some commits authored
by a runtime host carry none. See docs/contributors/study.md, item 4.
"""

from __future__ import annotations

import argparse
import json
import re
import sys

# Kept equal to hexctl.py's frozensets by tests/test_contributors.py.
HOST_IDENTITY_NAMES = frozenset(
    {
        "aider",
        "anthropic",
        "chatgpt",
        "claude",
        "claude code",
        "claude[bot]",
        "codex",
        "copilot",
        "cursor",
        "devin",
        "gemini",
        "gemini code assist",
        "github copilot",
        "openai",
    }
)
HOST_IDENTITY_EMAILS = frozenset(
    {
        "noreply@anthropic.com",
        "noreply@openai.com",
    }
)
HOST_PR_LOGINS = frozenset(
    {
        "app/claude",
        "chatgpt[bot]",
        "claude[bot]",
        "codex[bot]",
        "copilot[bot]",
    }
)

# A GitHub login is 1 to 39 characters of ASCII alphanumerics and hyphens, and
# may neither start nor end with a hyphen. Nothing matching this can carry
# Markdown syntax, which is why the login is the only API field either artefact
# is allowed to contain.
LOGIN_RE = re.compile(r"\A[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?\Z")


def is_host_identity(name: str, email: str) -> bool:
    """Recognise known runtime identities without reclassifying human authors."""
    return (
        name.strip().casefold() in HOST_IDENTITY_NAMES
        or email.strip().casefold() in HOST_IDENTITY_EMAILS
    )


def is_host_login(login: str) -> bool:
    """Recognise a runtime identity by its GitHub login or app byline."""
    folded = login.strip().casefold()
    return folded in HOST_PR_LOGINS or folded in HOST_IDENTITY_NAMES


def valid_login(login: str) -> bool:
    """Accept only a login that cannot carry Markdown syntax into an artefact.

    Classification must exclude runtime hosts BEFORE calling this. Some host
    logins are deliberately not valid logins: `claude[bot]` and `app/claude`
    both fail here. Validating first would turn a routine host exclusion into
    the bad-grammar stop, which fails the run on an identity the host set
    already knows how to drop.
    """
    return bool(LOGIN_RE.match(login))


def host_set_payload() -> dict:
    """Report the loaded classification set, for inspection and for tests."""
    return {
        "schema": "wildcat-contributors-host-set/v1",
        "host_identity_names": sorted(HOST_IDENTITY_NAMES),
        "host_identity_emails": sorted(HOST_IDENTITY_EMAILS),
        "host_pr_logins": sorted(HOST_PR_LOGINS),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="contributors.py",
        description="Rank the repository's human contributors from resolved identity.",
    )
    parser.add_argument(
        "--host-set",
        action="store_true",
        help="print the loaded runtime-host classification set as JSON and exit",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(sys.argv[1:] if argv is None else argv)
    if arguments.host_set:
        print(json.dumps(host_set_payload(), indent=2, sort_keys=True))
        return 0
    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
