#!/usr/bin/env python3
"""Rank the repository's human contributors from resolved GitHub identity.

CONTRIBUTORS.md and the thanks block in README.md are generated by this script.
Do not hand-edit either one: the weekly refresh overwrites whatever is there.

This module holds the classification primitives. Which identities are runtime
hosts rather than contributors is decided by ADR-016, and the mechanical set it
refers to lives in plugins/hexaemeron/skills/fiat/scripts/hexctl.py. The copy
below is kept equal to that one by tests/test_contributors.py, which fails when
either side is edited alone.

The Wildcat-Origin trailer is deliberately not part of the classification. It
records which tool performed the work, not who decided it: every commit by this
repository's external human contributors carries it, and some commits authored
by a runtime host carry none. See docs/contributors/study.md, item 4.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
from pathlib import Path
import re
import sys
import tempfile
import urllib.parse
import urllib.request

# Kept equal to hexctl.py's frozensets by tests/test_contributors.py.
HOST_IDENTITY_NAMES = frozenset(
    {
        "aider",
        "anthropic",
        "chatgpt",
        "claude",
        "claude code",
        "claude[bot]",
        "codex",
        "copilot",
        "cursor",
        "devin",
        "gemini",
        "gemini code assist",
        "github copilot",
        "openai",
    }
)
HOST_IDENTITY_EMAILS = frozenset(
    {
        "noreply@anthropic.com",
        "noreply@openai.com",
    }
)
HOST_PR_LOGINS = frozenset(
    {
        "app/claude",
        "chatgpt[bot]",
        "claude[bot]",
        "codex[bot]",
        "copilot[bot]",
    }
)

# A GitHub login is 1 to 39 characters of ASCII alphanumerics and hyphens, and
# may neither start nor end with a hyphen. Nothing matching this can carry
# Markdown syntax, which is why the login is the only API field either artefact
# is allowed to contain.
LOGIN_RE = re.compile(r"\A[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?\Z")

# Excluded at the Creator's own instruction: the repository owner is not ranked
# among the people the repository thanks. This is a decision, not something
# derived from the history, so it is named here rather than inferred.
EXCLUDED_MAINTAINERS = frozenset({"laurenceday"})

# The Shoggoth is the author of governed agent work under ADR-016, so it is a
# legitimate Git author and a legitimate GitHub contributor. It is still not a
# human being thanked for helping. It is deliberately NOT in the runtime-host
# set: a host identity is a transport that should never have been an author,
# whereas this one should. Different reason, different set, different message.
AGENT_LOGINS = frozenset({"shoggoth-wildcat"})

REPOSITORY = "wildcat-finance/skills"
HEXCTL_RELATIVE = "plugins/hexaemeron/skills/fiat/scripts/hexctl.py"
PARITY_SET_NAMES = ("HOST_IDENTITY_EMAILS", "HOST_IDENTITY_NAMES", "HOST_PR_LOGINS")
API_HOST = "api.github.com"
API_ROOT = f"https://{API_HOST}"
REPO_RE = re.compile(r"\A[A-Za-z0-9._-]{1,100}/[A-Za-z0-9._-]{1,100}\Z")
PAGE_SIZE = 100
MAX_PAGES = 50
RESPONSE_LIMIT = 4 * 1024 * 1024
TIMEOUT_SECONDS = 30


class Stop(Exception):
    """A fail-closed stop. The message names the identity or field at fault."""


def is_host_identity(name: str, email: str) -> bool:
    """Recognise known runtime identities without reclassifying human authors."""
    return (
        name.strip().casefold() in HOST_IDENTITY_NAMES
        or email.strip().casefold() in HOST_IDENTITY_EMAILS
    )


def is_host_login(login: str) -> bool:
    """Recognise a runtime identity by its GitHub login or app byline."""
    folded = login.strip().casefold()
    return folded in HOST_PR_LOGINS or folded in HOST_IDENTITY_NAMES


def valid_login(login: str) -> bool:
    """Accept only a login that cannot carry Markdown syntax into an artefact.

    Classification must exclude runtime hosts BEFORE calling this. Some host
    logins are deliberately not valid logins: `claude[bot]` and `app/claude`
    both fail here. Validating first would turn a routine host exclusion into
    the bad-grammar stop, which fails the run on an identity the host set
    already knows how to drop.
    """
    return bool(LOGIN_RE.match(login))


def host_set_payload() -> dict:
    """Report the loaded classification set, for inspection and for tests."""
    return {
        "schema": "wildcat-contributors-host-set/v1",
        "host_identity_names": sorted(HOST_IDENTITY_NAMES),
        "host_identity_emails": sorted(HOST_IDENTITY_EMAILS),
        "host_pr_logins": sorted(HOST_PR_LOGINS),
    }


def frozensets_from_source(path, prefix: str = "HOST_") -> dict:
    """Read every `HOST_* = frozenset({...})` module-level literal without importing.

    Discovery is by prefix, not by the names already known. A parity check that
    compares only what it knows cannot notice a new set. If hexctl.py grows a
    fourth host set, this module would miss a whole class of runtime identity
    and every check would still pass, so the prefix scan turns that into a stop
    naming the set nobody accounted for.
    """
    tree = ast.parse(Path(path).read_text(encoding="utf-8"), filename=str(path))
    found = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or not target.id.startswith(prefix):
            continue
        call = node.value
        if (
            not isinstance(call, ast.Call)
            or not isinstance(call.func, ast.Name)
            or call.func.id != "frozenset"
        ):
            # A HOST_* name that is not a frozenset is not a classification set.
            # hexctl.py has HOST_BYLINE_RE, a compiled pattern. Skipping it is
            # deliberate; a genuinely missing set is caught by comparing the
            # discovered names, not by asserting shape here.
            continue
        if len(call.args) != 1:
            raise Stop(
                f"{target.id} in {Path(path).name} is frozenset() with "
                f"{len(call.args)} arguments, which cannot be read"
            )
        try:
            members = ast.literal_eval(call.args[0])
        except (ValueError, TypeError) as error:
            raise Stop(
                f"{target.id} in {Path(path).name} is a frozenset of something "
                f"other than a literal: {error}"
            ) from error
        found[target.id] = frozenset(members)
    return found


def verify_host_set_parity(hexctl_path) -> None:
    """Stop when this module's host set and Fiat's declaration have diverged.

    ADR-016 names one mechanical set of runtime host identities and Fiat owns
    it. The copy above exists so this stays a standalone root script. A copy
    nothing checks stops agreeing, and the failure mode is a runtime identity
    ranked as a person, so the divergence is a stop rather than a warning.
    """
    declared = frozensets_from_source(hexctl_path)
    if sorted(declared) != sorted(PARITY_SET_NAMES):
        missing = sorted(set(PARITY_SET_NAMES) - set(declared))
        extra = sorted(set(declared) - set(PARITY_SET_NAMES))
        raise Stop(
            "host set drift: hexctl.py and this module disagree about which "
            f"HOST_* sets exist (missing here: {missing or 'none'}; "
            f"present there and unaccounted for here: {extra or 'none'})"
        )
    ours = {
        "HOST_IDENTITY_EMAILS": HOST_IDENTITY_EMAILS,
        "HOST_IDENTITY_NAMES": HOST_IDENTITY_NAMES,
        "HOST_PR_LOGINS": HOST_PR_LOGINS,
    }
    for name in PARITY_SET_NAMES:
        if ours[name] != declared[name]:
            raise Stop(
                f"host set drift: {name} differs from hexctl.py "
                f"(only here: {sorted(ours[name] - declared[name]) or 'none'}; "
                f"only there: {sorted(declared[name] - ours[name]) or 'none'})"
            )


def rate_limit_aware_message(path, error, authenticated):
    """Say plainly when the answer is a token, rather than reporting a bare 403.

    The search endpoints allow 30 requests a minute with a token and 10 without.
    This generator issues two search calls per ranked contributor plus two more,
    so an unauthenticated run stops being viable at about four contributors. A
    bare "api read failed" sends whoever is on call looking for a network fault.
    """
    remaining = error.headers.get("X-RateLimit-Remaining") if error.headers else None
    retry_after = error.headers.get("Retry-After") if error.headers else None
    rate_limited = error.code in (403, 429) and (remaining == "0" or retry_after is not None)
    if not rate_limited:
        return f"api read failed for {path}: HTTP {error.code} {error.reason}"
    reset = error.headers.get("X-RateLimit-Reset") if error.headers else None
    detail = f"api rate limit reached on {path} (HTTP {error.code}"
    if retry_after:
        detail += f", retry after {retry_after}s"
    elif reset:
        detail += f", resets at unix {reset}"
    detail += "). "
    if authenticated:
        detail += (
            "This run was authenticated, so the limit is 30 search requests a "
            "minute; wait for the reset or reduce the number of ranked contributors."
        )
    else:
        detail += (
            "This run sent no token, so the limit is 10 search requests a minute. "
            "Set GITHUB_TOKEN or GH_TOKEN in the environment and rerun."
        )
    return detail


class RefuseOffHostRedirect(urllib.request.HTTPRedirectHandler):
    """Stop a redirect off the API host before the next request is issued.

    urllib copies every request header onto the redirected request except
    content-length and content-type, so an Authorization bearer token travels to
    wherever the redirect points. Checking the final URL after urlopen returns is
    too late: by then the token has already been sent to that host.
    """

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        host = urllib.parse.urlsplit(newurl).netloc
        if host != API_HOST:
            raise Stop(f"api request was redirected off {API_HOST} to {host!r}")
        return super().redirect_request(req, fp, code, msg, headers, newurl)


def http_reader():
    """Return a reader that fetches one API path and parses its JSON body.

    Injectable so every test runs offline against recorded fixtures. The real
    reader is the only place this module touches the network.
    """

    import urllib.error
    import urllib.parse
    import urllib.request

    opener = urllib.request.build_opener(RefuseOffHostRedirect)

    def read(path: str):
        if not path.startswith("/"):
            raise Stop(f"api path must be absolute: {path!r}")
        request = urllib.request.Request(
            API_ROOT + path,
            headers={
                "Accept": "application/vnd.github+json",
                "User-Agent": "wildcat-contributors",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
        if token:
            # Read from the environment only. A token on the command line would
            # reach the process table and the shell history.
            request.add_header("Authorization", f"Bearer {token}")
        try:
            with opener.open(request, timeout=TIMEOUT_SECONDS) as response:
                landed = urllib.parse.urlsplit(response.geturl()).netloc
                if landed != API_HOST:
                    raise Stop(f"api response came from {landed!r}, not {API_HOST}")
                raw = response.read(RESPONSE_LIMIT + 1)
        except urllib.error.HTTPError as error:
            # HTTPError subclasses URLError, so catching only URLError would
            # report a 403 as a generic read failure and lose the one field that
            # says what to do about it.
            raise Stop(rate_limit_aware_message(path, error, bool(token))) from error
        except urllib.error.URLError as error:
            raise Stop(f"api read failed for {path}: {error}") from error
        except OSError as error:
            raise Stop(f"api read failed for {path}: {error}") from error
        if len(raw) > RESPONSE_LIMIT:
            raise Stop(f"api response for {path} exceeded {RESPONSE_LIMIT} bytes")
        try:
            return json.loads(raw.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as error:
            raise Stop(f"api response for {path} was not JSON: {error}") from error

    return read


def classify(rows, excluded=EXCLUDED_MAINTAINERS):
    """Split contributor rows into ranked candidates and named exclusions.

    Every row lands in exactly one of three places: a candidate, an exclusion
    with a reason, or a stop. There is no silent fourth outcome, because the
    cost of one is a runtime identity thanked as a person.
    """
    candidates, exclusions = [], []
    for row in rows:
        if not isinstance(row, dict):
            raise Stop(f"contributor row is not an object: {row!r}")
        login = row.get("login")
        kind = row.get("type")
        if not isinstance(login, str) or not login:
            raise Stop(f"contributor row carries no login: {row!r}")
        contributions = row.get("contributions")
        if not isinstance(contributions, int) or contributions < 0:
            raise Stop(f"{login} carries a non-integer contribution count: {contributions!r}")

        if is_host_login(login):
            exclusions.append({"login": login, "reason": "runtime host identity"})
            continue
        if kind == "Bot":
            # ADR-016 records that the mechanical set does not cover unfamiliar
            # future host names. Ranking one would put a runtime in a file that
            # thanks people, so an unrecognised bot stops the run by name.
            raise Stop(
                f"unknown identity: {login!r} is a Bot that is not in the host set; "
                "extend HOST_PR_LOGINS in hexctl.py and here, then rerun"
            )
        if kind != "User":
            raise Stop(f"unknown identity: {login!r} has account type {kind!r}, not User or Bot")
        if login in AGENT_LOGINS:
            exclusions.append(
                {"login": login, "reason": "Shoggoth agent identity, not a human contributor"}
            )
            continue
        if login in excluded:
            exclusions.append({"login": login, "reason": "repository owner, excluded by decision"})
            continue
        if not valid_login(login):
            raise Stop(f"{login!r} is not a valid GitHub login and cannot be rendered")
        candidates.append({"login": login, "commits": contributions})
    return candidates, exclusions


def rank(entries):
    """Order by commits, then merged pull requests, then login.

    The final key makes equal counts order identically on every run, so a
    refresh that changed nothing produces no diff.
    """
    return sorted(
        entries,
        key=lambda entry: (-entry["commits"], -entry.get("merged_prs", 0), entry["login"]),
    )


def merged_pr_count(read, repo, login):
    payload = read(f"/search/issues?q=repo:{repo}+type:pr+is:merged+author:{login}&per_page=1")
    total = payload.get("total_count") if isinstance(payload, dict) else None
    if not isinstance(total, int) or total < 0:
        raise Stop(f"merged pull-request count for {login} was not a count: {total!r}")
    return total


def corroborate_human_authorship(read, repo, login):
    """Confirm at least one of a login's commits was authored by a non-host identity.

    The contributors endpoint resolves several author emails to one account,
    which is the whole reason it is used. This checks the resolution did not
    quietly gather a runtime's commits under a human login.
    """
    payload = read(f"/search/commits?q=repo:{repo}+author:{login}&per_page=20")
    items = payload.get("items") if isinstance(payload, dict) else None
    if not isinstance(items, list) or not items:
        raise Stop(f"no commits found for {login}, so human authorship is unconfirmed")
    identities = []
    for item in items:
        author = (item.get("commit") or {}).get("author") or {}
        identities.append((str(author.get("name", "")), str(author.get("email", ""))))
    human = [pair for pair in identities if not is_host_identity(*pair)]
    if not human:
        raise Stop(
            f"every sampled commit for {login} was authored by a runtime host identity"
        )
    return len(human), len(identities)


def issue_coverage(read, repo, ranked_logins, excluded_logins):
    """Name humans with closed-issue activity but no ranked commits.

    Issue activity contributes no rank, per the request: commits and merges
    only. Reporting it separately is what keeps a person who worked an issue
    without landing a commit from disappearing without trace.
    """
    payload = read(f"/search/issues?q=repo:{repo}+type:issue+state:closed&per_page={PAGE_SIZE}")
    if not isinstance(payload, dict):
        raise Stop(f"closed-issue search returned {type(payload).__name__}, not an object")
    items = payload.get("items")
    if not isinstance(items, list):
        raise Stop("closed-issue search returned no items list")
    total = payload.get("total_count")
    if isinstance(total, int) and total > len(items):
        # Coverage that stops short has to say so. Reported rather than raised:
        # this list informs, it does not rank, so a partial read is a caveat and
        # not a reason to fail the whole refresh.
        raise Stop(
            f"closed-issue coverage read {len(items)} of {total} issues; "
            "paginate this read before relying on the coverage list"
        )
    seen, uncounted = set(), []
    for item in items:
        login = ((item.get("user") or {}).get("login")) or ""
        if not login or login in seen:
            continue
        seen.add(login)
        if login in ranked_logins or login in excluded_logins or is_host_login(login):
            continue
        uncounted.append(login)
    return sorted(uncounted)


def read_all_pages(read, path_template, label):
    """Read every page, or stop. A silent cap reads afterwards as full coverage.

    The alternative is a truncated list that looks complete: a repository with
    more than one page of contributors would quietly lose everyone past the
    first hundred, and the artefact would give no sign of it.
    """
    collected = []
    for page in range(1, MAX_PAGES + 1):
        rows = read(path_template.format(page=page, per_page=PAGE_SIZE))
        if not isinstance(rows, list):
            raise Stop(f"{label} returned {type(rows).__name__}, not a list")
        collected.extend(rows)
        if len(rows) < PAGE_SIZE:
            return collected
    raise Stop(
        f"{label} still had pages after {MAX_PAGES} of {PAGE_SIZE}; "
        "raise MAX_PAGES rather than shipping a truncated list"
    )


def compute(read, repo=REPOSITORY, hexctl_path=None, excluded=EXCLUDED_MAINTAINERS):
    """Produce the whole ranking in one pass, so nothing downstream recomputes it."""
    if not REPO_RE.match(repo):
        raise Stop(f"repository must be owner/name with no query syntax: {repo!r}")
    if hexctl_path is not None:
        verify_host_set_parity(hexctl_path)
    rows = read_all_pages(
        read,
        f"/repos/{repo}/contributors?per_page={{per_page}}&page={{page}}",
        "contributors endpoint",
    )
    candidates, exclusions = classify(rows, excluded=excluded)
    for entry in candidates:
        entry["merged_prs"] = merged_pr_count(read, repo, entry["login"])
        human, sampled = corroborate_human_authorship(read, repo, entry["login"])
        entry["human_authored_sampled"] = human
        entry["sampled"] = sampled
    ranked = rank(candidates)
    ranked_logins = {entry["login"] for entry in ranked}
    excluded_logins = {entry["login"] for entry in exclusions}
    # The net is unconditional and checks the module's declared truth, not the
    # caller's `excluded` argument. That argument shapes classification; if it
    # could also switch off the last check, the check would be worth nothing
    # exactly when classification had already gone wrong.
    for login in sorted(EXCLUDED_MAINTAINERS | AGENT_LOGINS | set(excluded)):
        if login in ranked_logins:
            raise Stop(f"{login} is excluded but reached the ranked list")
    payload = {
        "schema": "wildcat-contributors/v1",
        "repository": repo,
        "contributors": [
            {
                "rank": index,
                "login": entry["login"],
                "commits": entry["commits"],
                "merged_prs": entry["merged_prs"],
                "human_authored_sampled": entry["human_authored_sampled"],
                "commits_sampled": entry["sampled"],
            }
            for index, entry in enumerate(ranked, start=1)
        ],
        "excluded": sorted(exclusions, key=lambda item: item["login"]),
        "issue_activity_without_ranked_commits": issue_coverage(
            read, repo, ranked_logins, excluded_logins
        ),
    }
    return payload


def classification_lines(payload):
    """One line per identity, so `why is this person not on the list` is answerable."""
    lines = []
    for entry in payload["contributors"]:
        merged = entry["merged_prs"]
        lines.append(
            f"ranked   {entry['login']}: {entry['commits']} commits, "
            f"{merged} merged pull request{'' if merged == 1 else 's'}"
        )
    for entry in payload["excluded"]:
        lines.append(f"excluded {entry['login']}: {entry['reason']}")
    for login in payload["issue_activity_without_ranked_commits"]:
        lines.append(f"noted    {login}: closed-issue activity, no ranked commits")
    return lines


THANKS_START = "<!-- contributors:start -->"
THANKS_END = "<!-- contributors:end -->"
CONTRIBUTORS_PATH = "CONTRIBUTORS.md"
README_PATH = "README.md"

GENERATED_NOTICE = (
    "<!-- Generated by scripts/contributors.py. Do not edit by hand: the weekly\n"
    "     refresh overwrites this file. Change the generator instead. -->"
)


def render_contributors(payload):
    """Render the ranked file. One computation feeds this and the README block."""
    lines = [
        GENERATED_NOTICE,
        "",
        "# Contributors",
        "",
        "The people who have taken a job from this repository's queue and finished",
        "it, ranked by merged work. Regenerated weekly from the repository's own",
        "history.",
        "",
    ]
    if not payload["contributors"]:
        lines += ["No external contributors are recorded yet.", ""]
    else:
        lines += [
            "| # | Contributor | Commits | Merged PRs |",
            "| --- | --- | --- | --- |",
        ]
        for entry in payload["contributors"]:
            lines.append(
                f"| {entry['rank']} | [@{entry['login']}](https://github.com/{entry['login']}) "
                f"| {entry['commits']} | {entry['merged_prs']} |"
            )
        lines.append("")
    lines += [
        "## What this establishes",
        "",
        "Commit and merged-pull-request counts as GitHub resolves them, with one",
        "account per person even where the same person committed under several email",
        "addresses. Runtime host identities are excluded, and so is the repository",
        "owner. The Shoggoth is excluded too: ADR-016 makes it the author of governed",
        "agent work, which is not the same as being a person who helped.",
        "",
        "It does not establish who wrote which line, how much judgement a commit",
        "carried, or anything about a contributor beyond the account they chose. A",
        "merge that discards authorship reduces a count here and this repository",
        "cannot detect that; see issue #466.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_thanks(payload):
    """Render the README block: handles, and nothing else.

    No counts, ranks or dates, so the README carries no aggregate about anyone.
    A login may itself contain digits, so `radup1337` is a handle and not a
    number; the test for this asserts that nothing numeric survives once the
    handles are removed, rather than banning digits outright.
    """
    logins = [entry["login"] for entry in payload["contributors"]]
    if not logins:
        body = "No external contributors are recorded yet."
    elif len(logins) == 1:
        body = f"Thanks to @{logins[0]}."
    else:
        body = "Thanks to " + ", ".join(f"@{name}" for name in logins[:-1]) + f" and @{logins[-1]}."
    return f"{THANKS_START}\n\n## Thanks\n\n{body}\n\n{THANKS_END}"


def splice_thanks(readme_text, block):
    """Replace the marked region, or append it once if the markers are absent.

    Everything outside the two markers is returned byte for byte. A generator
    bug can then damage the block and nothing else in the file.
    """
    start = readme_text.find(THANKS_START)
    end = readme_text.find(THANKS_END)
    if start == -1 and end == -1:
        separator = "" if readme_text.endswith("\n") else "\n"
        return f"{readme_text}{separator}\n{block}\n"
    if start == -1 or end == -1:
        raise Stop(
            f"{README_PATH} carries one thanks marker but not the other; "
            "restore both or remove both"
        )
    if end < start:
        raise Stop(f"{README_PATH} has the thanks markers in the wrong order")
    return readme_text[:start] + block + readme_text[end + len(THANKS_END):]


def atomic_write(path, text):
    """Write whole or not at all, so a killed run leaves no half-written artefact."""
    path = Path(path)
    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=str(path.parent), prefix=f".{path.name}.", delete=False
    )
    try:
        with handle as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(handle.name, path)
    except BaseException:
        try:
            os.unlink(handle.name)
        except OSError:
            pass
        raise


def rendered(root, payload):
    """Both artefacts, rendered from one payload, so they cannot disagree."""
    readme = Path(root) / README_PATH
    return {
        CONTRIBUTORS_PATH: render_contributors(payload),
        README_PATH: splice_thanks(readme.read_text(encoding="utf-8"), render_thanks(payload)),
    }


def check_artefacts(root, payload):
    """Name every artefact that does not match the computation."""
    stale = []
    for relative, text in rendered(root, payload).items():
        target = Path(root) / relative
        if not target.is_file():
            stale.append(f"{relative} is absent")
        elif target.read_text(encoding="utf-8") != text:
            stale.append(f"{relative} does not match the computed ranking")
    return stale


def write_artefacts(root, payload):
    """Render everything before writing anything."""
    documents = rendered(root, payload)
    for relative, text in sorted(documents.items()):
        atomic_write(Path(root) / relative, text)
    return sorted(documents)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="contributors.py",
        description="Rank the repository's human contributors from resolved identity.",
    )
    parser.add_argument(
        "--host-set",
        action="store_true",
        help="print the loaded runtime-host classification set as JSON and exit",
    )
    parser.add_argument(
        "--verify-host-set",
        action="store_true",
        help="stop unless this module's host set matches hexctl.py's declaration",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="compute the ranking and print it as JSON",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"regenerate {CONTRIBUTORS_PATH} and the {README_PATH} thanks block",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero, naming the file, when an artefact is out of date",
    )
    parser.add_argument(
        "--repo",
        default=REPOSITORY,
        help=f"owner/name to rank (default {REPOSITORY})",
    )
    return parser


def repository_root() -> Path:
    return Path(__file__).resolve().parents[1]


def main(argv=None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(sys.argv[1:] if argv is None else argv)
    hexctl = repository_root() / HEXCTL_RELATIVE
    try:
        if arguments.host_set:
            print(json.dumps(host_set_payload(), indent=2, sort_keys=True))
            return 0
        if arguments.verify_host_set:
            verify_host_set_parity(hexctl)
            print("host set matches hexctl.py")
            return 0
        if arguments.json or arguments.write or arguments.check:
            payload = compute(
                http_reader(),
                repo=arguments.repo,
                hexctl_path=hexctl if hexctl.is_file() else None,
            )
            for line in classification_lines(payload):
                print(line, file=sys.stderr)
            if arguments.json:
                print(json.dumps(payload, indent=2, sort_keys=True))
                return 0
            root = repository_root()
            if arguments.check:
                stale = check_artefacts(root, payload)
                for item in stale:
                    print(f"contributors.py: {item}", file=sys.stderr)
                if stale:
                    return 1
                print("both artefacts match the computed ranking")
                return 0
            for relative in write_artefacts(root, payload):
                print(f"wrote {relative}", file=sys.stderr)
            return 0
    except Stop as stop:
        print(f"contributors.py: {stop}", file=sys.stderr)
        return 2
    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
