#!/usr/bin/env python3
"""Rank human contributors from resolved commits and merged pull requests.

CONTRIBUTORS.md and the thanks block in README.md are generated by this script.
Do not hand-edit either one: the daily refresh overwrites whatever is there.
Skills commits supply the first ordering key. Human authors of merged pull
requests in Shoggoth Wave Atlas also qualify, and merged PRs across both
repositories supply the second key.

This module holds the classification primitives. Which identities are runtime
hosts rather than contributors is decided by ADR-016, and the mechanical set it
refers to lives in plugins/hexaemeron/skills/fiat/scripts/hexctl.py. The copy
below is kept equal to that one by tests/test_contributors.py, which fails when
either side is edited alone.

The Wildcat-Origin trailer is deliberately not part of the classification. It
records which tool performed the work, not who decided it: every commit by this
repository's external human contributors carries it, and some commits authored
by a runtime host carry none. See docs/contributors/study.md, item 4.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile
import urllib.parse
import urllib.request

# Kept equal to hexctl.py's frozensets by tests/test_contributors.py.
HOST_IDENTITY_NAMES = frozenset(
    {
        "aider",
        "anthropic",
        "chatgpt",
        "claude",
        "claude code",
        "claude[bot]",
        "codex",
        "copilot",
        "cursor",
        "devin",
        "gemini",
        "gemini code assist",
        "github copilot",
        "openai",
    }
)
HOST_IDENTITY_EMAILS = frozenset(
    {
        "noreply@anthropic.com",
        "noreply@openai.com",
    }
)
HOST_PR_LOGINS = frozenset(
    {
        "app/claude",
        "chatgpt[bot]",
        "claude[bot]",
        "codex[bot]",
        "copilot[bot]",
    }
)

# A GitHub login is 1 to 39 characters of ASCII alphanumerics and hyphens, and
# may neither start nor end with a hyphen. Nothing matching this can carry
# Markdown syntax, which is why the login is the only API field either artefact
# is allowed to contain.
LOGIN_RE = re.compile(r"\A[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?\Z")

# Excluded at the Creator's own instruction: the repository owner is not ranked
# among the people the repository thanks. This is a decision, not something
# derived from the history, so it is named here rather than inferred.
EXCLUDED_MAINTAINERS = frozenset({"laurenceday"})

# The Shoggoth is the author of governed agent work under ADR-016, so it is a
# legitimate Git author and a legitimate GitHub contributor. It is still not a
# human being thanked for helping. It is deliberately NOT in the runtime-host
# set: a host identity is a transport that should never have been an author,
# whereas this one should. Different reason, different set, different message.
AGENT_LOGINS = frozenset({"shoggoth-wildcat"})

REPOSITORY = "wildcat-finance/skills"
WAVE_ATLAS_REPOSITORY = "wildcat-finance/shoggoth-wave-atlas"
SUPPLEMENTAL_PR_REPOSITORIES = (WAVE_ATLAS_REPOSITORY,)
HEXCTL_RELATIVE = "plugins/hexaemeron/skills/fiat/scripts/hexctl.py"
PARITY_SET_NAMES = ("HOST_IDENTITY_EMAILS", "HOST_IDENTITY_NAMES", "HOST_PR_LOGINS")
API_HOST = "api.github.com"
API_ROOT = f"https://{API_HOST}"
REPO_RE = re.compile(r"\A[A-Za-z0-9._-]{1,100}/[A-Za-z0-9._-]{1,100}\Z")
PAGE_SIZE = 100
MAX_PAGES = 50
# GitHub's search API refuses to serve past the first thousand results of any
# query, whatever the pagination asks for.
SEARCH_RESULT_CAP = 1000
RESPONSE_LIMIT = 4 * 1024 * 1024
TIMEOUT_SECONDS = 30


class Stop(Exception):
    """A fail-closed stop. The message names the identity or field at fault."""


def is_host_identity(name: str, email: str) -> bool:
    """Recognise known runtime identities without reclassifying human authors."""
    return (
        name.strip().casefold() in HOST_IDENTITY_NAMES
        or email.strip().casefold() in HOST_IDENTITY_EMAILS
    )


def is_host_login(login: str) -> bool:
    """Recognise a runtime identity by its GitHub login or app byline."""
    folded = login.strip().casefold()
    return folded in HOST_PR_LOGINS or folded in HOST_IDENTITY_NAMES


def valid_login(login: str) -> bool:
    """Accept only a login that cannot carry Markdown syntax into an artefact.

    Classification must exclude runtime hosts BEFORE calling this. Some host
    logins are deliberately not valid logins: `claude[bot]` and `app/claude`
    both fail here. Validating first would turn a routine host exclusion into
    the bad-grammar stop, which fails the run on an identity the host set
    already knows how to drop.
    """
    return bool(LOGIN_RE.match(login))


def host_set_payload() -> dict:
    """Report the loaded classification set, for inspection and for tests."""
    return {
        "schema": "wildcat-contributors-host-set/v1",
        "host_identity_names": sorted(HOST_IDENTITY_NAMES),
        "host_identity_emails": sorted(HOST_IDENTITY_EMAILS),
        "host_pr_logins": sorted(HOST_PR_LOGINS),
    }


def frozensets_from_source(path, prefix: str = "HOST_") -> dict:
    """Read every `HOST_* = frozenset({...})` module-level literal without importing.

    Discovery is by prefix, not by the names already known. A parity check that
    compares only what it knows cannot notice a new set. If hexctl.py grows a
    fourth host set, this module would miss a whole class of runtime identity
    and every check would still pass, so the prefix scan turns that into a stop
    naming the set nobody accounted for.
    """
    tree = ast.parse(Path(path).read_text(encoding="utf-8"), filename=str(path))
    found = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or not target.id.startswith(prefix):
            continue
        call = node.value
        if (
            not isinstance(call, ast.Call)
            or not isinstance(call.func, ast.Name)
            or call.func.id != "frozenset"
        ):
            # A HOST_* name that is not a frozenset is not a classification set.
            # hexctl.py has HOST_BYLINE_RE, a compiled pattern. Skipping it is
            # deliberate; a genuinely missing set is caught by comparing the
            # discovered names, not by asserting shape here.
            continue
        if len(call.args) != 1:
            raise Stop(
                f"{target.id} in {Path(path).name} is frozenset() with "
                f"{len(call.args)} arguments, which cannot be read"
            )
        try:
            members = ast.literal_eval(call.args[0])
        except (ValueError, TypeError) as error:
            raise Stop(
                f"{target.id} in {Path(path).name} is a frozenset of something "
                f"other than a literal: {error}"
            ) from error
        found[target.id] = frozenset(members)
    return found


def verify_host_set_parity(hexctl_path) -> None:
    """Stop when this module's host set and Fiat's declaration have diverged.

    ADR-016 names one mechanical set of runtime host identities and Fiat owns
    it. The copy above exists so this stays a standalone root script. An
    unchecked copy can stop agreeing and rank a runtime identity as a person,
    so the divergence is a stop rather than a warning.
    """
    declared = frozensets_from_source(hexctl_path)
    if sorted(declared) != sorted(PARITY_SET_NAMES):
        missing = sorted(set(PARITY_SET_NAMES) - set(declared))
        extra = sorted(set(declared) - set(PARITY_SET_NAMES))
        raise Stop(
            "host set drift: hexctl.py and this module disagree about which "
            f"HOST_* sets exist (missing here: {missing or 'none'}; "
            f"present there and unaccounted for here: {extra or 'none'})"
        )
    ours = {
        "HOST_IDENTITY_EMAILS": HOST_IDENTITY_EMAILS,
        "HOST_IDENTITY_NAMES": HOST_IDENTITY_NAMES,
        "HOST_PR_LOGINS": HOST_PR_LOGINS,
    }
    for name in PARITY_SET_NAMES:
        if ours[name] != declared[name]:
            raise Stop(
                f"host set drift: {name} differs from hexctl.py "
                f"(only here: {sorted(ours[name] - declared[name]) or 'none'}; "
                f"only there: {sorted(declared[name] - ours[name]) or 'none'})"
            )


def rate_limit_aware_message(path, error, authenticated):
    """Say plainly when the answer is a token, rather than reporting a bare 403.

    The search endpoints allow 30 requests a minute with a token and 10 without.
    This generator issues two search calls per ranked contributor plus two more,
    so an unauthenticated run stops being viable at about four contributors. A
    bare "api read failed" sends whoever is on call looking for a network fault.
    """
    remaining = error.headers.get("X-RateLimit-Remaining") if error.headers else None
    retry_after = error.headers.get("Retry-After") if error.headers else None
    rate_limited = error.code in (403, 429) and (remaining == "0" or retry_after is not None)
    if not rate_limited:
        return f"api read failed for {path}: HTTP {error.code} {error.reason}"
    reset = error.headers.get("X-RateLimit-Reset") if error.headers else None
    detail = f"api rate limit reached on {path} (HTTP {error.code}"
    if retry_after:
        detail += f", retry after {retry_after}s"
    elif reset:
        detail += f", resets at unix {reset}"
    detail += "). "
    if authenticated:
        detail += (
            "This run was authenticated, so the limit is 30 search requests a "
            "minute; wait for the reset or reduce the number of ranked contributors."
        )
    else:
        detail += (
            "This run sent no token, so the limit is 10 search requests a minute. "
            "Set GITHUB_TOKEN or GH_TOKEN in the environment and rerun."
        )
    return detail


class RefuseOffHostRedirect(urllib.request.HTTPRedirectHandler):
    """Stop a redirect off the API host before the next request is issued.

    urllib copies every request header onto the redirected request except
    content-length and content-type, so an Authorization bearer token travels to
    wherever the redirect points. Checking the final URL after urlopen returns is
    too late: by then the token has already been sent to that host.
    """

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        host = urllib.parse.urlsplit(newurl).netloc
        if host != API_HOST:
            raise Stop(f"api request was redirected off {API_HOST} to {host!r}")
        return super().redirect_request(req, fp, code, msg, headers, newurl)


def http_reader():
    """Return a reader that fetches one API path and parses its JSON body.

    Injectable so every test runs offline against recorded fixtures. The real
    reader is the only place this module touches the network.
    """

    import urllib.error
    import urllib.parse
    import urllib.request

    opener = urllib.request.build_opener(RefuseOffHostRedirect)

    def read(path: str):
        if not path.startswith("/"):
            raise Stop(f"api path must be absolute: {path!r}")
        request = urllib.request.Request(
            API_ROOT + path,
            headers={
                "Accept": "application/vnd.github+json",
                "User-Agent": "wildcat-contributors",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
        if token:
            # Read from the environment only. A token on the command line would
            # reach the process table and the shell history.
            request.add_header("Authorization", f"Bearer {token}")
        try:
            with opener.open(request, timeout=TIMEOUT_SECONDS) as response:
                landed = urllib.parse.urlsplit(response.geturl()).netloc
                if landed != API_HOST:
                    raise Stop(f"api response came from {landed!r}, not {API_HOST}")
                raw = response.read(RESPONSE_LIMIT + 1)
        except urllib.error.HTTPError as error:
            # HTTPError subclasses URLError, so catching only URLError would
            # report a 403 as a generic read failure and lose the one field that
            # says what to do about it.
            raise Stop(rate_limit_aware_message(path, error, bool(token))) from error
        except urllib.error.URLError as error:
            raise Stop(f"api read failed for {path}: {error}") from error
        except OSError as error:
            raise Stop(f"api read failed for {path}: {error}") from error
        if len(raw) > RESPONSE_LIMIT:
            raise Stop(f"api response for {path} exceeded {RESPONSE_LIMIT} bytes")
        try:
            return json.loads(raw.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as error:
            raise Stop(f"api response for {path} was not JSON: {error}") from error

    return read


def exclusion_reason(login, kind, excluded=EXCLUDED_MAINTAINERS):
    """Classify one account, returning a reason only when it is excluded."""
    if is_host_login(login):
        return "runtime host identity"
    if kind == "Bot":
        # ADR-016 records that the mechanical set does not cover unfamiliar
        # future host names. Ranking one would put a runtime in a file that
        # thanks people, so an unrecognised bot stops the run by name.
        raise Stop(
            f"unknown identity: {login!r} is a Bot that is not in the host set; "
            "extend HOST_PR_LOGINS in hexctl.py and here, then rerun"
        )
    if kind != "User":
        raise Stop(f"unknown identity: {login!r} has account type {kind!r}, not User or Bot")
    if login in AGENT_LOGINS:
        return "Shoggoth agent identity, not a human contributor"
    if login in excluded:
        return "repository owner, excluded by decision"
    if not valid_login(login):
        raise Stop(f"{login!r} is not a valid GitHub login and cannot be rendered")
    return None


def classify(rows, excluded=EXCLUDED_MAINTAINERS):
    """Split contributor rows into ranked candidates and named exclusions.

    Every row lands in exactly one of three places: a candidate, an exclusion
    with a reason, or a stop. There is no silent fourth outcome, because the
    cost of one is a runtime identity thanked as a person.
    """
    candidates, exclusions = [], []
    for row in rows:
        if not isinstance(row, dict):
            raise Stop(f"contributor row is not an object: {row!r}")
        login = row.get("login")
        kind = row.get("type")
        if not isinstance(login, str) or not login:
            raise Stop(f"contributor row carries no login: {row!r}")
        contributions = row.get("contributions")
        if not isinstance(contributions, int) or contributions < 0:
            raise Stop(f"{login} carries a non-integer contribution count: {contributions!r}")

        reason = exclusion_reason(login, kind, excluded=excluded)
        if reason:
            exclusions.append({"login": login, "reason": reason})
            continue
        candidates.append({"login": login, "commits": contributions})
    return candidates, exclusions


def rank(entries):
    """Order by commits, then merged pull requests, then login.

    The final key makes equal counts order identically on every run, so a
    refresh that changed nothing produces no diff.
    """
    return sorted(
        entries,
        key=lambda entry: (-entry["commits"], -entry.get("merged_prs", 0), entry["login"]),
    )


def merged_pr_count(read, repo, login):
    payload = read(f"/search/issues?q=repo:{repo}+type:pr+is:merged+author:{login}&per_page=1")
    total = payload.get("total_count") if isinstance(payload, dict) else None
    if not isinstance(total, int) or total < 0:
        raise Stop(f"merged pull-request count for {login} was not a count: {total!r}")
    return total


def merged_pr_authors(read, repo, excluded=EXCLUDED_MAINTAINERS):
    """Count human authors of merged PRs in one supplemental repository.

    The pulls endpoint is used instead of search so the read can paginate past
    GitHub search's thousand-result cap. Closed, unmerged pull requests do not
    qualify anyone. Every merged row is either counted, excluded with a named
    reason, or refused.
    """
    rows = read_all_pages(
        read,
        f"/repos/{repo}/pulls?state=closed&per_page={{per_page}}&page={{page}}",
        f"closed pull requests for {repo}",
    )
    counts, exclusions = {}, []
    for row in rows:
        if not isinstance(row, dict):
            raise Stop(f"pull-request row for {repo} is not an object: {row!r}")
        if "merged_at" not in row:
            raise Stop(f"pull-request row for {repo} carries no merged_at field: {row!r}")
        merged_at = row["merged_at"]
        if merged_at is None:
            continue
        if not isinstance(merged_at, str) or not merged_at:
            raise Stop(
                f"pull-request row for {repo} carries an invalid merged_at field: "
                f"{merged_at!r}"
            )
        user = row.get("user")
        if not isinstance(user, dict):
            number = row.get("number", "unknown")
            raise Stop(f"merged pull request {repo}#{number} carries no author")
        login = user.get("login")
        kind = user.get("type")
        if not isinstance(login, str) or not login:
            number = row.get("number", "unknown")
            raise Stop(f"merged pull request {repo}#{number} carries no author login")
        reason = exclusion_reason(login, kind, excluded=excluded)
        if reason:
            exclusions.append({"login": login, "reason": reason})
            continue
        counts[login] = counts.get(login, 0) + 1
    return counts, exclusions


def merge_exclusions(groups):
    """Deduplicate exclusions observed in more than one repository."""
    by_login = {}
    for group in groups:
        for entry in group:
            login, reason = entry["login"], entry["reason"]
            previous = by_login.get(login)
            if previous is not None and previous != reason:
                raise Stop(
                    f"{login} was excluded for conflicting reasons: "
                    f"{previous!r} and {reason!r}"
                )
            by_login[login] = reason
    return [{"login": login, "reason": reason} for login, reason in by_login.items()]


def corroborate_human_authorship(read, repo, login):
    """Confirm at least one of a login's commits was authored by a non-host identity.

    The contributors endpoint resolves several author emails to one account,
    which is the whole reason it is used. This checks the resolution did not
    quietly gather a runtime's commits under a human login.
    """
    payload = read(f"/search/commits?q=repo:{repo}+author:{login}&per_page=20")
    items = payload.get("items") if isinstance(payload, dict) else None
    if not isinstance(items, list) or not items:
        raise Stop(f"no commits found for {login}, so human authorship is unconfirmed")
    identities = []
    for item in items:
        author = (item.get("commit") or {}).get("author") or {}
        identities.append((str(author.get("name", "")), str(author.get("email", ""))))
    human = [pair for pair in identities if not is_host_identity(*pair)]
    if not human:
        raise Stop(
            f"every sampled commit for {login} was authored by a runtime host identity"
        )
    return len(human), len(identities)


def issue_coverage(read, repo, ranked_logins, excluded_logins):
    """Name humans with closed-issue activity but no ranked commits.

    Issue activity contributes no rank, per the request: commits and merges
    only. Reporting it separately is what keeps a person who worked an issue
    without landing a commit from disappearing without trace.
    """
    # The search API serves at most SEARCH_RESULT_CAP results however it is
    # paged, so coverage past that point is impossible through this endpoint.
    # That limit is a caveat carried in the result, not a stop: this list
    # informs, it does not rank, so a partial read must be visible without
    # failing the whole refresh. The first live run failed exactly here, on a
    # repository that had grown from 55 closed issues to 391 while the code
    # both read one page and stopped on the shortfall its own comment said it
    # would only report.
    items, total = [], None
    for page in range(1, SEARCH_RESULT_CAP // PAGE_SIZE + 1):
        payload = read(
            f"/search/issues?q=repo:{repo}+type:issue+state:closed"
            f"&per_page={PAGE_SIZE}&page={page}"
        )
        if not isinstance(payload, dict):
            raise Stop(f"closed-issue search returned {type(payload).__name__}, not an object")
        batch = payload.get("items")
        if not isinstance(batch, list):
            raise Stop("closed-issue search returned no items list")
        reported = payload.get("total_count")
        if isinstance(reported, int):
            total = reported
        items.extend(batch)
        if len(batch) < PAGE_SIZE or (total is not None and len(items) >= total):
            break
    caveat = None
    if total is not None and total > len(items):
        caveat = (
            f"closed-issue coverage reads {len(items)} of {total} issues; the "
            f"search endpoint serves at most {SEARCH_RESULT_CAP}, so activity "
            "past that point is invisible to this list"
        )
    seen, uncounted = set(), []
    for item in items:
        login = ((item.get("user") or {}).get("login")) or ""
        if not login or login in seen:
            continue
        seen.add(login)
        if login in ranked_logins or login in excluded_logins or is_host_login(login):
            continue
        uncounted.append(login)
    return sorted(uncounted), caveat


def read_all_pages(read, path_template, label):
    """Read every page, or stop. A silent cap reads afterwards as full coverage.

    The alternative is a truncated list that looks complete: a repository with
    more than one page of contributors would quietly lose everyone past the
    first hundred, and the artefact would give no sign of it.
    """
    collected = []
    for page in range(1, MAX_PAGES + 1):
        rows = read(path_template.format(page=page, per_page=PAGE_SIZE))
        if not isinstance(rows, list):
            raise Stop(f"{label} returned {type(rows).__name__}, not a list")
        collected.extend(rows)
        if len(rows) < PAGE_SIZE:
            return collected
    raise Stop(
        f"{label} still had pages after {MAX_PAGES} of {PAGE_SIZE}; "
        "raise MAX_PAGES rather than shipping a truncated list"
    )


def validate_repository(repo):
    if not isinstance(repo, str) or not REPO_RE.match(repo):
        raise Stop(f"repository must be owner/name with no query syntax: {repo!r}")


def compute(
    read,
    repo=REPOSITORY,
    hexctl_path=None,
    excluded=EXCLUDED_MAINTAINERS,
    supplemental_pr_repositories=SUPPLEMENTAL_PR_REPOSITORIES,
):
    """Produce the whole ranking in one pass, so nothing downstream recomputes it."""
    validate_repository(repo)
    if isinstance(supplemental_pr_repositories, str):
        raise Stop("supplemental pull-request repositories must be a sequence, not one string")
    try:
        supplemental_pr_repositories = tuple(supplemental_pr_repositories)
    except TypeError as error:
        raise Stop("supplemental pull-request repositories must be a sequence") from error
    seen_repositories = {repo}
    for supplemental in supplemental_pr_repositories:
        validate_repository(supplemental)
        if supplemental in seen_repositories:
            raise Stop(f"duplicate pull-request repository: {supplemental}")
        seen_repositories.add(supplemental)
    pull_request_repositories = (repo,) + supplemental_pr_repositories
    if hexctl_path is not None:
        verify_host_set_parity(hexctl_path)
    rows = read_all_pages(
        read,
        f"/repos/{repo}/contributors?per_page={{per_page}}&page={{page}}",
        "contributors endpoint",
    )
    candidates, primary_exclusions = classify(rows, excluded=excluded)
    candidates_by_login = {}
    for entry in candidates:
        login = entry["login"]
        if login in candidates_by_login:
            raise Stop(f"contributors endpoint returned duplicate login: {login}")
        primary_prs = merged_pr_count(read, repo, login)
        entry["merged_prs_by_repository"] = {
            repository: primary_prs if repository == repo else 0
            for repository in pull_request_repositories
        }
        entry["qualified_by"] = [f"{repo}:resolved-commit"]
        human, sampled = corroborate_human_authorship(read, repo, entry["login"])
        entry["human_authored_sampled"] = human
        entry["sampled"] = sampled
        candidates_by_login[login] = entry

    exclusion_groups = [primary_exclusions]
    for supplemental in supplemental_pr_repositories:
        author_counts, supplemental_exclusions = merged_pr_authors(
            read, supplemental, excluded=excluded
        )
        exclusion_groups.append(supplemental_exclusions)
        for login, count in author_counts.items():
            entry = candidates_by_login.get(login)
            if entry is None:
                entry = {
                    "login": login,
                    "commits": 0,
                    "merged_prs_by_repository": {
                        repository: 0 for repository in pull_request_repositories
                    },
                    "qualified_by": [],
                    "human_authored_sampled": 0,
                    "sampled": 0,
                }
                candidates_by_login[login] = entry
            entry["merged_prs_by_repository"][supplemental] += count
            entry["qualified_by"].append(
                f"{supplemental}:merged-pull-request"
            )

    exclusions = merge_exclusions(exclusion_groups)
    for entry in candidates_by_login.values():
        entry["merged_prs"] = sum(entry["merged_prs_by_repository"].values())
    ranked = rank(candidates_by_login.values())
    ranked_logins = {entry["login"] for entry in ranked}
    excluded_logins = {entry["login"] for entry in exclusions}
    # The net is unconditional and checks the module's declared truth, not the
    # caller's `excluded` argument. That argument shapes classification; if it
    # could also switch off the last check, the check would be worth nothing
    # exactly when classification had already gone wrong.
    for login in sorted(EXCLUDED_MAINTAINERS | AGENT_LOGINS | set(excluded)):
        if login in ranked_logins:
            raise Stop(f"{login} is excluded but reached the ranked list")
    issue_notes, issue_caveat = issue_coverage(read, repo, ranked_logins, excluded_logins)
    payload = {
        "schema": "wildcat-contributors/v2",
        "repository": repo,
        "pull_request_repositories": list(pull_request_repositories),
        "digest": ranking_digest(ranked),
        "contributors": [
            {
                "rank": index,
                "login": entry["login"],
                "commits": entry["commits"],
                "merged_prs": entry["merged_prs"],
                "merged_prs_by_repository": entry["merged_prs_by_repository"],
                "qualified_by": entry["qualified_by"],
                "human_authored_sampled": entry["human_authored_sampled"],
                "commits_sampled": entry["sampled"],
            }
            for index, entry in enumerate(ranked, start=1)
        ],
        "excluded": sorted(exclusions, key=lambda item: item["login"]),
        "issue_activity_without_ranked_commits": issue_notes,
        "issue_coverage_caveat": issue_caveat,
    }
    return payload


def ranking_digest(ranked):
    """A stable digest of the ranking alone, for the unattended run's summary.

    Covers the ordered logins and their two counts and nothing else, so the
    digest changes when the published ranking changes and not when an unrelated
    field is added to the payload.
    """
    material = json.dumps(
        [[e["login"], e["commits"], e["merged_prs"]] for e in ranked],
        separators=(",", ":"),
    )
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def classification_lines(payload):
    """One line per identity, so `why is this person not on the list` is answerable."""
    lines = []
    for entry in payload["contributors"]:
        merged = entry["merged_prs"]
        repository_count = len(payload["pull_request_repositories"])
        repository_word = "repository" if repository_count == 1 else "repositories"
        lines.append(
            f"ranked   {entry['login']}: {entry['commits']} Skills commits, "
            f"{merged} merged pull request{'' if merged == 1 else 's'} across "
            f"{repository_count} {repository_word}"
        )
    for entry in payload["excluded"]:
        lines.append(f"excluded {entry['login']}: {entry['reason']}")
    for login in payload["issue_activity_without_ranked_commits"]:
        lines.append(f"noted    {login}: closed-issue activity, no ranked commits")
    if payload.get("issue_coverage_caveat"):
        lines.append(f"caveat   {payload['issue_coverage_caveat']}")
    return lines


THANKS_START = "<!-- contributors:start -->"
THANKS_END = "<!-- contributors:end -->"
CONTRIBUTORS_PATH = "CONTRIBUTORS.md"
README_PATH = "README.md"

GENERATED_NOTICE = (
    "<!-- Generated by scripts/contributors.py. Do not edit by hand: the daily\n"
    "     refresh overwrites this file. Change the generator instead. -->"
)


def render_contributors(payload):
    """Render the ranked file. One computation feeds this and the README block."""
    lines = [
        GENERATED_NOTICE,
        "",
        "# Contributors",
        "",
        "This list ranks human accounts with resolved commits in Wildcat Skills or",
        "an authored, merged pull request in Shoggoth Wave Atlas. It is regenerated",
        "daily from both repositories' public history.",
        "",
    ]
    if not payload["contributors"]:
        lines += ["No external contributors are recorded yet.", ""]
    else:
        lines += [
            "## Ranking",
            "",
            "| # | Contributor | Skills commits | Merged PRs across both repos |",
            "| --- | --- | --- | --- |",
        ]
        for entry in payload["contributors"]:
            lines.append(
                f"| {entry['rank']} | [@{entry['login']}](https://github.com/{entry['login']}) "
                f"| {entry['commits']} | {entry['merged_prs']} |"
            )
        lines.append("")
    lines += [
        "## What this establishes",
        "",
        "The commit column counts commits GitHub resolves to an account in",
        "`wildcat-finance/skills`. The merged-PR column combines authored, merged",
        "pull requests in that repository and `wildcat-finance/shoggoth-wave-atlas`.",
        "A merged Atlas PR qualifies its human author even with no Skills commit.",
        "Runtime hosts, the repository owner and the Shoggoth are excluded. ADR-016",
        "makes the Shoggoth the author of governed agent work, which is not the same",
        "as being a person who helped.",
        "",
        "It does not establish who wrote which line, who else worked on a pull",
        "request, how much judgement a commit carried, or anything about a",
        "contributor beyond the account they chose. A merge that discards authorship",
        "reduces a count here and this repository cannot detect that; see issue #466.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_thanks(payload):
    """Render the README block: handles, and nothing else.

    No counts, ranks or dates, so the README carries no aggregate about anyone.
    A login may itself contain digits, so `radup1337` is a handle and not a
    number; the test for this asserts that nothing numeric survives once the
    handles are removed, rather than banning digits outright.
    """
    logins = [entry["login"] for entry in payload["contributors"]]
    if not logins:
        body = "No external contributors are recorded yet."
    elif len(logins) == 1:
        body = f"Thanks to @{logins[0]}."
    else:
        body = "Thanks to " + ", ".join(f"@{name}" for name in logins[:-1]) + f" and @{logins[-1]}."
    return f"{THANKS_START}\n\n## Thanks\n\n{body}\n\n{THANKS_END}"


def splice_thanks(readme_text, block):
    """Replace the marked region, or append it once if the markers are absent.

    Everything outside the two markers is returned byte for byte. A generator
    bug can then damage the block and nothing else in the file.
    """
    start = readme_text.find(THANKS_START)
    end = readme_text.find(THANKS_END)
    if start == -1 and end == -1:
        separator = "" if readme_text.endswith("\n") else "\n"
        return f"{readme_text}{separator}\n{block}\n"
    if start == -1 or end == -1:
        raise Stop(
            f"{README_PATH} carries one thanks marker but not the other; "
            "restore both or remove both"
        )
    if end < start:
        raise Stop(f"{README_PATH} has the thanks markers in the wrong order")
    return readme_text[:start] + block + readme_text[end + len(THANKS_END):]


DEFAULT_FILE_MODE = 0o644


def atomic_write(path, text):
    """Write whole or not at all, so a killed run leaves no half-written artefact.

    The replacement carries the temporary file's mode, and `NamedTemporaryFile`
    creates at 0600. Replacing a tracked file would therefore quietly narrow it
    from 0644, and git records only the executable bit so the diff would show
    nothing. An existing file keeps its mode; a new one gets 0644 like the rest
    of the repository.
    """
    path = Path(path)
    try:
        mode = stat.S_IMODE(path.stat().st_mode)
    except FileNotFoundError:
        mode = DEFAULT_FILE_MODE
    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=str(path.parent), prefix=f".{path.name}.", delete=False
    )
    try:
        with handle as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(handle.name, mode)
        os.replace(handle.name, path)
    except BaseException:
        try:
            os.unlink(handle.name)
        except OSError:
            pass
        raise


def rendered(root, payload):
    """Both artefacts, rendered from one payload, so they cannot disagree."""
    readme = Path(root) / README_PATH
    try:
        existing = readme.read_text(encoding="utf-8")
    except FileNotFoundError as error:
        raise Stop(
            f"{README_PATH} is absent, so the thanks block has nowhere to go"
        ) from error
    except (OSError, UnicodeDecodeError) as error:
        raise Stop(f"{README_PATH} cannot be read as UTF-8 text: {error}") from error
    return {
        CONTRIBUTORS_PATH: render_contributors(payload),
        README_PATH: splice_thanks(existing, render_thanks(payload)),
    }


def check_artefacts(root, payload):
    """Name every artefact that does not match the computation."""
    stale = []
    for relative, text in rendered(root, payload).items():
        target = Path(root) / relative
        if not target.is_file():
            stale.append(f"{relative} is absent")
        elif target.read_text(encoding="utf-8") != text:
            stale.append(f"{relative} does not match the computed ranking")
    return stale


def sweep_orphans(root, names):
    """Remove this script's own abandoned temporaries, and nothing else.

    A hard-killed write leaves `.<artefact>.<random>` beside the target. It is
    untracked and not ignored by default, so it shows up as a repository change
    and could be swept into a commit by a broad `git add`. The match is anchored
    to the exact artefact name this script writes, and only regular files are
    removed, so nothing outside the script's own litter is in scope.
    """
    removed = []
    for name in names:
        for candidate in Path(root).glob(f".{name}.*"):
            if candidate.is_file() and not candidate.is_symlink():
                try:
                    candidate.unlink()
                except OSError:
                    continue
                removed.append(candidate.name)
    return sorted(removed)


def write_artefacts(root, payload):
    """Render everything before writing anything."""
    documents = rendered(root, payload)
    sweep_orphans(root, sorted(documents))
    for relative, text in sorted(documents.items()):
        atomic_write(Path(root) / relative, text)
    return sorted(documents)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="contributors.py",
        description="Rank the repository's human contributors from resolved identity.",
    )
    parser.add_argument(
        "--host-set",
        action="store_true",
        help="print the loaded runtime-host classification set as JSON and exit",
    )
    parser.add_argument(
        "--verify-host-set",
        action="store_true",
        help="stop unless this module's host set matches hexctl.py's declaration",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="compute the ranking and print it as JSON",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"regenerate {CONTRIBUTORS_PATH} and the {README_PATH} thanks block",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero, naming the file, when an artefact is out of date",
    )
    parser.add_argument(
        "--repo",
        default=REPOSITORY,
        help=f"owner/name whose resolved commits are ranked (default {REPOSITORY})",
    )
    parser.add_argument(
        "--supplemental-pr-repo",
        action="append",
        dest="supplemental_pr_repositories",
        help=(
            "owner/name whose merged PR authors also qualify; repeat for more "
            f"(default {', '.join(SUPPLEMENTAL_PR_REPOSITORIES)})"
        ),
    )
    return parser


def repository_root() -> Path:
    return Path(__file__).resolve().parents[1]


def main(argv=None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(sys.argv[1:] if argv is None else argv)
    hexctl = repository_root() / HEXCTL_RELATIVE
    try:
        if arguments.host_set:
            print(json.dumps(host_set_payload(), indent=2, sort_keys=True))
            return 0
        if arguments.verify_host_set:
            verify_host_set_parity(hexctl)
            print("host set matches hexctl.py")
            return 0
        if arguments.json or arguments.write or arguments.check:
            payload = compute(
                http_reader(),
                repo=arguments.repo,
                hexctl_path=hexctl if hexctl.is_file() else None,
                supplemental_pr_repositories=(
                    tuple(arguments.supplemental_pr_repositories)
                    if arguments.supplemental_pr_repositories
                    else SUPPLEMENTAL_PR_REPOSITORIES
                ),
            )
            for line in classification_lines(payload):
                print(line, file=sys.stderr)
            if arguments.json:
                print(json.dumps(payload, indent=2, sort_keys=True))
                return 0
            root = repository_root()
            if arguments.check:
                stale = check_artefacts(root, payload)
                for item in stale:
                    print(f"contributors.py: {item}", file=sys.stderr)
                if stale:
                    return 1
                print("both artefacts match the computed ranking")
                return 0
            for relative in write_artefacts(root, payload):
                print(f"wrote {relative}", file=sys.stderr)
            return 0
    except Stop as stop:
        print(f"contributors.py: {stop}", file=sys.stderr)
        return 2
    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
