#!/usr/bin/env python3
"""Check Wildcat V1's assembly event emitters against their declarations.

    python3 scripts/emitter_declarations_v1.py build --from-git CLONE --out TABLE.json [--markdown TABLE.md]
    python3 scripts/emitter_declarations_v1.py check --from-git CLONE --table TABLE.json [--markdown TABLE.md] [--ref COMMIT]
    python3 scripts/emitter_declarations_v1.py check --from-https --table TABLE.json
    python3 scripts/emitter_declarations_v1.py crosscheck --solc SOLC

The V1 counterpart of scripts/emitter_declarations.py (#1361), for #1962. It
reuses that script's parser, type mapping and comparison, and its table's
row, mismatch, unreviewed and summary shapes. Three things differ, because V1
keeps no compiler input or output in its repository:

- The builds are Sourcify records, one per deployed contract that the
  accepted registry (`docs/kickoff/1359/targets.json`, row
  `wildcat-v1-ethereum-mainnet`) names. Each record's standard JSON input is
  pinned by the SHA-256 of its canonical form, the form the registry uses,
  and its compilation target's ABI by the SHA-256 of the ABI's canonical
  form. Where the registry pins a build input, the two digests must agree.
- Reach is contract-level. An emitter is reached by a build when a contract
  in the compilation target's own inheritance chain calls it. A call site in
  a library or a free function is not attributed; it is named instead.
- Each read `src/` file is bound to each build as equal, comments-only (the
  bytes differ only in comments and whitespace), differs, or absent.

`build` reads `wildcat-finance/wildcat-protocol` at `--ref` (default the
registry's V1 commit), every `.sol` file under `src/`, and the Sourcify
records the registry names, and writes the table. `check` takes the refs,
paths and digests from the committed table, refuses any read byte that
differs from it, regenerates the table and exits 1 on any byte difference.
`--ref` on `check` changes only the commit the `src/` bytes are read at.
`--sourcify-dir DIR` reads `DIR/<address>.json` Sourcify responses instead of
fetching them, under the same digest checks.

`crosscheck` needs the registry's solc. It compiles each registry-pinned
input with ABI-only output for every contract and compares each build's ABI
digest with the one that input yields. The market and controller builds are
instance records, so this is what ties their ABIs to the factory input the
registry pins. `build` and `check` never run a compiler.

Exit status: 0 when the table is written (`build`) or matches (`check`); 1 on
any refusal; 2 on a usage error. Each refusal line on stderr starts with one
prefix: `source-drift:` when read bytes, a Sourcify digest or the file list
differ from the table, `registry-difference:` when the registry no longer
names what the checker scans, `table-difference:` or `markdown-difference:`
when the source matches but the regenerated bytes differ, `read-failure:`
when a file, record or compiler run fails, `table-invalid:` when the
committed table is not a readable V1 table, and `abi-crosscheck:` when a
compiled ABI differs from its build's.

The scan is static text analysis. It runs no target code and makes no claim
about runtime behaviour, bytecode identity or capture completeness.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import urllib.parse
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import emitter_declarations as core  # noqa: E402

Refusal = core.Refusal
read_failure = core.read_failure

SCHEMA = core.SCHEMA
REPOSITORY = "wildcat-finance/wildcat-protocol"
REGISTRY_ROW = "wildcat-v1-ethereum-mainnet"
REGISTRY_PATH = "docs/kickoff/1359/targets.json"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMITTER_FILES = core.EMITTER_FILES
CHAIN_ID = 1
# The builds, in table order: a registry role, and for a role the registry
# lists as instances, which instance list stands for the template.
BUILD_ROLES = (
    ("market", "markets"),
    ("controller", "controllers"),
    ("factory", None),
    ("registry", None),
    ("sanctions-sentinel", None),
    ("lens", None),
)
SOURCIFY_HOST = "sourcify.dev"
SOURCIFY_FIELDS = "stdJsonInput,stdJsonOutput,compilation"
MAX_RECORD_BYTES = 8 * 1024 * 1024
MAX_SOURCE_BYTES = 8 * 1024 * 1024
TABLE_PATH = "docs/kickoff/1962/emitters.json"
MARKDOWN_PATH = "docs/kickoff/1962/emitters.md"

_ADDRESS = re.compile(r"^0x[0-9a-f]{40}$")
_FQN = re.compile(r"^([A-Za-z0-9_./-]+\.sol):([A-Za-z_]\w*)$")
_DEFINITION = re.compile(r"\b(contract|interface|library)\s+([A-Za-z_]\w*)([^{;]*)\{")
_LOG_SITE = re.compile(r"\blog[0-4]\s*\(")
_EMITTER_DEF = re.compile(r"\bfunction\s+(emit_[A-Za-z_]\w*)\s*\(")

STATIC_NOTE = (
    "This is a static text comparison of source declarations, assembly "
    "emitters and the compiler ABI Sourcify retains for each deployed build. "
    "It runs no target code and makes no claim about runtime behaviour, "
    "deployed bytecode identity or capture completeness. Runtime emitter "
    "fidelity for V1 is the separate campaign in "
    "[#1964](https://github.com/wildcat-finance/skills/issues/1964); this "
    "table is its input, not its result."
)
BUILD_NOTE = (
    "V1 keeps no compiler input or output in its repository. Each build "
    "below is the verified Sourcify record of a contract the registry "
    "names, and the table keeps Sourcify's match status for it. The market and controller builds are the records of the first "
    "instance the registry lists; the registry records that every instance "
    "reproduces its one template from the factory's input. The standard "
    "input digest is the SHA-256 of `json.dumps(stdJsonInput, sort_keys=True, "
    "separators=(',', ':'))`, the registry's canonical form, and the ABI "
    "digest applies the same form to the compilation target's ABI."
)
PIN_NOTE = (
    "Source commits are per component and come from the registry. The "
    "market, controller, factory and arch controller are built from "
    "`da74452a`, the commit the scan reads. The sanctions sentinel is built "
    "from `6164ddd4`, whose sources differ from `da74452a` only in their "
    "licence comments. The lens has no single source commit: the registry's "
    "best match is `488b30d0`, at 40 of 46 in-tree sources. Four of the "
    "other six match only `da74452a`, and `MarketErrors.sol` and "
    "`MarketEvents.sol` differ from every commit by one added licence line. "
    "The binding column of the source-file table shows, per build, whether "
    "each scanned file is equal, differs only in comments, differs, or is "
    "absent."
)
REACH_NOTE = (
    "Reached by names the builds whose compilation target inherits, directly "
    "or through its bases, a contract that calls the emitter. This is "
    "narrower than the V2 table's build-level rule: the V1 factory's input "
    "carries the market sources because it embeds the market's creation "
    "code, but the factory never runs a market emitter."
)


SUMMARY_MEANINGS = {
    "abi_checked_rows": "rows compared with at least one build's ABI",
    "binding_comments_only": "files some build carries with only comment or whitespace differences",
    "binding_differs": "files some build carries with differing code",
    "compared_rows": "rows whose comparison ran",
    "declaration_disagreements": "event names declared with more than one shape",
    "declarations_without_emitter": "declarations no assembly emitter pairs with",
    "emitters": "emit_ functions in the emitter files",
    "mismatch_rows": "rows with at least one mismatch class",
    "non_emitting_declarations": "declarations nothing under src/ emits",
    "rows": "emitter and same-named declaration pairs",
    "unreached_rows": "rows no build's compilation target reaches",
    "unreviewed": "entries the scan could not compare or attribute",
}


def canonical(value) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sourcify_url(address: str) -> str:
    return (f"https://{SOURCIFY_HOST}/server/v2/contract/{CHAIN_ID}/{address}"
            f"?fields={urllib.parse.quote(SOURCIFY_FIELDS, safe=',')}")


def abi_url(address: str) -> str:
    return f"https://{SOURCIFY_HOST}/server/v2/contract/{CHAIN_ID}/{address}?fields=stdJsonOutput"


def input_url(address: str) -> str:
    return f"https://{SOURCIFY_HOST}/server/v2/contract/{CHAIN_ID}/{address}?fields=stdJsonInput"


# --- readers ---------------------------------------------------------------


class HttpsReader(core.HttpsReader):
    """Read V1 blobs from raw.githubusercontent.com at a pinned commit."""

    @staticmethod
    def url(ref: str, path: str) -> str:
        ref, path = core._safe_ref(ref), core._safe_path(path)
        return f"https://{core.ALLOWED_HOST}/{REPOSITORY}/{ref}/{urllib.parse.quote(path)}"


class _SourcifyRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        target = urllib.parse.urlsplit(newurl)
        if target.scheme != "https" or target.hostname != SOURCIFY_HOST:
            raise read_failure(f"redirect to {target.scheme}://{target.hostname} refused")
        return super().redirect_request(req, fp, code, msg, headers, newurl)


class SourcifyReader:
    """Fetch one Sourcify v2 record per address from the fixed host."""

    def __init__(self, opener=None):
        self.opener = opener or urllib.request.build_opener(_SourcifyRedirect)

    def record(self, address: str) -> dict:
        url = sourcify_url(_safe_address(address))
        try:
            with self.opener.open(url, timeout=core.HTTPS_TIMEOUT_SECONDS * 4) as response:  # phylax: allow url: fixed host, validated address, digest-verified
                final = urllib.parse.urlsplit(response.geturl())
                if final.scheme != "https" or final.hostname != SOURCIFY_HOST:
                    raise read_failure(f"Sourcify record for {address} was served from {final.hostname}")
                data = response.read(MAX_RECORD_BYTES + 1)
        except Refusal:
            raise
        except (OSError, ValueError) as err:
            raise read_failure(f"Sourcify record for {address} could not be fetched: {type(err).__name__}") from None
        return _record_json(address, data)


class DirectorySourcifyReader:
    """Read saved Sourcify v2 responses named `<address>.json` from a directory."""

    def __init__(self, directory: str):
        self.directory = os.path.abspath(directory)

    def record(self, address: str) -> dict:
        path = os.path.join(self.directory, _safe_address(address) + ".json")
        try:
            with open(path, "rb") as fh:
                data = fh.read(MAX_RECORD_BYTES + 1)
        except OSError as err:
            raise read_failure(f"Sourcify record for {address} cannot be read: {type(err).__name__}") from None
        return _record_json(address, data)


def _safe_address(address: object) -> str:
    if not isinstance(address, str) or not _ADDRESS.match(address):
        raise read_failure(f"address {address!r} is not a lowercase 20-byte hex address")
    return address


def _record_json(address: str, data: bytes) -> dict:
    if len(data) > MAX_RECORD_BYTES:
        raise read_failure(f"Sourcify record for {address} exceeds the {MAX_RECORD_BYTES}-byte cap")
    try:
        record = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        raise read_failure(f"Sourcify record for {address} is not JSON") from None
    if not isinstance(record, dict):
        raise read_failure(f"Sourcify record for {address} is not a JSON object")
    return record


# --- registry --------------------------------------------------------------


def load_registry(root: str = ROOT) -> dict:
    """Return the V1 facts this checker scans, read from the accepted registry."""
    path = os.path.join(root, REGISTRY_PATH)
    try:
        with open(path, "rb") as fh:
            registry = json.loads(fh.read().decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as err:
        raise Refusal("registry-difference", f"{REGISTRY_PATH} cannot be read: {type(err).__name__}") from None
    rows = registry.get("targets") if isinstance(registry, dict) else None
    row = next((r for r in rows or [] if isinstance(r, dict) and r.get("id") == REGISTRY_ROW), None)
    if row is None:
        raise Refusal("registry-difference", f"{REGISTRY_PATH} has no row {REGISTRY_ROW}")
    try:
        source, deployment = row["source"], row["deployment"]
        if source["repository"] != f"https://github.com/{REPOSITORY}":
            raise Refusal("registry-difference", f"the V1 row names repository {source['repository']}")
        commit = core._safe_ref(source["commit"])
        emitter_paths = sorted(p["path"] for p in source["emitter_paths"])
        if emitter_paths != sorted(EMITTER_FILES):
            raise Refusal("registry-difference", f"the V1 row names emitter paths {emitter_paths}; "
                                                 f"this checker scans {sorted(EMITTER_FILES)}")
        pinned_inputs = {i["compilation_target"]: i["sha256"] for i in source["build_inputs"]}
        contracts = {c["address"]: c for c in deployment["contracts"]}
        builds = []
        for role, instances in BUILD_ROLES:
            if instances:
                listed = deployment["instances"][instances]
                address = listed[0]
                count = len(listed)
            else:
                matches = [a for a, c in contracts.items() if c["role"] == role]
                if len(matches) != 1:
                    raise Refusal("registry-difference", f"the V1 row lists {len(matches)} contracts with role {role}")
                address, count = matches[0], 1
            entry = contracts.get(address)
            if entry is None:
                raise Refusal("registry-difference", f"the V1 row lists {address} as a {role} but not as a contract")
            builds.append({
                "role": role, "address": _safe_address(address), "instances": count,
                "registry_name": entry["name"],
                "source_commit": core._safe_ref(entry["code_match"]["source_commit"]),
            })
        compiler = source["compiler"]["solc"]
    except Refusal:
        raise
    except (KeyError, TypeError, IndexError):
        raise Refusal("registry-difference", f"the {REGISTRY_ROW} row lacks a field this checker reads") from None
    return {"path": REGISTRY_PATH, "row": REGISTRY_ROW, "commit": commit, "compiler": compiler,
            "emitter_paths": emitter_paths, "pinned_inputs": pinned_inputs, "builds": builds}


# --- builds ----------------------------------------------------------------


def read_builds(reader, registry: dict) -> list[dict]:
    """Fetch and digest each registry build's Sourcify record."""
    builds = []
    for spec in registry["builds"]:
        record = reader.record(spec["address"])
        builds.append(parse_record(spec, record, registry))
    return builds


def parse_record(spec: dict, record: dict, registry: dict) -> dict:
    address = spec["address"]
    try:
        if str(record["address"]).lower() != address or str(record["chainId"]) != str(CHAIN_ID):
            raise read_failure(f"Sourcify record for {address} names another contract or chain")
        standard_input = record["stdJsonInput"]
        compilation = record["compilation"]
        fqn = compilation["fullyQualifiedName"]
        match = _FQN.match(fqn or "")
        if not match:
            raise read_failure(f"Sourcify record for {address} has compilation target {fqn!r}")
        path, name = match.group(1), match.group(2)
        abi = record["stdJsonOutput"]["contracts"][path][name]["abi"]
        sources = standard_input["sources"]
        contents = {p: s["content"] for p, s in sources.items()}
        if not all(isinstance(c, str) for c in contents.values()):
            raise TypeError
        version = compilation["compilerVersion"]
        full_match = record.get("match")
    except Refusal:
        raise
    except (KeyError, TypeError, AttributeError):
        raise read_failure(f"Sourcify record for {address} lacks a field this checker reads") from None
    if sum(len(c) for c in contents.values()) > MAX_SOURCE_BYTES:
        raise read_failure(f"Sourcify sources for {address} exceed the {MAX_SOURCE_BYTES}-byte cap")
    input_digest = sha256(canonical(standard_input))
    pinned = registry["pinned_inputs"].get(name)
    if pinned is not None and pinned != input_digest:
        raise Refusal("source-drift", f"Sourcify input for {name} at {address} has SHA-256 {input_digest}; "
                                      f"the registry pins {pinned}")
    return {
        "contract": name, "role": spec["role"], "address": address,
        "registry_name": spec["registry_name"], "instances": spec["instances"],
        "source_commit": spec["source_commit"], "fully_qualified_name": fqn,
        "compiler": version, "match": full_match,
        "standard_input": input_url(address), "standard_input_sha256": input_digest,
        "registry_build_input": pinned is not None,
        "abi": abi_url(address), "abi_sha256": sha256(canonical(abi)),
        "_sources": contents, "_abi": abi, "_input": standard_input,
    }


# --- analysis --------------------------------------------------------------


class Unit:
    """One set of sources, masked once, with its contract definitions."""

    def __init__(self, sources: dict[str, str]):
        self.sources = sources
        self.masked = {path: core.mask(text) for path, text in sources.items()}
        self.defs = _definitions(self.masked)
        self.spans = [(d["start"], d["end"], d["kind"], name, d["path"])
                      for name, items in self.defs.items() for d in items]

    def owner(self, path: str, offset: int) -> tuple | None:
        inside = [s for s in self.spans if s[4] == path and s[0] <= offset <= s[1]]
        return max(inside, key=lambda s: s[0]) if inside else None


def _definitions(masked: dict[str, str]) -> dict[str, list[dict]]:
    """Map each contract, interface and library name to its definitions."""
    found: dict[str, list[dict]] = {}
    for path in sorted(masked):
        clean = masked[path]
        for m in _DEFINITION.finditer(clean):
            end = core._close(clean, m.end() - 1, "{", "}")
            header = m.group(3).strip()
            bases = []
            if header.startswith("is") and (len(header) == 2 or not (header[2].isalnum() or header[2] == "_")):
                for item in core.split_args(header[2:]):
                    base = re.match(r"\s*([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)", item)
                    bases.append(base.group(1).split(".")[-1] if base else None)
            found.setdefault(m.group(2), []).append({
                "path": path, "kind": m.group(1), "start": m.start(),
                "end": len(clean) if end is None else end, "bases": bases,
            })
    return found


def inheritance_chain(unit: Unit, target: str) -> tuple[set[str], list[str]]:
    """(contract names in target's inheritance chain, unresolved base names).

    A build's input is a whole compilation unit, so every base must resolve
    to exactly one definition in it.
    """
    chain, pending, unresolved = set(), [target], []
    while pending:
        name = pending.pop()
        if name in chain:
            continue
        found = unit.defs.get(name, [])
        if len(found) != 1 or None in found[0]["bases"]:
            unresolved.append(str(name))
            continue
        chain.add(name)
        pending.extend(found[0]["bases"])
    return chain, sorted(set(unresolved))


def call_sites(unit: Unit, emitter: str, emitter_path: str) -> list[dict]:
    """Every call of emitter outside its own file, with the definition holding it."""
    call = re.compile(r"\b" + re.escape(emitter) + r"\s*\(")
    sites = []
    for path in sorted(unit.masked):
        if path == emitter_path:
            continue
        clean = unit.masked[path]
        for m in call.finditer(clean):
            owner = unit.owner(path, m.start())
            sites.append({"at": f"{path}:{core._line(clean, m.start())}",
                          "owner": owner[3] if owner else None, "kind": owner[2] if owner else None})
    return sites


class Reach:
    """Contract-level reach over each build's own sources."""

    def __init__(self, builds: list[dict]):
        self.builds = builds
        self.units = {b["contract"]: Unit(b["_sources"]) for b in builds}
        self.unattributed: dict[str, list[str]] = {}
        self.unresolved: dict[str, list[str]] = {}
        self.chains = {}
        for b in builds:
            name = b["contract"]
            self.chains[name], missing = inheritance_chain(self.units[name], name)
            if missing:
                self.unresolved[name] = missing

    def __call__(self, emitter: dict) -> list[str]:
        reached, loose = [], set()
        for b in self.builds:
            if emitter["path"] not in b["_sources"]:
                continue
            for site in call_sites(self.units[b["contract"]], emitter["emitter"], emitter["path"]):
                if site["kind"] == "contract" and site["owner"] in self.chains[b["contract"]]:
                    reached.append(b["contract"])
                elif site["kind"] != "contract":
                    loose.add(f"{site['at']} in {b['contract']}'s input")
        if loose:
            self.unattributed[emitter["emitter"]] = sorted(loose)
        return sorted(set(reached))


def binding(git_text: str, build_text: str | None) -> str:
    if build_text is None:
        return "absent"
    if build_text == git_text:
        return "equal"
    if "".join(core.mask(build_text).split()) == "".join(core.mask(git_text).split()):
        return "comments-only"
    return "differs"


_EMIT = re.compile(r"\bemit\s+((?:[A-Za-z_]\w*\.)*)([A-Za-z_]\w*)\s*\(")


def _scope(defs: dict[str, list[dict]], owner: str) -> tuple[set[str], list[str]]:
    """(names in owner's inheritance chain found under src/, names defined more than once)."""
    chain, pending, ambiguous = set(), [owner], []
    while pending:
        name = pending.pop()
        if name is None or name in chain:
            continue
        found = defs.get(name, [])
        if len(found) > 1:
            ambiguous.append(name)
            continue
        chain.add(name)
        if found:
            pending.extend(found[0]["bases"])
    return chain, sorted(set(ambiguous))


def resolve_emit_sites(unit: Unit, declarations: list[dict]) -> tuple[dict[str, list[str]], list[dict]]:
    """Attribute each Solidity `emit` under src/ to the declaration it names.

    An unqualified name resolves through the emitting contract's inheritance
    chain, a qualified one to the named contract or interface. A base defined
    outside src/ is outside the declaration scope and adds no candidate.
    Returns ({declaration key: sites}, unresolved sites).
    """
    by_key: dict[str, list[str]] = {}
    unresolved = []
    for path in sorted(unit.masked):
        clean = unit.masked[path]
        for m in _EMIT.finditer(clean):
            at, name = f"{path}:{core._line(clean, m.start())}", m.group(2)
            span = unit.owner(path, m.start())
            owner = span[3] if span else None
            qualifier = m.group(1).rstrip(".").split(".")[-1] if m.group(1) else None
            ambiguous = []
            if qualifier:
                owners = {qualifier}
            elif owner:
                owners, ambiguous = _scope(unit.defs, owner)
            else:
                owners = set()
            candidates = [d for d in declarations if d["name"] == name
                          and (d["qualified"].split(".")[0] in owners or d["qualified"].startswith("<file>."))]
            if len(candidates) > 1:
                close = core._close(clean, m.end() - 1, "(", ")")
                count = len(core.split_args(clean[m.end():close])) if close is not None else -1
                candidates = [d for d in candidates if len(d["inputs"]) == count]
            if len(candidates) != 1 or ambiguous:
                reason = (f"inheritance names {', '.join(ambiguous)} more than once" if ambiguous
                          else f"resolves to {len(candidates)} declarations under src/")
                unresolved.append({"kind": "emit-site", "name": name, "at": at, "reason": reason})
                continue
            d = candidates[0]
            by_key.setdefault(d["qualified"] + "@" + d["at"], []).append(at)
    return by_key, unresolved


def _shape(inputs: list[dict], anonymous: bool) -> tuple:
    return tuple((i["type"], i["indexed"]) for i in inputs), anonymous


def declaration_disagreements(declarations: list[dict], emitted: dict[str, list[str]],
                              assembly: dict[str, list[str]], builds: list[dict]) -> list[dict]:
    """Same-named declarations whose signature, indexed positions or anonymity differ.

    Each variant names the builds whose ABI carries an event of that name
    with exactly its types, indexed flags and anonymity.
    """
    views = {b["contract"]: core.abi_events({"abi": b["_abi"]}) for b in builds}
    groups: dict[str, list[dict]] = {}
    for d in declarations:
        groups.setdefault(d["name"], []).append(d)
    found = []
    for name in sorted(groups):
        variants = []
        for d in groups[name]:
            key = d["qualified"] + "@" + d["at"]
            shape = _shape(d["inputs"], d["anonymous"])
            variants.append({
                "declaration": d["qualified"], "declared_at": d["at"],
                "signature": core.signature(name, d["inputs"]),
                "indexed_positions": [n for n, i in enumerate(d["inputs"]) if i["indexed"]],
                "anonymous": d["anonymous"],
                "assembly_emitters": assembly.get(key, []),
                "solidity_emit_sites": emitted.get(key, []),
                "in_abi_of": sorted(c for c, events in views.items()
                                    if any(_shape(e["inputs"], e["anonymous"]) == shape for e in events.get(name, []))),
            })
        shapes = {(v["signature"], tuple(v["indexed_positions"]), v["anonymous"]) for v in variants}
        if len(shapes) > 1:
            found.append({"name": name, "variants": variants})
    return found


def stray_sites(unit: Unit) -> list[dict]:
    """Assembly log sites and emit_ functions outside the registry's emitter paths."""
    found = []
    for path in sorted(unit.masked):
        if path in EMITTER_FILES:
            continue
        clean = unit.masked[path]
        for m in _LOG_SITE.finditer(clean):
            found.append({"kind": "log-site", "name": m.group(0).rstrip("( "), "at": f"{path}:{core._line(clean, m.start())}",
                          "reason": "log site outside the registry's emitter paths"})
        for m in _EMITTER_DEF.finditer(clean):
            found.append({"kind": "emitter", "name": m.group(1), "at": f"{path}:{core._line(clean, m.start())}",
                          "reason": "emit_ function outside the registry's emitter paths"})
    return found


# --- table -----------------------------------------------------------------


def assemble(files: list[tuple[dict, bytes]], commit: str, registry: dict, builds: list[dict]) -> dict:
    total = sum(len(data) for _entry, data in files)
    if total > core.MAX_TOTAL_BYTES:
        raise read_failure(f"{total} bytes read, over the {core.MAX_TOTAL_BYTES}-byte total cap")
    sources = {e["path"]: core._decode(e["path"], data) for e, data in files}
    deployments = {b["contract"]: {"input": {"sources": {p: {"content": c} for p, c in b["_sources"].items()}},
                                   "output": {"abi": b["_abi"]}} for b in builds}
    reach = Reach(builds)
    body = core.scan(sources, deployments, EMITTER_FILES, reach=reach)
    for row in body["rows"]:
        loose = reach.unattributed.get(row["emitter"])
        if loose:
            row["notes"].append("call sites " + ", ".join(loose) + " are in a library or free function; "
                                "reach through them is not attributed")
    for emitter, loose in sorted(reach.unattributed.items()):
        body["unreviewed"].append({"kind": "reach", "name": emitter, "at": loose[0],
                                   "reason": "call site in a library or free function; reach not attributed"})
    for contract, missing in sorted(reach.unresolved.items()):
        body["unreviewed"].append({"kind": "reach", "name": contract, "at": f"build {contract}",
                                   "reason": "inheritance names " + ", ".join(missing) + " do not resolve to one definition"})
    resolver = core.TypeResolver(sources)
    declarations = []
    for path in sorted(sources):
        declarations += core.parse_declarations(path, sources[path], resolver)[0]
    unit = Unit(sources)
    emitted, unresolved = resolve_emit_sites(unit, declarations)
    assembly: dict[str, list[str]] = {}
    for row in body["rows"]:
        assembly.setdefault(row["declaration"] + "@" + row["declared_at"], []).append(row["emitter"])
    body["unreviewed"] += stray_sites(unit) + unresolved
    body["unreviewed"].sort(key=lambda u: (u["at"], u["kind"], u["name"]))
    for item in body["declarations_without_emitter"]:
        item["solidity_emit_sites"] = emitted.get(item["declaration"] + "@" + item["declared_at"], [])
    body["declaration_disagreements"] = declaration_disagreements(declarations, emitted, assembly, builds)
    entries = []
    for e, _data in sorted(files, key=lambda f: f[0]["path"]):
        entry = dict(e)
        entry["in_builds"] = {b["contract"]: binding(sources[e["path"]], b["_sources"].get(e["path"]))
                              for b in sorted(builds, key=lambda b: b["contract"])}
        entries.append(entry)
    summary = body["summary"]
    summary["unreviewed"] = len(body["unreviewed"])
    summary["binding_differs"] = sorted(e["path"] for e in entries if "differs" in e["in_builds"].values())
    summary["binding_comments_only"] = sorted(
        e["path"] for e in entries if "comments-only" in e["in_builds"].values())
    summary["non_emitting_declarations"] = sum(
        not item["solidity_emit_sites"] for item in body["declarations_without_emitter"])
    summary["unreached_rows"] = sum(not r["reached_by"] for r in body["rows"])
    summary["declaration_disagreements"] = len(body["declaration_disagreements"])
    body["schema"] = SCHEMA
    body["source"] = {
        "repository": REPOSITORY, "commit": commit, "build_origin": "sourcify", "chain_id": CHAIN_ID,
        "declaration_scope": "every .sol file under src/ at commit",
        "emitter_files": list(EMITTER_FILES),
        "registry": {k: registry[k] for k in ("path", "row", "commit", "compiler", "emitter_paths")},
        "deployments": [{k: v for k, v in b.items() if not k.startswith("_")} for b in builds],
        "files": entries,
    }
    return body


def read_sources(reader, ref: str) -> list[tuple[dict, bytes]]:
    listed = reader.list_sources(ref)
    files = []
    for path in sorted(listed):
        data = reader.read(ref, path)
        if core.git_blob_id(data) != listed[path]:
            raise read_failure(f"{path} at {ref}: bytes do not hash to listed blob {listed[path]}")
        files.append((core._entry(path, ref, "source", data), data))
    return files


def load_table(path: str) -> tuple[bytes, dict]:
    try:
        with open(path, "rb") as fh:
            raw = fh.read(core.MAX_TOTAL_BYTES + 1)
    except OSError as err:
        raise Refusal("table-invalid", f"{path} cannot be read: {type(err).__name__}") from None
    try:
        table = json.loads(raw.decode("utf-8"))
        source = table["source"]
        files = source["files"]
        ok = (table.get("schema") == SCHEMA and source.get("repository") == REPOSITORY
              and source.get("build_origin") == "sourcify" and isinstance(files, list)
              and all(isinstance(f, dict) and {"path", "ref", "role", "blob", "bytes", "sha256"} <= set(f)
                      for f in files)
              and isinstance(source["deployments"], list)
              and all({"address", "standard_input_sha256", "abi_sha256"} <= set(d) for d in source["deployments"]))
        core._safe_ref(source["commit"])
        for f in files:
            core._safe_path(f["path"])
            core._safe_ref(f["ref"])
        for d in source["deployments"]:
            _safe_address(d["address"])
    except (UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError, AttributeError, Refusal):
        ok = False
    if not ok:
        raise Refusal("table-invalid", f"{path} is not a V1 {SCHEMA} table")
    return raw, table


def read_table_sources(reader, table: dict, source_ref: str | None) -> tuple[list[tuple[dict, bytes]], list[str]]:
    drift, files = [], []
    table_sources = {f["path"] for f in table["source"]["files"]}
    read_ref = source_ref or table["source"]["commit"]
    listed = None
    if reader.list_sources is not None:
        listed = set(reader.list_sources(read_ref))
        drift += [f"{p} is present at {read_ref} and absent from the table" for p in sorted(listed - table_sources)]
        drift += [f"{p} is in the table and absent at {read_ref}" for p in sorted(table_sources - listed)]
    for f in table["source"]["files"]:
        if listed is not None and f["path"] not in listed:
            continue
        data = reader.read(read_ref, f["path"])
        seen = core._entry(f["path"], read_ref, "source", data)
        if (seen["bytes"], seen["sha256"], seen["blob"]) != (f["bytes"], f["sha256"], f["blob"]):
            drift.append(f"{f['path']} at {read_ref}: sha256 {f['sha256']} -> {seen['sha256']}, "
                         f"bytes {f['bytes']} -> {seen['bytes']}")
        files.append(({**seen, "ref": f["ref"]}, data))
    return files, drift


def build_drift(table: dict, builds: list[dict]) -> list[str]:
    drift = []
    committed = {d["address"]: d for d in table["source"]["deployments"]}
    for b in builds:
        d = committed.get(b["address"])
        if d is None:
            drift.append(f"build {b['contract']} at {b['address']} is absent from the table")
            continue
        for key in ("standard_input_sha256", "abi_sha256"):
            if d[key] != b[key]:
                drift.append(f"build {b['contract']} at {b['address']}: {key} {d[key]} -> {b[key]}")
    for address in sorted(set(committed) - {b["address"] for b in builds}):
        drift.append(f"build at {address} is in the table and no longer named by the registry")
    return drift


def render_markdown(table: dict) -> str:
    def cell(value) -> str:
        text = value if isinstance(value, str) else json.dumps(value, sort_keys=True)
        return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")

    source, summary = table["source"], table["summary"]
    lines = [
        "# Wildcat V1 emitter declarations", "",
        f"Schema `{table['schema']}`. Source `{source['repository']}` at commit `{source['commit']}`; "
        f"builds are Sourcify records on chain {source['chain_id']}, bound to the registry row "
        f"`{source['registry']['row']}` in `{source['registry']['path']}`.", "",
        "Mismatch classes: " + ", ".join(f"`{c}`" for c in core.MISMATCH_CLASSES)
        + "; a class found against a build's ABI is prefixed `abi:<contract>:`.", "",
        "## Regenerating this table", "",
        "```sh", f"python3 scripts/emitter_declarations_v1.py build --from-git <clone> "
        f"--out {TABLE_PATH} --markdown {MARKDOWN_PATH}", "```", "",
        "Verify without writing:", "",
        "```sh", f"python3 scripts/emitter_declarations_v1.py check --from-git <clone> "
        f"--table {TABLE_PATH} --markdown {MARKDOWN_PATH}", "```", "",
        f"Tie each build's ABI to the inputs the registry pins, with the registry's compiler "
        f"`{source['registry']['compiler']}`:", "",
        "```sh", "python3 scripts/emitter_declarations_v1.py crosscheck --solc <solc>", "```", "",
        "## Scope and limits", "", STATIC_NOTE, "", BUILD_NOTE, "", PIN_NOTE, "", REACH_NOTE, "",
        "## Builds", "",
        "| Contract | Role | Address | Instances | Source commit | Compiler | Registry input | Standard input SHA-256 | ABI SHA-256 |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for d in source["deployments"]:
        lines.append(f"| {d['contract']} | {d['role']} | `{d['address']}` | {d['instances']} | `{d['source_commit'][:8]}` "
                     f"| `{d['compiler']}` | {'pinned' if d['registry_build_input'] else 'not pinned'} "
                     f"| `{d['standard_input_sha256']}` | `{d['abi_sha256']}` |")
    lines += ["", "## Summary", "", "| Count | Value | Meaning |", "| --- | --- | --- |"]
    for key in sorted(summary):
        lines.append(f"| {cell(key)} | {cell(summary[key])} | {cell(SUMMARY_MEANINGS.get(key, 'see the JSON'))} |")
    lines += ["", "## Rows", "",
              "| Emitter | Declaration | Signature | topic0 | logN | Indexed | Data bytes | ABI checked | Reached by | Status | Classes | Notes |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for r in table["rows"]:
        lines.append("| " + " | ".join([
            f"`{r['emitter']}` ({cell(r['emitter_at'])})", f"`{r['declaration']}` ({cell(r['declared_at'])})",
            f"`{cell(r['signature'])}`", f"`{cell(r['topic0'])}`", cell(r["log_arity"]),
            cell(r["indexed_positions"]), cell(r["data_bytes"]), cell(", ".join(r["abi_checked"]) or "none"),
            cell(", ".join(r["reached_by"]) or "none"), cell(r["status"]),
            cell(", ".join(r["classes"]) or "none"), cell("; ".join(r["notes"]) or "none"),
        ]) + " |")
    for title, key, columns in (
        ("Mismatches", "mismatches", ("emitter", "declaration", "declared_at", "classes")),
        ("Unreviewed", "unreviewed", ("kind", "name", "at", "reason")),
    ):
        lines += ["", f"## {title}", ""]
        if not table[key]:
            lines.append("None.")
            continue
        lines.append("| " + " | ".join(columns) + " |")
        lines.append("| " + " | ".join("---" for _ in columns) + " |")
        for item in table[key]:
            lines.append("| " + " | ".join(cell(", ".join(item[c]) if isinstance(item[c], list) else item[c])
                                           for c in columns) + " |")
    lines += ["", "## Same-named declarations that disagree", "",
              "Each event below is declared more than once, with different signatures, indexed positions or "
              "anonymity. A decoder built from a variant that nothing emits computes a topic0 or layout "
              "that no deployed log carries. Every row above still compares its emitter with each "
              "same-named declaration separately.", ""]
    if not table["declaration_disagreements"]:
        lines.append("None.")
    else:
        lines += ["| Event | Declaration | Declared at | Signature | Indexed | Anonymous | Emitted by | In the ABI of |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for group in table["declaration_disagreements"]:
        for v in group["variants"]:
            emitted_by = ", ".join([f"`{e}`" for e in v["assembly_emitters"]] + v["solidity_emit_sites"])
            lines.append(f"| `{group['name']}` | {cell(v['declaration'])} | {cell(v['declared_at'])} "
                         f"| `{cell(v['signature'])}` | {cell(v['indexed_positions'])} | {cell(v['anonymous'])} "
                         f"| {cell(emitted_by or 'nothing')} | {cell(', '.join(v['in_abi_of']) or 'no build')} |")
    lines += ["", "## Declarations with no assembly emitter", "",
              "Each is either emitted by a Solidity `emit` statement, whose log the compiler derives from the "
              "declaration, or emitted nowhere under `src/`. An emit site is attributed through the emitting "
              "contract's inheritance chain, so a same-named declaration the contract does not inherit gets "
              "none of its sites.", ""]
    if not table["declarations_without_emitter"]:
        lines.append("None.")
    else:
        lines.append("| Declaration | Declared at | Signature | Solidity emit sites |")
        lines.append("| --- | --- | --- | --- |")
        for item in table["declarations_without_emitter"]:
            lines.append(f"| {cell(item['declaration'])} | {cell(item['declared_at'])} | {cell(item['signature'])} "
                         f"| {cell(', '.join(item['solidity_emit_sites']) or 'none: non-emitting')} |")
    unreached = [r for r in table["rows"] if not r["reached_by"]]
    lines += ["", "## Not reached by any deployed build", "",
              "A row here has an emitter that no listed build's compilation target calls through its own "
              "inheritance chain. It keeps its row and its comparison.", ""]
    if not unreached:
        lines.append("None.")
    else:
        lines.append("| Emitter | Declaration | Declared at | Status |")
        lines.append("| --- | --- | --- | --- |")
        for r in unreached:
            lines.append(f"| `{r['emitter']}` ({cell(r['emitter_at'])}) | `{r['declaration']}` "
                         f"| {cell(r['declared_at'])} | {cell(r['status'])} |")
    lines += ["", "## Source files", "", "| Path | Blob | Bytes | SHA-256 | Binding |",
              "| --- | --- | --- | --- | --- |"]
    for f in source["files"]:
        builds = ", ".join(f"{k}={v}" for k, v in sorted(f["in_builds"].items()))
        lines.append(f"| `{f['path']}` | `{f['blob']}` | {f['bytes']} | `{f['sha256']}` | {cell(builds)} |")
    lines.append("")
    return "\n".join(lines)


# --- compiler cross-check --------------------------------------------------


SOLC_TIMEOUT_SECONDS = 600


def _solc(solc: str, arguments: list[str], stdin: bytes | None = None) -> bytes:
    try:
        result = subprocess.run(  # phylax: allow subprocess: fixed argv list naming a user-supplied solc binary, no shell
            [solc, *arguments], input=stdin, capture_output=True, timeout=SOLC_TIMEOUT_SECONDS, check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as err:
        raise read_failure(f"solc did not complete: {type(err).__name__}") from None
    if result.returncode != 0:
        raise read_failure(f"solc exited {result.returncode}")
    return result.stdout


def crosscheck(sourcify, solc: str, root: str = ROOT) -> tuple[list[str], list[str]]:
    """Compile each registry-pinned input for ABI only and compare every build it covers.

    Returns (result lines, problem lines). A build no pinned input compiles
    is named as not cross-checked, never as agreeing.
    """
    registry = load_registry(root)
    builds = read_builds(sourcify, registry)
    version = _solc(solc, ["--version"]).decode("utf-8", "replace")
    if registry["compiler"] not in version:
        return [], [f"abi-crosscheck: solc reports {version.strip().splitlines()[-1]!r}, "
                    f"not the registry's {registry['compiler']}"]
    with open(solc, "rb") as fh:
        binary = sha256(fh.read())
    lines, problems = [f"abi-crosscheck: solc {registry['compiler']}, binary SHA-256 {binary}"], []
    covered, failed = set(), set()
    for pinned in (b for b in builds if b["registry_build_input"]):
        request = json.loads(json.dumps(pinned["_input"]))
        request.setdefault("settings", {})["outputSelection"] = {"*": {"*": ["abi"]}}
        output = json.loads(_solc(solc, ["--standard-json"], canonical(request)).decode("utf-8"))
        errors = [e for e in output.get("errors", []) if e.get("severity") == "error"]
        if errors:
            problems.append(f"abi-crosscheck: the {pinned['contract']} input does not compile: {len(errors)} errors")
            continue
        for b in builds:
            path, name = b["fully_qualified_name"].split(":")
            entry = output.get("contracts", {}).get(path, {}).get(name)
            if entry is None:
                continue
            digest = sha256(canonical(entry["abi"]))
            label = f"{b['contract']} ABI from the {pinned['contract']} input ({pinned['standard_input_sha256'][:12]})"
            if digest == b["abi_sha256"]:
                lines.append(f"abi-crosscheck: {label} equals its build's, {digest}")
                covered.add(b["contract"])
            else:
                problems.append(f"abi-crosscheck: {label} is {digest}; its build carries {b['abi_sha256']}")
                failed.add(b["contract"])
    for b in builds:
        if b["contract"] not in covered | failed:
            lines.append(f"abi-crosscheck: {b['contract']} is compiled by no registry-pinned input; not cross-checked")
    return lines, problems


# --- commands --------------------------------------------------------------


def run_build(reader, sourcify, out: str, markdown: str | None, ref: str | None, root: str = ROOT) -> dict:
    registry = load_registry(root)
    if reader.list_sources is None:
        raise Refusal("read-failure", "a V1 build reads src/ from a clone; use --from-git")
    commit = ref or registry["commit"]
    files = read_sources(reader, commit)
    builds = read_builds(sourcify, registry)
    table = assemble(files, commit, registry, builds)
    core.atomic_write(out, core.serialize(table))
    if markdown:
        core.atomic_write(markdown, render_markdown(table).encode("utf-8"))
    return table


def run_check(reader, sourcify, table_path: str, markdown: str | None, source_ref: str | None,
              root: str = ROOT) -> list[str]:
    raw, committed = load_table(table_path)
    registry = load_registry(root)
    files, drift = read_table_sources(reader, committed, source_ref)
    builds = read_builds(sourcify, registry)
    drift += build_drift(committed, builds)
    if drift:
        return [f"source-drift: {line}" for line in drift] + [
            f"source-drift: {len(drift)} source differences from {table_path}; the table was not regenerated"]
    table = assemble(files, committed["source"]["commit"], registry, builds)
    regenerated = core.serialize(table)
    problems = []
    if regenerated != raw:
        problems.append(f"table-difference: {table_path} differs from the table regenerated from matching source")
        problems += [f"table-difference: {line}" for line in core._diff_lines(raw, regenerated, table_path)]
    if markdown:
        try:
            with open(markdown, "rb") as fh:
                committed_md = fh.read(core.MAX_TOTAL_BYTES + 1)
        except OSError as err:
            return problems + [f"markdown-difference: {markdown} cannot be read: {type(err).__name__}"]
        rendered = render_markdown(table).encode("utf-8")
        if rendered != committed_md:
            problems.append(f"markdown-difference: {markdown} differs from its rendering of the table")
            problems += [f"markdown-difference: {line}" for line in core._diff_lines(committed_md, rendered, markdown)]
    return problems


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    subparsers = parser.add_subparsers(dest="command", required=True)
    build = subparsers.add_parser("build", help="regenerate the V1 emitter table")
    check = subparsers.add_parser("check", help="compare a regenerated table with the committed one")
    for sub in (build, check):
        origin = sub.add_mutually_exclusive_group(required=True)
        origin.add_argument("--from-git", metavar="CLONE", help="read src/ from a local wildcat-protocol clone")
        origin.add_argument("--from-https", action="store_true", help=f"read src/ from {core.ALLOWED_HOST}")
        sub.add_argument("--markdown", metavar="PATH", help="the rendered Markdown table")
        sub.add_argument("--sourcify-dir", metavar="DIR", help="read saved Sourcify responses from DIR")
        sub.add_argument("--ref", type=core._commit, help="read src/ at this commit")
    build.add_argument("--out", required=True, metavar="PATH", help="where to write the JSON table")
    check.add_argument("--table", required=True, metavar="PATH", help="the committed JSON table")
    cross = subparsers.add_parser("crosscheck", help="compile the registry-pinned inputs and compare build ABIs")
    cross.add_argument("--solc", required=True, metavar="PATH", help="the registry's solc version")
    cross.add_argument("--sourcify-dir", metavar="DIR", help="read saved Sourcify responses from DIR")
    return parser


def main(argv: list[str] | None = None, reader=None, sourcify=None, root: str = ROOT) -> int:
    args = build_parser().parse_args(argv)
    if reader is None and args.command != "crosscheck":
        reader = HttpsReader() if args.from_https else core.GitReader(args.from_git)
    if sourcify is None:
        sourcify = DirectorySourcifyReader(args.sourcify_dir) if args.sourcify_dir else SourcifyReader()
    try:
        if args.command == "crosscheck":
            lines, problems = crosscheck(sourcify, args.solc, root)
            for line in lines + problems:
                print(line, file=sys.stderr)
            return 1 if problems else 0
        if args.command == "build":
            table = run_build(reader, sourcify, args.out, args.markdown, args.ref, root)
            s = table["summary"]
            print(f"build: {s['emitters']} emitters, {s['rows']} rows, {s['mismatch_rows']} mismatch rows, "
                  f"{s['unreviewed']} unreviewed; wrote {args.out}", file=sys.stderr)
            return 0
        problems = run_check(reader, sourcify, args.table, args.markdown, args.ref, root)
    except Refusal as refusal:
        print(str(refusal), file=sys.stderr)
        return 1
    for line in problems:
        print(line, file=sys.stderr)
    if problems:
        return 1
    print(f"check: {args.table} regenerates exactly", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
