#!/usr/bin/env python3
"""Check a target's assembly event emitters against their declarations.

    python3 scripts/emitter_declarations.py build --from-git CLONE --out TABLE.json [--markdown TABLE.md]
    python3 scripts/emitter_declarations.py check --from-git CLONE --table TABLE.json [--ref COMMIT]
    python3 scripts/emitter_declarations.py check --from-https --table TABLE.json

`build` reads `wildcat-finance/v2-protocol` at `--ref` (default the pin) and
the compiler output at `--abi-ref` (default tag v2.0.0), scans every
`emit_<Name>` function in the two emitter files, pairs each with every
same-named `event` declared in any `.sol` file under `src/`, and compares it
with the declaration text and with the compiler ABI of the WildcatMarket and
HooksFactory builds. Its source block names every file it read: each `.sol`
file under `src/` at the ref, and the standard input and output of both
builds at the compiler-output ref. A found mismatch is written as a row with
its classes; it never fails `build`. Over HTTPS, `build` reads exactly the
paths of an existing `--table` at that table's refs, because a raw host cannot
list a tree, and refuses any byte that differs from it.

`check` takes the refs and paths from the committed table's source block.
`--ref` changes only the commit the `src/` bytes are read at; the table stays
the oracle. Before scanning, every read file must match the table's size, git
blob id and SHA-256, and with `--from-git` the `.sol` file list under `src/`
must match the table's. `check` writes nothing.

Exit status: 0 when the table is written (`build`) or matches (`check`); 1 on
any refusal; 2 on a usage error. Each refusal line on stderr starts with one
prefix: `source-drift:` when read bytes or the file list differ from the
table, `table-difference:` or `markdown-difference:` when the source matches
but the regenerated bytes differ, `read-failure:` when a file cannot be read
or exceeds its cap, and `table-invalid:` when the committed table is not a
readable v1 table.

The scan is static text analysis. It runs no target code and makes no claim
about runtime behaviour, bytecode identity or capture completeness.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request


# Keccak-256 permutation copied from
# plugins/tabularium/scripts/tabularium_lib/keccak.py, whose padding carried
# the S1-R1-01 defect until #1860 fixed it the same way. A root script does
# not import a plugin's private library, so the logic is carried here and
# pinned by tests/test_emitter_declarations.py.
_ROTATION = (
    0, 1, 62, 28, 27,
    36, 44, 6, 55, 20,
    3, 10, 43, 25, 39,
    41, 45, 15, 21, 8,
    18, 2, 61, 56, 14,
)
_ROUND = (
    0x0000000000000001, 0x0000000000008082,
    0x800000000000808A, 0x8000000080008000,
    0x000000000000808B, 0x0000000080000001,
    0x8000000080008081, 0x8000000000008009,
    0x000000000000008A, 0x0000000000000088,
    0x0000000080008009, 0x000000008000000A,
    0x000000008000808B, 0x800000000000008B,
    0x8000000000008089, 0x8000000000008003,
    0x8000000000008002, 0x8000000000000080,
    0x000000000000800A, 0x800000008000000A,
    0x8000000080008081, 0x8000000000008080,
    0x0000000080000001, 0x8000000080008008,
)
_MASK = (1 << 64) - 1
_RATE = 136


def _rotate(value: int, amount: int) -> int:
    if amount == 0:
        return value
    return ((value << amount) | (value >> (64 - amount))) & _MASK


def _permutation(state: list[int]) -> None:
    for constant in _ROUND:
        columns = [
            state[x] ^ state[x + 5] ^ state[x + 10] ^ state[x + 15] ^ state[x + 20]
            for x in range(5)
        ]
        deltas = [columns[(x - 1) % 5] ^ _rotate(columns[(x + 1) % 5], 1) for x in range(5)]
        for y in range(5):
            for x in range(5):
                state[x + 5 * y] ^= deltas[x]
        moved = [0] * 25
        for y in range(5):
            for x in range(5):
                moved[y % 5 + 5 * ((2 * x + 3 * y) % 5)] = _rotate(
                    state[x + 5 * y], _ROTATION[x + 5 * y]
                )
        for y in range(5):
            row = moved[5 * y:5 * y + 5]
            for x in range(5):
                state[x + 5 * y] = row[x] ^ ((~row[(x + 1) % 5]) & row[(x + 2) % 5])
        state[0] ^= constant


def _sponge(data: bytes, suffix: int) -> bytes:
    """Absorb data under a domain suffix and squeeze 32 bytes.

    pad10*1 appends the suffix and a final 0x80 bit. When one byte of the
    block remains they share it, so that byte is ``suffix | 0x80``.
    """
    padded = bytearray(data)
    remaining = _RATE - len(padded) % _RATE
    if remaining == 1:
        padded.append(suffix | 0x80)
    else:
        padded.append(suffix)
        padded.extend(b"\x00" * (remaining - 2))
        padded.append(0x80)
    state = [0] * 25
    for offset in range(0, len(padded), _RATE):
        block = padded[offset:offset + _RATE]
        for lane in range(_RATE // 8):
            state[lane] ^= int.from_bytes(block[lane * 8:lane * 8 + 8], "little")
        _permutation(state)
    output = b"".join(lane.to_bytes(8, "little") for lane in state[:_RATE // 8])
    return output[:32]


def keccak256(data: bytes) -> bytes:
    """Return legacy Keccak-256, with Ethereum's 0x01 domain suffix."""
    if not isinstance(data, bytes):
        raise TypeError("Keccak input must be bytes")
    return _sponge(data, 0x01)


SCHEMA = "wildcat.emitter-declarations.v1"
REPOSITORY = "wildcat-finance/v2-protocol"
PIN = "f5a26146987926f4811b72a795d662813dedfe85"
COMPILER_OUTPUT_REF = "a70f297fbd1b1ab597e0e9a3458a2d13a34b4657"
# Human label for COMPILER_OUTPUT_REF's own commit; shown in the rendered
# table only when a build's compiler_output_ref still equals this SHA, so a
# future --abi-ref away from the tag never carries a stale label.
COMPILER_OUTPUT_TAG = "v2.0.0"
RUNTIME_DIFFERENTIAL_NOTE = (
    "This is a static text comparison of source declarations, assembly "
    "emitters and compiler ABI output. It runs no target code and makes no "
    "claim about runtime behaviour, deployed bytecode identity or capture "
    "completeness. The Fizz differential harness landed in "
    "[PR #1601](https://github.com/wildcat-finance/skills/pull/1601) is "
    "supplemental runtime evidence for the emitters it covers, never proof "
    "for this table."
)
SPHEREXCONFIG_CORRECTION_NOTE = (
    "The deployed market and factory take their SphereX event declarations "
    "from `SphereXProtectedRegisteredBase.sol`, not from `SphereXConfig.sol`. "
    "`SphereXConfig.sol` enters only the MarketLens build and the V2 tree's "
    "`WildcatArchController.sol`, which is not the deployed arch controller."
)
SOURCE_PREFIX = "src/"
EMITTER_FILES = ("src/libraries/MarketEvents.sol", "src/spherex/SphereXProtectedEvents.sol")
DEPLOYMENTS = (
    ("WildcatMarket", "0xac3216fa28f81b8fae150fb5626ca79c7a570daf"),
    ("HooksFactory", "0xdd7dd3b5076cf89440d05585ff56d246386207be"),
)
ALLOWED_HOST = "raw.githubusercontent.com"
MAX_FILE_BYTES = 1024 * 1024
MAX_TOTAL_BYTES = 8 * 1024 * 1024
GIT_TIMEOUT_SECONDS = 60
HTTPS_TIMEOUT_SECONDS = 30
MISMATCH_CLASSES = (
    "topic0", "log-arity", "indexed-order", "data-length", "data-order",
    "parameter-count", "anonymous-declared",
)

_COMMIT = re.compile(r"^[0-9a-f]{40}$")
_PATH = re.compile(r"^[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)*$")
_IDENT = re.compile(r"^[A-Za-z_]\w*$")
_NUMBER = re.compile(r"^(?:0x[0-9a-fA-F]+|[0-9]+)$")
_TOPIC_LITERAL = re.compile(r"^0x[0-9a-fA-F]{64}$")
_TYPE = re.compile(r"^([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)((?:\[[0-9]*\])*)$")
_SIZED = re.compile(r"^(u?int|bytes)([0-9]+)$")
_LOCATIONS = frozenset(("memory", "calldata", "storage"))
_WORDS = re.compile(r"[\w\s]*")
_OTHER_MEMORY_WRITES = re.compile(r"\b(mstore8|mcopy|calldatacopy|codecopy|extcodecopy|returndatacopy)\s*\(")


class Refusal(Exception):
    """A read or comparison that ends the command with exit 1."""

    def __init__(self, prefix: str, message: str):
        super().__init__(f"{prefix}: {message}")
        self.prefix = prefix


def read_failure(message: str) -> Refusal:
    return Refusal("read-failure", message)


def git_blob_id(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\x00" % len(data) + data).hexdigest()


def _safe_path(path: object) -> str:
    if not isinstance(path, str) or not _PATH.match(path) or ".." in path.split("/"):
        raise read_failure(f"unsafe path {path!r}")
    return path


def _safe_ref(ref: object) -> str:
    if not isinstance(ref, str) or not _COMMIT.match(ref):
        raise read_failure(f"ref {ref!r} is not a 40-hex commit")
    return ref


def deployment_paths(contract: str, address: str) -> tuple[str, str]:
    base = f"deployments/mainnet/{contract}-{address}"
    return f"{base}/standard-input.json", f"{base}/output.json"


# --- readers ---------------------------------------------------------------


class GitReader:
    """Read blobs from a local clone with a fixed git argv and no shell."""

    def __init__(self, clone: str):
        self.clone = os.path.abspath(clone)

    def _git(self, arguments: list[str]) -> bytes:
        argv = ["git", "-C", self.clone, "--no-pager", *arguments]
        env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
        env.update(GIT_NO_REPLACE_OBJECTS="1", GIT_TERMINAL_PROMPT="0", GIT_OPTIONAL_LOCKS="0")
        try:
            result = subprocess.run(  # phylax: allow subprocess: fixed git argv list, validated ref and path, no shell
                argv, capture_output=True, timeout=GIT_TIMEOUT_SECONDS, check=False, env=env,
            )
        except (OSError, subprocess.TimeoutExpired) as err:
            raise read_failure(f"git {arguments[0]} did not complete: {type(err).__name__}") from None
        if result.returncode != 0:
            raise read_failure(f"git {' '.join(arguments[-1:])} exited {result.returncode}")
        return result.stdout

    def read(self, ref: str, path: str) -> bytes:
        ref, path = _safe_ref(ref), _safe_path(path)
        data = self._git(["show", "--no-textconv", "--end-of-options", f"{ref}:{path}"])
        if len(data) > MAX_FILE_BYTES:
            raise read_failure(f"{path} at {ref} is {len(data)} bytes, over the {MAX_FILE_BYTES}-byte cap")
        return data

    def list_sources(self, ref: str) -> dict[str, str]:
        """Return {path: blob id} for every `.sol` file under src/ at ref."""
        ref = _safe_ref(ref)
        listing = self._git(["ls-tree", "-r", "-z", "--full-tree", "--end-of-options", ref, SOURCE_PREFIX.rstrip("/")])
        found = {}
        for record in listing.decode("utf-8", "strict").split("\x00"):
            if not record:
                continue
            meta, _, path = record.partition("\t")
            fields = meta.split()
            if len(fields) == 3 and fields[1] == "blob" and path.endswith(".sol"):
                found[_safe_path(path)] = fields[2]
        return found


class _HostPinnedRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        target = urllib.parse.urlsplit(newurl)
        if target.scheme != "https" or target.hostname != ALLOWED_HOST:
            raise read_failure(f"redirect to {target.scheme}://{target.hostname} refused")
        return super().redirect_request(req, fp, code, msg, headers, newurl)


class HttpsReader:
    """Read blobs from raw.githubusercontent.com at a pinned commit."""

    list_sources = None

    def __init__(self, opener=None):
        self.opener = opener or urllib.request.build_opener(_HostPinnedRedirect)

    @staticmethod
    def url(ref: str, path: str) -> str:
        ref, path = _safe_ref(ref), _safe_path(path)
        return f"https://{ALLOWED_HOST}/{REPOSITORY}/{ref}/{urllib.parse.quote(path)}"

    def read(self, ref: str, path: str) -> bytes:
        url = self.url(ref, path)
        if urllib.parse.urlsplit(url).hostname != ALLOWED_HOST:
            raise read_failure(f"host for {path} is not {ALLOWED_HOST}")
        try:
            with self.opener.open(url, timeout=HTTPS_TIMEOUT_SECONDS) as response:  # phylax: allow url: fixed host, pinned commit, digest-verified
                final = urllib.parse.urlsplit(response.geturl())
                if final.scheme != "https" or final.hostname != ALLOWED_HOST:
                    raise read_failure(f"{path} was served from {final.hostname}")
                data = response.read(MAX_FILE_BYTES + 1)
        except Refusal:
            raise
        except (OSError, ValueError) as err:
            raise read_failure(f"{path} at {ref} could not be fetched: {type(err).__name__}") from None
        if len(data) > MAX_FILE_BYTES:
            raise read_failure(f"{path} at {ref} exceeds the {MAX_FILE_BYTES}-byte cap")
        return data


# --- Solidity text ---------------------------------------------------------


def mask(text: str) -> str:
    """Blank comments and string contents, keeping every offset and newline."""
    out = list(text)
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                out[i] = " "
                i += 1
        elif ch == "/" and i + 1 < n and text[i + 1] == "*":
            end = text.find("*/", i + 2)
            end = n if end < 0 else end + 2
            for k in range(i, end):
                if text[k] != "\n":
                    out[k] = " "
            i = end
        elif ch in "\"'":
            i += 1
            while i < n and text[i] != ch and text[i] != "\n":
                out[i] = " "
                if text[i] == "\\" and i + 1 < n:
                    out[i + 1] = " " if text[i + 1] != "\n" else "\n"
                    i += 1
                i += 1
            i += 1
        else:
            i += 1
    return "".join(out)


def _close(text: str, start: int, opening: str, closing: str) -> int | None:
    """Index of the bracket that closes text[start], or None when unbalanced."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == opening:
            depth += 1
        elif text[i] == closing:
            depth -= 1
            if depth == 0:
                return i
    return None


def split_args(text: str) -> list[str]:
    parts, depth, current = [], 0, []
    for ch in text:
        if ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
            continue
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        current.append(ch)
    tail = "".join(current).strip()
    if tail or parts:
        parts.append(tail)
    return parts


def _line(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def parse_param(text: str, event: bool) -> dict | None:
    """Split one parameter into its type text, indexed flag and name."""
    text = re.sub(r"\s*\[\s*", "[", text)
    text = re.sub(r"\s*\]", "]", text)
    words = text.split()
    if not words or not _TYPE.match(words[0]):
        return None
    kind, rest = words[0], words[1:]
    if kind == "address" and rest[:1] == ["payable"]:
        rest = rest[1:]
    indexed = False
    if event and rest[:1] == ["indexed"]:
        indexed, rest = True, rest[1:]
    if not event and rest[:1] and rest[0] in _LOCATIONS:
        rest = rest[1:]
    if len(rest) > 1 or (rest and not _IDENT.match(rest[0])):
        return None
    return {"type_text": kind, "indexed": indexed, "name": rest[0] if rest else ""}


def _spans(clean: str) -> list[tuple[int, int, str, str]]:
    """(start, end, kind, name) for each contract, interface and library body."""
    spans = []
    for m in re.finditer(r"\b(contract|interface|library)\s+([A-Za-z_]\w*)[^{;]*\{", clean):
        end = _close(clean, m.end() - 1, "{", "}")
        spans.append((m.start(), len(clean) if end is None else end, m.group(1), m.group(2)))
    return spans


def _owner(spans, offset: int) -> str | None:
    inside = [s for s in spans if s[0] <= offset <= s[1]]
    return max(inside, key=lambda s: s[0])[3] if inside else None


class TypeResolver:
    """Map Solidity parameter types to canonical ABI types.

    A contract or interface is `address`, an enum is `uint8`, a user-defined
    value type is its underlying type, a struct is the tuple of its members,
    and array suffixes are kept. A name with no definition, or with
    definitions that disagree, resolves to None and its row is unreviewed.
    """

    def __init__(self, sources: dict[str, str]):
        self.defs: dict[str, list[tuple[str | None, str, object]]] = {}
        for path in sorted(sources):
            clean = mask(sources[path])
            spans = _spans(clean)
            for start, _end, kind, name in spans:
                self._add(name, _owner([s for s in spans if s[0] < start], start), kind, None)
            for m in re.finditer(r"\benum\s+([A-Za-z_]\w*)\s*\{", clean):
                self._add(m.group(1), _owner(spans, m.start()), "enum", None)
            for m in re.finditer(r"\btype\s+([A-Za-z_]\w*)\s+is\s+([A-Za-z_]\w*)\s*;", clean):
                self._add(m.group(1), _owner(spans, m.start()), "udvt", m.group(2))
            for m in re.finditer(r"\bstruct\s+([A-Za-z_]\w*)\s*\{", clean):
                end = _close(clean, m.end() - 1, "{", "}")
                members = None
                if end is not None:
                    members = []
                    for item in clean[m.end():end].split(";"):
                        if item.strip():
                            parsed = parse_param(item, event=False)
                            members.append(parsed["type_text"] if parsed else None)
                self._add(m.group(1), _owner(spans, m.start()), "struct", members)

    def _add(self, name, owner, kind, detail):
        self.defs.setdefault(name, []).append((owner, kind, detail))

    def resolve(self, type_text: str, _stack: frozenset = frozenset()) -> str | None:
        match = _TYPE.match(type_text or "")
        if not match:
            return None
        base, suffix = match.group(1), match.group(2)
        canonical = self._base(base, _stack)
        return None if canonical is None else canonical + suffix

    def _base(self, base: str, stack: frozenset) -> str | None:
        if base in ("uint", "int"):
            return base + "256"
        if base in ("address", "bool", "string", "bytes"):
            return base
        sized = _SIZED.match(base)
        if sized:
            width = int(sized.group(2))
            if sized.group(1) == "bytes":
                return base if 1 <= width <= 32 else None
            return base if 8 <= width <= 256 and width % 8 == 0 else None
        if base in stack:
            return None
        *qualifier, name = base.split(".")
        found = set()
        for owner, kind, detail in self.defs.get(name, []):
            if qualifier and owner != qualifier[-1]:
                continue
            if kind in ("contract", "interface"):
                found.add("address")
            elif kind == "enum":
                found.add("uint8")
            elif kind == "udvt":
                found.add(self.resolve(detail, stack | {base}))
            elif kind == "struct":
                parts = [self.resolve(t, stack | {base}) if t else None for t in (detail or [None])]
                found.add(None if None in parts or detail is None else "(" + ",".join(parts) + ")")
            else:
                found.add(None)
        return found.pop() if len(found) == 1 else None


def one_word(canonical: str | None) -> bool:
    """True for a static value type that occupies exactly one ABI word."""
    if canonical is None or "[" in canonical or "(" in canonical:
        return False
    return canonical not in ("string", "bytes")


def sub_word(canonical: str | None) -> bool:
    if canonical in ("address", "bool"):
        return True
    sized = _SIZED.match(canonical or "")
    if not sized:
        return False
    width = int(sized.group(2))
    return width < 32 if sized.group(1) == "bytes" else width < 256


def _literal(token: str, constants: dict[str, int]) -> int | None:
    token = token.strip()
    if token in constants:
        return constants[token]
    return int(token, 0) if _NUMBER.match(token) else None


def parse_emitters(path: str, text: str) -> tuple[list[dict], list[dict]]:
    """Return (emitters, stray log sites) for one emitter file."""
    clean = mask(text)
    constants = {}
    for m in re.finditer(r"\buint[0-9]*\s+constant\s+([A-Za-z_]\w*)\s*=\s*(0x[0-9a-fA-F]+|[0-9]+)\s*;", clean):
        constants[m.group(1)] = int(m.group(2), 0)
    emitters, bodies = [], []
    for m in re.finditer(r"\bfunction\s+(emit_[A-Za-z_]\w*)\s*\(", clean):
        row = {"emitter": m.group(1), "path": path, "line": _line(clean, m.start())}
        emitters.append(row)
        reason = _parse_emitter(clean, m.end() - 1, constants, row, bodies)
        if reason:
            row["unreviewed"] = reason
    stray = []
    for m in re.finditer(r"\blog[0-4]\s*\(", clean):
        if not any(start <= m.start() < end for start, end in bodies):
            stray.append({"kind": "log-site", "name": m.group(0).rstrip("( "), "at": f"{path}:{_line(clean, m.start())}",
                          "reason": "log site outside any emit_ function body"})
    return emitters, stray


def _parse_emitter(clean, open_paren, constants, row, bodies) -> str | None:
    close = _close(clean, open_paren, "(", ")")
    if close is None:
        return "unbalanced parameter list"
    brace, semicolon = clean.find("{", close + 1), clean.find(";", close + 1)
    if brace < 0 or 0 <= semicolon < brace or not _WORDS.fullmatch(clean, close + 1, brace):
        return "no function body"
    body_start = brace + 1
    body_end = _close(clean, body_start - 1, "{", "}")
    if body_end is None:
        return "unbalanced function body"
    bodies.append((body_start, body_end))
    params = []
    for item in split_args(clean[open_paren + 1:close]):
        parsed = parse_param(item, event=False)
        if parsed is None or not parsed["name"]:
            return f"parameter {item.strip()!r} does not parse"
        params.append(parsed)
    row["params"] = [{"name": p["name"], "type": p["type_text"]} for p in params]
    body = clean[body_start:body_end]
    logs = list(re.finditer(r"\blog([0-4])\s*\(", body))
    row["log_sites"] = len(logs)
    if len(logs) != 1:
        return f"{len(logs)} log sites in the body"
    other = _OTHER_MEMORY_WRITES.search(body)
    if other:
        return f"body writes memory with {other.group(1)}"
    log = logs[0]
    arity = int(log.group(1))
    end = _close(body, log.end() - 1, "(", ")")
    if end is None:
        return "unbalanced log arguments"
    args = split_args(body[log.end():end])
    if len(args) != 2 + arity:
        return f"log{arity} has {len(args)} arguments"
    row["arity"] = arity
    row["log_line"] = _line(clean, body_start + log.start())
    size = _literal(args[1], constants)
    if size is None:
        return f"data size {args[1]!r} is not a literal"
    row["data_bytes"] = size
    row["topic0_literal"] = None
    if arity:
        topic = args[2]
        if _TOPIC_LITERAL.match(topic):
            row["topic0_literal"] = topic.lower()
        elif topic in constants:
            row["topic0_literal"] = "0x%064x" % constants[topic]
        else:
            return f"topic0 {topic!r} is not a literal"
    for topic in args[3:]:
        if not _IDENT.match(topic):
            return f"topic {topic!r} is an expression"
    row["topic_args"] = args[3:]
    base = args[0]
    base_literal = _literal(base, constants)
    words = {}
    for store in re.finditer(r"\bmstore\s*\(", body[:log.start()]):
        close_store = _close(body, store.end() - 1, "(", ")")
        pair = split_args(body[store.end():close_store]) if close_store is not None else []
        if len(pair) != 2:
            return "mstore does not parse"
        target, value = pair
        offset = None
        added = split_args(target[4:-1]) if target.startswith("add(") and target.endswith(")") else []
        if target == base:
            offset = 0
        elif len(added) == 2 and base in added:
            offset = _literal(added[1] if added[0] == base else added[0], constants)
        elif base_literal is not None and _literal(target, constants) is not None:
            offset = _literal(target, constants) - base_literal
        if offset is None:
            return f"mstore target {target!r} is not relative to the data base"
        if offset < 0 or offset >= size:
            continue
        if offset % 32:
            return f"mstore at data offset {offset} is not word-aligned"
        if not _IDENT.match(value):
            return f"data word at offset {offset} is an expression"
        words[offset] = value
    row["data_args"] = [words.get(32 * w) for w in range(size // 32)]
    return None


def parse_declarations(path: str, text: str, resolver: TypeResolver) -> tuple[list[dict], list[dict]]:
    clean = mask(text)
    spans = _spans(clean)
    decls, failed = [], []
    for m in re.finditer(r"\bevent\s+([A-Za-z_]\w*)\s*\(", clean):
        name, at = m.group(1), f"{path}:{_line(clean, m.start())}"
        owner = _owner(spans, m.start())
        qualified = f"{owner or '<file>'}.{name}"
        close = _close(clean, m.end() - 1, "(", ")")
        tail = re.compile(r"\s*(anonymous\s*)?;").match(clean, close + 1) if close is not None else None
        if tail is None:
            failed.append({"kind": "declaration", "name": qualified, "at": at, "reason": "declaration does not parse"})
            continue
        inputs, unresolved = [], []
        for item in split_args(clean[m.end():close]):
            parsed = parse_param(item, event=True)
            if parsed is None:
                unresolved.append(item.strip())
                inputs.append({"type": None, "type_text": item.strip(), "indexed": False, "name": ""})
                continue
            canonical = resolver.resolve(parsed["type_text"])
            if canonical is None:
                unresolved.append(parsed["type_text"])
            inputs.append({"type": canonical, "type_text": parsed["type_text"],
                           "indexed": parsed["indexed"], "name": parsed["name"]})
        decls.append({"name": name, "qualified": qualified, "at": at, "path": path,
                      "inputs": inputs, "anonymous": bool(tail.group(1)), "unresolved": unresolved})
    return decls, failed


def signature(name: str, inputs: list[dict]) -> str | None:
    if any(i["type"] is None for i in inputs):
        return None
    return f"{name}({','.join(i['type'] for i in inputs)})"


def topic0_of(sig: str | None) -> str | None:
    return None if sig is None else "0x" + keccak256(sig.encode("utf-8")).hex()


def compare(emitter: dict, inputs: list[dict], anonymous: bool, name: str) -> list[str]:
    """Mismatch classes between one emitter and one declaration view.

    Expected values come from the declaration's types, indexed flags and
    anonymity; the emitter's literal is only ever the value under test.

    A genuinely anonymous `logN` call reserves no topic0 slot: every topic
    word is an indexed value. The scan still reads `args[2]` provisionally
    as `topic0_literal` (S2-R1-01, since anonymity is not known until a
    declaration is paired here), so under this anonymous view that word is
    folded back into the indexed sequence rather than dropped from it.
    """
    classes = []
    indexed = [n for n, i in enumerate(inputs) if i["indexed"]]
    data = [n for n, i in enumerate(inputs) if not i["indexed"]]
    if anonymous:
        classes.append("anonymous-declared")
    if emitter["arity"] != len(indexed) + (0 if anonymous else 1):
        classes.append("log-arity")
    if not anonymous and emitter["topic0_literal"] != topic0_of(signature(name, inputs)):
        classes.append("topic0")
    names = [p["name"] for p in emitter["params"]]
    if len(names) != len(inputs):
        classes.append("parameter-count")
        return classes
    topic_values = emitter["topic_args"]
    if anonymous and emitter["topic0_literal"] is not None:
        topic_values = [emitter["topic0_literal"]] + emitter["topic_args"]
    if len(topic_values) == len(indexed) and topic_values != [names[n] for n in indexed]:
        classes.append("indexed-order")
    if emitter["data_bytes"] != 32 * len(data):
        classes.append("data-length")
    elif emitter["data_args"] != [names[n] for n in data]:
        classes.append("data-order")
    return classes


def _abi_type(entry: dict) -> str | None:
    kind = entry.get("type")
    if not isinstance(kind, str):
        return None
    if kind.startswith("tuple"):
        parts = [_abi_type(c) for c in entry.get("components") or []]
        if None in parts:
            return None
        return "(" + ",".join(parts) + ")" + kind[len("tuple"):]
    return kind


def abi_events(output: dict) -> dict[str, list[dict]]:
    events: dict[str, list[dict]] = {}
    for entry in output.get("abi") or []:
        if isinstance(entry, dict) and entry.get("type") == "event":
            inputs = [{"type": _abi_type(i), "indexed": bool(i.get("indexed")), "name": i.get("name", "")}
                      for i in entry.get("inputs") or []]
            events.setdefault(entry.get("name"), []).append(
                {"inputs": inputs, "anonymous": bool(entry.get("anonymous"))})
    return events


# --- table -----------------------------------------------------------------


def scan(sources: dict[str, str], deployments: dict[str, dict], emitter_files=EMITTER_FILES) -> dict:
    """Build the table body from decoded sources and parsed build files.

    deployments maps a contract name to {"input": standard JSON input,
    "output": compiler output}.
    """
    resolver = TypeResolver(sources)
    unreviewed, emitters = [], []
    for path in emitter_files:
        found, stray = parse_emitters(path, sources.get(path, ""))
        emitters += found
        unreviewed += stray
    declarations = []
    for path in sorted(sources):
        found, failed = parse_declarations(path, sources[path], resolver)
        declarations += found
        unreviewed += failed
    views = {c: abi_events(d["output"]) for c, d in sorted(deployments.items())}
    callers = {}
    for contract, d in sorted(deployments.items()):
        carried = d["input"].get("sources", {})
        callers[contract] = (set(carried), {p: mask(s.get("content", "")) for p, s in carried.items()
                                            if isinstance(s, dict) and isinstance(s.get("content"), str)})
    for e in emitters:
        for p in e.get("params", []):
            p["canonical"] = resolver.resolve(p["type"])
    rows, emitted = [], set()
    for e in emitters:
        name = e["emitter"][len("emit_"):]
        at = f"{e['path']}:{e['line']}"
        if "unreviewed" in e:
            unreviewed.append({"kind": "emitter", "name": e["emitter"], "at": at, "reason": e["unreviewed"]})
            continue
        matches = [d for d in declarations if d["name"] == name]
        if not matches:
            unreviewed.append({"kind": "emitter", "name": e["emitter"], "at": at,
                               "reason": "no same-named event declaration under src/"})
            continue
        call = re.compile(r"\b" + re.escape(e["emitter"]) + r"\s*\(")
        reached = sorted(c for c, (paths, masked) in callers.items() if e["path"] in paths and any(
            call.search(text) for p, text in masked.items() if p != e["path"]))
        for d in matches:
            emitted.add(d["qualified"] + "@" + d["at"])
            rows.append(_row(e, d, name, at, views, reached, unreviewed))
    without = []
    for d in declarations:
        if d["qualified"] + "@" + d["at"] not in emitted:
            without.append({"declaration": d["qualified"], "declared_at": d["at"],
                            "signature": signature(d["name"], d["inputs"])})
    mismatches = [{"emitter": r["emitter"], "declaration": r["declaration"], "declared_at": r["declared_at"],
                   "classes": r["classes"]} for r in rows if r["classes"]]
    return {
        "rows": rows,
        "mismatches": mismatches,
        "unreviewed": sorted(unreviewed, key=lambda u: (u["at"], u["kind"], u["name"])),
        "declarations_without_emitter": sorted(without, key=lambda w: (w["declared_at"], w["declaration"])),
        "summary": {
            "emitters": len(emitters),
            "rows": len(rows),
            "compared_rows": sum(r["status"] != "unreviewed" for r in rows),
            "abi_checked_rows": sum(bool(r["abi_checked"]) for r in rows),
            "mismatch_rows": len(mismatches),
            "unreviewed": len(unreviewed),
            "declarations_without_emitter": len(without),
        },
    }


def _row(e, d, name, at, views, reached, unreviewed) -> dict:
    sig = signature(name, d["inputs"])
    row = {
        "emitter": e["emitter"], "emitter_at": at, "log_at": f"{e['path']}:{e['log_line']}",
        "declaration": d["qualified"], "declared_at": d["at"],
        "signature": sig, "topic0": topic0_of(sig), "topic0_literal": e["topic0_literal"],
        "anonymous": d["anonymous"], "log_arity": e["arity"],
        "indexed_positions": [n for n, i in enumerate(d["inputs"]) if i["indexed"]],
        "topic_args": e["topic_args"], "data_bytes": e["data_bytes"], "data_args": e["data_args"],
        "abi_checked": [], "reached_by": reached, "classes": [], "notes": [],
    }
    if not reached:
        row["notes"].append("called from no bound deployed build")
    if d["unresolved"]:
        row["status"] = "unreviewed"
        reason = "parameter type " + ", ".join(f"`{t}`" for t in d["unresolved"]) + " has no resolved canonical ABI type"
        row["notes"].append(reason)
        unreviewed.append({"kind": "row", "name": f"{e['emitter']} / {d['qualified']}", "at": d["at"], "reason": reason})
        return row
    if not all(one_word(i["type"]) for i in d["inputs"]):
        row["status"] = "unreviewed"
        reason = "a parameter is not a one-word static type; layout not compared"
        row["notes"].append(reason)
        unreviewed.append({"kind": "row", "name": f"{e['emitter']} / {d['qualified']}", "at": d["at"], "reason": reason})
        return row
    classes = compare(e, d["inputs"], d["anonymous"], name)
    for contract, events in views.items():
        candidates = events.get(name, [])
        if len(candidates) > 1:
            row["notes"].append(f"{contract} ABI has {len(candidates)} events named {name}; not compared")
        elif candidates:
            view = candidates[0]
            if any(i["type"] is None for i in view["inputs"]):
                row["notes"].append(f"{contract} ABI entry for {name} has an unreadable type; not compared")
                continue
            row["abi_checked"].append(contract)
            classes += [f"abi:{contract}:{c}" for c in compare(e, view["inputs"], view["anonymous"], name)]
    row["classes"] = sorted(set(classes))
    row["status"] = "mismatch" if row["classes"] else "compared"
    if len(e["params"]) == len(d["inputs"]):
        pairs = list(zip(e["params"], d["inputs"]))
        for p, i in pairs:
            if p["canonical"] != i["type"]:
                row["notes"].append(f"emitter parameter `{p['name']}` is `{p['type']}` where the declaration says "
                                    f"`{i['type']}`; recorded, not graded")
        narrow = [f"`{p['name']}` (`{p['type']}`)" for p, i in pairs
                  if not i["indexed"] and sub_word(p["canonical"])]
        if narrow:
            row["notes"].append("sub-word values " + ", ".join(narrow) + " are written by mstore as full words; "
                                "their cleaning is not graded")
    return row


def _entry(path: str, ref: str, role: str, data: bytes) -> dict:
    return {"path": path, "ref": ref, "role": role, "blob": git_blob_id(data),
            "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}


def _decode(path: str, data: bytes) -> str:
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        raise read_failure(f"{path} is not UTF-8") from None


def _json(path: str, data: bytes) -> dict:
    try:
        value = json.loads(_decode(path, data))
    except json.JSONDecodeError:
        raise read_failure(f"{path} is not JSON") from None
    if not isinstance(value, dict):
        raise read_failure(f"{path} is not a JSON object")
    return value


def assemble(files: list[tuple[dict, bytes]], commit: str, compiler_ref: str) -> dict:
    """Build the whole table from (source-block entry, bytes) pairs."""
    total = sum(len(data) for _entry_, data in files)
    if total > MAX_TOTAL_BYTES:
        raise read_failure(f"{total} bytes read, over the {MAX_TOTAL_BYTES}-byte total cap")
    sources = {e["path"]: _decode(e["path"], data) for e, data in files if e["role"] == "source"}
    by_path = {e["path"]: data for e, data in files}
    deployments, block = {}, []
    for contract, address in DEPLOYMENTS:
        input_path, output_path = deployment_paths(contract, address)
        if input_path not in by_path or output_path not in by_path:
            raise read_failure(f"{contract} build files were not read")
        deployments[contract] = {"input": _json(input_path, by_path[input_path]),
                                 "output": _json(output_path, by_path[output_path])}
        block.append({"contract": contract, "address": address,
                      "standard_input": input_path,
                      "standard_input_sha256": hashlib.sha256(by_path[input_path]).hexdigest(),
                      "output": output_path,
                      "output_sha256": hashlib.sha256(by_path[output_path]).hexdigest()})
    entries = []
    for e, data in sorted(files, key=lambda f: f[0]["path"]):
        entry = dict(e)
        if entry["role"] == "source":
            text = sources[entry["path"]]
            binding = {}
            for contract, d in sorted(deployments.items()):
                carried = d["input"].get("sources", {}).get(entry["path"])
                binding[contract] = "absent" if carried is None else (
                    "equal" if isinstance(carried, dict) and carried.get("content") == text else "differs")
            entry["in_builds"] = binding
        entries.append(entry)
    body = scan(sources, deployments)
    body["summary"]["binding_differs"] = sorted(
        e["path"] for e in entries if "differs" in e.get("in_builds", {}).values())
    body["schema"] = SCHEMA
    body["source"] = {
        "repository": REPOSITORY, "commit": commit, "compiler_output_ref": compiler_ref,
        "declaration_scope": "every .sol file under src/ at commit",
        "emitter_files": list(EMITTER_FILES), "deployments": block, "files": entries,
    }
    return body


def serialize(table: dict) -> bytes:
    return (json.dumps(table, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("utf-8")


def read_build(reader, ref: str, compiler_ref: str) -> list[tuple[dict, bytes]]:
    """Read every file a git build needs, checking each blob against the tree."""
    listed = reader.list_sources(ref)
    files = []
    for path in sorted(listed):
        data = reader.read(ref, path)
        if git_blob_id(data) != listed[path]:
            raise read_failure(f"{path} at {ref}: bytes do not hash to listed blob {listed[path]}")
        files.append((_entry(path, ref, "source", data), data))
    for contract, address in DEPLOYMENTS:
        for role, path in zip(("standard-input", "compiler-output"), deployment_paths(contract, address)):
            data = reader.read(compiler_ref, path)
            files.append((_entry(path, compiler_ref, role, data), data))
    return files


def load_table(path: str) -> tuple[bytes, dict]:
    try:
        with open(path, "rb") as fh:
            raw = fh.read(MAX_TOTAL_BYTES + 1)
    except OSError as err:
        raise Refusal("table-invalid", f"{path} cannot be read: {type(err).__name__}") from None
    try:
        table = json.loads(raw.decode("utf-8"))
        source = table["source"]
        files = source["files"]
        ok = (table.get("schema") == SCHEMA and isinstance(files, list) and all(
            isinstance(f, dict) and {"path", "ref", "role", "blob", "bytes", "sha256"} <= set(f) for f in files))
        _safe_ref(source["commit"])
        _safe_ref(source["compiler_output_ref"])
        for f in files:
            _safe_path(f["path"])
            _safe_ref(f["ref"])
    except (UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError, Refusal):
        ok = False
    if not ok:
        raise Refusal("table-invalid", f"{path} is not a {SCHEMA} table")
    return raw, table


def read_table_sources(reader, table: dict, source_ref: str | None) -> tuple[list[tuple[dict, bytes]], list[str]]:
    """Read the table's files, with src/ at source_ref; return (files, drift lines)."""
    drift, files = [], []
    table_sources = {f["path"] for f in table["source"]["files"] if f["role"] == "source"}
    read_ref = source_ref or table["source"]["commit"]
    listed = None
    if reader.list_sources is not None:
        listed = set(reader.list_sources(read_ref))
        for path in sorted(listed - table_sources):
            drift.append(f"{path} is present at {read_ref} and absent from the table")
        for path in sorted(table_sources - listed):
            drift.append(f"{path} is in the table and absent at {read_ref}")
    for f in table["source"]["files"]:
        ref = read_ref if f["role"] == "source" else f["ref"]
        if f["role"] == "source" and listed is not None and f["path"] not in listed:
            continue
        data = reader.read(ref, f["path"])
        seen = _entry(f["path"], ref, f["role"], data)
        if (seen["bytes"], seen["sha256"], seen["blob"]) != (f["bytes"], f["sha256"], f["blob"]):
            drift.append(f"{f['path']} at {ref}: sha256 {f['sha256']} -> {seen['sha256']}, "
                         f"bytes {f['bytes']} -> {seen['bytes']}")
        files.append(({**seen, "ref": f["ref"]}, data))
    return files, drift


def render_markdown(table: dict) -> str:
    """Render the reader's table from the JSON table, deterministically."""
    def cell(value) -> str:
        text = value if isinstance(value, str) else json.dumps(value, sort_keys=True)
        return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")

    source, summary = table["source"], table["summary"]
    compiler_label = (f"`{source['compiler_output_ref']}` (tag `{COMPILER_OUTPUT_TAG}`)"
                      if source["compiler_output_ref"] == COMPILER_OUTPUT_REF
                      else f"`{source['compiler_output_ref']}`")
    lines = [
        "# Emitter declarations", "",
        f"Schema `{table['schema']}`. Source `{source['repository']}` at commit "
        f"`{source['commit']}`; compiler output at {compiler_label}.", "",
        "Mismatch classes: " + ", ".join(f"`{c}`" for c in MISMATCH_CLASSES)
        + "; a class found against a build's ABI is prefixed `abi:<contract>:`.", "",
        "## Regenerating this table", "",
        "```sh", "python3 scripts/emitter_declarations.py build --from-git <clone> "
        "--out docs/kickoff/1361/emitters.json --markdown docs/kickoff/1361/emitters.md",
        "```", "",
        "Verify without writing:", "",
        "```sh", "python3 scripts/emitter_declarations.py check --from-git <clone> "
        "--table docs/kickoff/1361/emitters.json", "```", "",
        "## Scope and limits", "",
        RUNTIME_DIFFERENTIAL_NOTE, "",
        SPHEREXCONFIG_CORRECTION_NOTE, "",
        "## Builds", "",
        "| Contract | Address | Standard input SHA-256 | Output SHA-256 |",
        "| --- | --- | --- | --- |",
    ]
    for d in source["deployments"]:
        lines.append(f"| {d['contract']} | `{d['address']}` | `{d['standard_input_sha256']}` | `{d['output_sha256']}` |")
    lines += ["", "## Summary", "", "| Count | Value |", "| --- | --- |"]
    for key in sorted(summary):
        lines.append(f"| {cell(key)} | {cell(summary[key])} |")
    lines += ["", "## Rows", "",
              "| Emitter | Declaration | Signature | topic0 | logN | Indexed | Data bytes | ABI checked | Reached by | Status | Classes | Notes |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for r in table["rows"]:
        lines.append("| " + " | ".join([
            f"`{r['emitter']}` ({cell(r['emitter_at'])})", f"`{r['declaration']}` ({cell(r['declared_at'])})",
            f"`{cell(r['signature'])}`", f"`{cell(r['topic0'])}`", cell(r["log_arity"]),
            cell(r["indexed_positions"]), cell(r["data_bytes"]), cell(", ".join(r["abi_checked"]) or "none"),
            cell(", ".join(r["reached_by"]) or "none"), cell(r["status"]),
            cell(", ".join(r["classes"]) or "none"), cell("; ".join(r["notes"]) or "none"),
        ]) + " |")
    for title, key, columns in (
        ("Mismatches", "mismatches", ("emitter", "declaration", "declared_at", "classes")),
        ("Unreviewed", "unreviewed", ("kind", "name", "at", "reason")),
        ("Declarations with no assembly emitter", "declarations_without_emitter",
         ("declaration", "declared_at", "signature")),
    ):
        lines += ["", f"## {title}", ""]
        if not table[key]:
            lines.append("None.")
            continue
        lines.append("| " + " | ".join(columns) + " |")
        lines.append("| " + " | ".join("---" for _ in columns) + " |")
        for item in table[key]:
            lines.append("| " + " | ".join(cell(", ".join(item[c]) if isinstance(item[c], list) else item[c])
                                           for c in columns) + " |")
    unreached = [r for r in table["rows"] if not r["reached_by"] and r["status"] == "compared"]
    lines += ["", "## Not reached by any deployed build", "",
              "A row here compared cleanly against its declaration but its emitter is never called "
              "from a source file bound into a listed build; the source-level dead-code and unused-slot "
              "cases named in the study belong here.", ""]
    if not unreached:
        lines.append("None.")
    else:
        lines.append("| Emitter | Declaration | Declared at |")
        lines.append("| --- | --- | --- |")
        for r in unreached:
            lines.append(f"| `{r['emitter']}` ({cell(r['emitter_at'])}) | `{r['declaration']}` | {cell(r['declared_at'])} |")
    lines += ["", "## Source files", "", "| Path | Ref | Blob | Bytes | SHA-256 | In builds |",
              "| --- | --- | --- | --- | --- | --- |"]
    for f in source["files"]:
        builds = ", ".join(f"{k}={v}" for k, v in sorted(f.get("in_builds", {}).items())) or f["role"]
        lines.append(f"| `{f['path']}` | `{f['ref']}` | `{f['blob']}` | {f['bytes']} | `{f['sha256']}` | {cell(builds)} |")
    lines.append("")
    return "\n".join(lines)


def atomic_write(path: str, data: bytes) -> None:
    """Write data to path through a sibling temporary file and os.replace."""
    directory = os.path.dirname(os.path.abspath(path))
    handle, temporary = tempfile.mkstemp(prefix=".emitter-declarations-", dir=directory)
    try:
        with os.fdopen(handle, "wb") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def _diff_lines(expected: bytes, actual: bytes, label: str) -> list[str]:
    diff = difflib.unified_diff(expected.decode("utf-8", "replace").splitlines(),
                                actual.decode("utf-8", "replace").splitlines(),
                                f"{label} (committed)", f"{label} (regenerated)", n=0, lineterm="")
    return [line for _i, line in zip(range(12), diff)]


def run_build(reader, out: str, markdown: str | None, ref: str, compiler_ref: str, table_path: str | None) -> dict:
    if reader.list_sources is None:
        if table_path is None:
            raise Refusal("read-failure", "an HTTPS build needs --table for its path list and digests")
        _raw, committed = load_table(table_path)
        if (ref, compiler_ref) != (committed["source"]["commit"], committed["source"]["compiler_output_ref"]):
            raise Refusal("source-drift", "an HTTPS build reads only the table's refs")
        files, drift = read_table_sources(reader, committed, None)
        if drift:
            raise Refusal("source-drift", "; ".join(drift))
    else:
        files = read_build(reader, ref, compiler_ref)
    table = assemble(files, ref, compiler_ref)
    atomic_write(out, serialize(table))
    if markdown:
        atomic_write(markdown, render_markdown(table).encode("utf-8"))
    return table


def run_check(reader, table_path: str, markdown: str | None, source_ref: str | None) -> list[str]:
    """Return refusal lines; empty when the committed table regenerates exactly."""
    raw, committed = load_table(table_path)
    files, drift = read_table_sources(reader, committed, source_ref)
    if drift:
        return [f"source-drift: {line}" for line in drift] + [
            f"source-drift: {len(drift)} source differences from {table_path}; the table was not regenerated"]
    table = assemble(files, committed["source"]["commit"], committed["source"]["compiler_output_ref"])
    regenerated = serialize(table)
    problems = []
    if regenerated != raw:
        problems.append(f"table-difference: {table_path} differs from the table regenerated from matching source")
        problems += [f"table-difference: {line}" for line in _diff_lines(raw, regenerated, table_path)]
    if markdown:
        try:
            with open(markdown, "rb") as fh:
                committed_md = fh.read(MAX_TOTAL_BYTES + 1)
        except OSError as err:
            return problems + [f"markdown-difference: {markdown} cannot be read: {type(err).__name__}"]
        rendered = render_markdown(table).encode("utf-8")
        if rendered != committed_md:
            problems.append(f"markdown-difference: {markdown} differs from its rendering of the table")
            problems += [f"markdown-difference: {line}" for line in _diff_lines(committed_md, rendered, markdown)]
    return problems


def _commit(value: str) -> str:
    if not _COMMIT.match(value):
        raise argparse.ArgumentTypeError(f"{value!r} is not a 40-hex commit")
    return value


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    subparsers = parser.add_subparsers(dest="command", required=True)
    build = subparsers.add_parser("build", help="regenerate the emitter table")
    check = subparsers.add_parser("check", help="compare a regenerated table with the committed one")
    for sub in (build, check):
        origin = sub.add_mutually_exclusive_group(required=True)
        origin.add_argument("--from-git", metavar="CLONE", help="read from a local v2-protocol clone")
        origin.add_argument("--from-https", action="store_true", help=f"read from {ALLOWED_HOST}")
        sub.add_argument("--markdown", metavar="PATH", help="the rendered Markdown table")
    build.add_argument("--out", required=True, metavar="PATH", help="where to write the JSON table")
    build.add_argument("--ref", type=_commit, default=PIN, help="source commit (default the pin)")
    build.add_argument("--abi-ref", type=_commit, default=COMPILER_OUTPUT_REF, help="compiler-output commit")
    build.add_argument("--table", metavar="PATH", help="existing table naming the paths an HTTPS build reads")
    check.add_argument("--table", required=True, metavar="PATH", help="the committed JSON table")
    check.add_argument("--ref", type=_commit, help="read src/ at this commit instead of the table's")
    return parser


def main(argv: list[str] | None = None, reader=None) -> int:
    args = build_parser().parse_args(argv)
    if reader is None:
        reader = HttpsReader() if args.from_https else GitReader(args.from_git)
    try:
        if args.command == "build":
            table = run_build(reader, args.out, args.markdown, args.ref, args.abi_ref, args.table)
            s = table["summary"]
            print(f"build: {s['emitters']} emitters, {s['rows']} rows, {s['mismatch_rows']} mismatch rows, "
                  f"{s['unreviewed']} unreviewed; wrote {args.out}", file=sys.stderr)
            return 0
        problems = run_check(reader, args.table, args.markdown, args.ref)
    except Refusal as refusal:
        print(str(refusal), file=sys.stderr)
        return 1
    for line in problems:
        print(line, file=sys.stderr)
    if problems:
        return 1
    print(f"check: {args.table} regenerates exactly", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
