#!/usr/bin/env python3
"""Prove what a bound-source edit costs, without consulting a model.

Three instruction documents are bound into `tests/fixtures/agent-instruction-v1`
by whole-file SHA-256.  Editing one starts the reconciliation sequence
skills#1030 records.  This tool runs that sequence against a throwaway copy of
the tree and reports what the repository's own checker says afterwards, so the
cost of an edit is observed rather than argued about.

    offline      an out-of-span edit, every mechanical pass applied: does
                 `agent_instruction.py check` go green with no model consulted?
    span-shift   the edit placements whose reconciliation outcome is proved,
                 because only an edit before a reviewed span start moves the
                 recorded binding offsets.
    selftest     the tool's own machinery: fixture-copy isolation, a no-op
                 reconciliation that reproduces the committed bytes, and the
                 path confinement that keeps every write inside the copy.

Each subcommand writes one closed `protasis-design-report/v1` object, the same
seven-key shape `.hexaemeron/scripts/design_probe.py` writes, either to
`--report` or to stdout.

The mechanical passes, applied in this order and named so a missing one is
identifiable from the refusal it produces:

    manifest-source      manifest `fixtures[i].source.sha256`
    model                `<fixture>/model.json` `sources[0].sha256`
    source-spans         `<fixture>/source-spans.json` `source.sha256`
    compact              `<fixture>/compact.wai`, regenerated by the checker's
                         own `format`, because it embeds the digest as `h64:`
    manifest-artifacts   manifest `artifacts.{compact,model,source_spans}.sha256`

A live reconciliation owes a sixth pass this tool does not exercise: the
matching digests in the `agent_instruction` row of
`tests/promise_machine_coverage.json`.  `agent_instruction.py check` never
reads that file, so a fixture copy cannot observe it; `tests/test_agent_instruction.py`
is what holds it current.  `coverage_bound_artifacts` reports which paths that
row binds so the pass is not forgotten.

Boundaries this tool holds to, per the study's `reconcile-tool-writes` entry:

- Every write inside the copy goes through the checker's own
  `write_confined_atomic`, and every read through its `read_confined`, rather
  than through a reimplementation.  Both refuse an absolute path, a `..`
  component, a backslash, a control character and a symlinked component.
- The bound sources in the live repository are never written.  The edit is
  applied to the copy, and `selftest` proves the live tree's digests are
  unchanged across a run.
- `--report` is the one write this tool makes outside the copy, so it refuses a
  target the manifest binds by digest.  The bound set is derived from the
  manifest rather than listed here, and `tests/test_agent_instruction_corpus.py`
  exercises the refusal against a throwaway copy.
- The checker runs as a subprocess with an argument list, no shell, a
  constructed environment rather than the ambient one, the copy as its working
  directory, a wall-clock timeout and a cap on the output parsed.
- The checker's bytes are digest-checked against the repository copy before it
  is executed, so the subprocess runs bytes this tool verified.
- Nothing here opens a socket, starts a model, or reads a credential.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


SCHEMA = "protasis-design-report/v1"

FIXTURE_ROOT = "tests/fixtures/agent-instruction-v1"
MANIFEST = f"{FIXTURE_ROOT}/manifest.json"
MEASUREMENT = f"{FIXTURE_ROOT}/evidence/measurement.json"
PARITY = f"{FIXTURE_ROOT}/evidence/parity.json"
CHECKER = "scripts/agent_instruction.py"
COVERAGE = "tests/promise_machine_coverage.json"

# The fixture whose bound source these proofs edit. The other two are left
# alone deliberately: an edit to one bound document must not invalidate the
# recorded counts of the other two either.
SUBJECT = "fiat-study-runbook-phase"

# The mechanical passes, in application order.
MECHANICAL_PASSES = (
    "manifest-source",
    "model",
    "source-spans",
    "compact",
    "manifest-artifacts",
)

# The pass a live reconciliation owes that a fixture copy cannot observe,
# because `agent_instruction.py check` does not read the coverage register.
UNOBSERVED_PASS = "coverage-register"

# An out-of-span edit appended at end of file. After the reviewed span, so the
# recorded binding offsets do not move: the edit shape that should stop costing
# a measurement.
AFTER_SPAN_EDIT = b"\n<!-- prove: skills#1098 out-of-span edit -->\n"

# An out-of-span edit before the reviewed span start moves every recorded
# offset. Named here so `span-shift` can report it as uncovered rather than
# silently omit it; the runbook schedules it at step 4.
BEFORE_SPAN_PLACEMENT = "before-span"
AFTER_SPAN_PLACEMENT = "after-span"

CHECK_TIMEOUT_SECONDS = 600
MAX_OUTPUT_BYTES = 1 << 20

# The run's design record, read to close `--candidate`.
DESIGN_EVIDENCE = ".hexaemeron/design-evidence.json"
MAX_DESIGN_EVIDENCE_BYTES = 1 << 20

# The closed candidate set, used only when the run's design record is not
# readable, because this tool is runnable outside a Fiat run.
# `.hexaemeron/scripts/design_probe.py` closes the same flag over the same ids.
FALLBACK_CANDIDATES = (
    "deterministic-tokenizer",
    "digest-neutral-corpus",
    "evidence-outside-corpus",
    "published-profile",
)


class ProverError(RuntimeError):
    """The tool cannot complete a check, so it reports nothing rather than a guess."""


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def report_bytes(record: dict[str, Any]) -> bytes:
    """The exact canonical shape design_probe.py writes its reports in."""
    return (
        json.dumps(
            record,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode("utf-8")


def candidate_choices(root: Path) -> tuple[str, ...]:
    """The candidate ids the run's design record declares.

    Read from the record rather than listed here, so the flag tracks the design
    this run actually selected from. `--candidate` is closed over the result, so
    a typo is a usage error rather than a `protasis-design-report/v1` object
    naming a candidate no design record contains.

    Falls back to the closed set above when the record is absent, oversized or
    malformed, because the flag must stay closed even where the record is not
    there to close it.
    """
    path = Path(root) / DESIGN_EVIDENCE
    try:
        if path.stat().st_size > MAX_DESIGN_EVIDENCE_BYTES:
            return FALLBACK_CANDIDATES
        record = json.loads(path.read_bytes())
        ids = tuple(str(entry["id"]) for entry in record["candidates"])
    except (OSError, ValueError, KeyError, TypeError):
        return FALLBACK_CANDIDATES
    return ids or FALLBACK_CANDIDATES


def bound_digests(manifest: dict[str, Any]) -> tuple[tuple[str, str], ...]:
    """Every path the manifest binds by digest, with the digest it binds.

    One enumeration serves both the constructor's self-consistency check and
    the `--report` guard, so the two cannot drift apart: a path the manifest
    starts binding is checked and protected in the same commit that adds it.
    """
    entries: list[tuple[str, str]] = []
    for entry in manifest["fixtures"]:
        entries.append((entry["source"]["path"], entry["source"]["sha256"]))
        for name in sorted(entry["artifacts"]):
            artifact = entry["artifacts"][name]
            entries.append((artifact["path"], artifact["sha256"]))
    return tuple(sorted(set(entries)))


def bound_targets(root: Path, manifest: dict[str, Any]) -> frozenset[Path]:
    """Every path the manifest binds by digest, resolved absolute.

    Derived from the manifest rather than listed here, so the guard tracks what
    the manifest binds instead of drifting from it. Both sides are resolved, so
    a symlinked route to a bound path is the same path.
    """
    relative = {MANIFEST} | {path for path, _ in bound_digests(manifest)}
    return frozenset((Path(root) / path).resolve() for path in sorted(relative))


def write_report(checker, root: Path, target: str, data: bytes, bound: frozenset[Path]) -> None:
    """Write one report through the checker's confined atomic writer.

    A relative `--report` is confined to `--root`, which is how the design
    record's own resolver commands name it: `.hexaemeron/reports/<criterion>.json`.
    An absolute one is confined to the directory the operator named, so a
    caller can write outside the repository without the writer losing its
    `O_NOFOLLOW` parent walk, its refusal of a non-regular leaf, or its
    atomic replace. Either way the leaf goes through `_safe_relative_path`,
    so `..`, a backslash, a control character and an empty name refuse.

    The path is operator argv, not data read from outside the process, so the
    writer's own controls are about symlinks and half-written files rather than
    about which directory an operator may choose. One choice is not the
    operator's to make: this is the only write the tool performs outside its
    throwaway copy, and the study's "Never" list rules out editing a bound
    document. A target the manifest binds is therefore refused before anything
    is opened, so `--report PROMISE_MACHINE.md --root .` cannot replace a bound
    document with a JSON report.
    """
    path = Path(target)
    absolute = path if path.is_absolute() else Path(root) / path
    if absolute.resolve() in bound:
        raise ProverError(
            f"{target} is a path the manifest binds by digest; "
            "writing a report over it would destroy bound bytes"
        )
    if path.is_absolute():
        checker.write_confined_atomic(path.parent, path.name, data)
    else:
        checker.write_confined_atomic(root, target, data)


def load_checker(root: Path):
    """The repository's own checker, as a module.

    Loaded rather than reimplemented so the corpus digest this tool reasons
    about is the digest the checker computes, and so its path confinement is
    the audited code rather than a copy of it.
    """
    script = root / CHECKER
    spec = importlib.util.spec_from_file_location("agent_instruction", script)
    if spec is None or spec.loader is None:
        raise ProverError(f"cannot load the checker at {script}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class Reconciliation:
    """One bound-source edit, reconciled inside a throwaway copy of the tree.

    Construction reads the live tree and verifies it agrees with itself before
    anything is copied, so a proof never runs against a tree that was already
    inconsistent. "Agrees with itself" means every path `bound_digests` reports:
    each fixture's source and each of its artefacts, not only the subject
    fixture's rewritten ones. Nothing here writes to the live tree.
    """

    def __init__(self, root: Path, checker=None) -> None:
        self.root = Path(root).resolve()
        self.checker = checker if checker is not None else load_checker(self.root)
        self.checker_bytes = self._live_bytes(CHECKER)

        self.manifest = self._live_record(MANIFEST)
        self.fixture = self._subject_fixture(self.manifest)
        self.source_path = self.fixture["source"]["path"]
        self.start = int(self.fixture["source"]["start"])
        self.end = int(self.fixture["source"]["end"])
        self.source = self._live_bytes(self.source_path)
        self.old_digest = self.fixture["source"]["sha256"]

        if digest(self.source) != self.old_digest:
            raise ProverError(
                f"{self.source_path} is already off its manifest digest; "
                "reconcile the live tree before proving anything about it"
            )
        if len(self.source) < self.end:
            raise ProverError(f"{self.source_path} is shorter than its reviewed span")
        self.span = self.source[self.start : self.end]
        if digest(self.span) != self.fixture["source"]["span_sha256"]:
            raise ProverError(f"{self.source_path} has a reviewed span off its manifest digest")

        # Every bound path, not just the subject fixture's rewritten artefacts.
        # A proof that started against a tree already off one of these would
        # report a refusal caused by pre-existing drift as though the edit
        # caused it, which is the confusion this check exists to prevent.
        for relative, expected in bound_digests(self.manifest):
            if digest(self._live_bytes(relative)) != expected:
                raise ProverError(f"{relative} is off its manifest digest")

        # Every path this tool copies, so `selftest` can prove the live tree
        # came through a run byte-identical.
        self.live_paths = tuple(
            sorted(
                {MANIFEST, CHECKER, MEASUREMENT, PARITY}
                | {entry["source"]["path"] for entry in self.manifest["fixtures"]}
                | {
                    artifact["path"]
                    for entry in self.manifest["fixtures"]
                    for artifact in entry["artifacts"].values()
                }
            )
        )

    # --- the live tree, read through the checker's confinement -----------

    def _live_bytes(self, relative: str) -> bytes:
        return self.checker.read_confined(self.root, relative)

    def _live_record(self, relative: str, *, allow_integers: bool = False) -> dict[str, Any]:
        return self.checker.load_canonical_record(
            self._live_bytes(relative), allow_integers=allow_integers
        )

    @staticmethod
    def _subject_fixture(manifest: dict[str, Any]) -> dict[str, Any]:
        for entry in manifest["fixtures"]:
            if entry["id"] == SUBJECT:
                return entry
        raise ProverError(f"the manifest binds no fixture {SUBJECT}")

    def live_digests(self) -> dict[str, str]:
        return {path: digest(self._live_bytes(path)) for path in self.live_paths}

    def coverage_bound_artifacts(self) -> tuple[str, ...]:
        """The subject fixture's paths the coverage register binds by digest.

        The sixth mechanical pass a live reconciliation owes, reported so it is
        visible even though a fixture copy cannot exercise it.
        """
        row = json.loads(self._live_bytes(COVERAGE))["agent_instruction"]
        prefix = f"{FIXTURE_ROOT}/{SUBJECT}/"
        bound = {entry["path"] for entry in row["fixtures"] if entry["path"].startswith(prefix)}
        return tuple(sorted(bound | {row["manifest"]["path"]}))

    # --- edit shapes ------------------------------------------------------

    def edited_source(self, placement: str) -> bytes:
        """The bound source after one out-of-span edit at the named placement."""
        if placement == AFTER_SPAN_PLACEMENT:
            edited = self.source + AFTER_SPAN_EDIT
        elif placement == BEFORE_SPAN_PLACEMENT:
            edited = AFTER_SPAN_EDIT + self.source
        else:
            raise ProverError(f"unknown span placement {placement}")
        return edited

    def in_span_source(self) -> bytes:
        """The bound source after an edit inside the reviewed span.

        Same length, so nothing but the reviewed bytes changes: this isolates
        "the reviewed bytes moved" from "the offsets moved".
        """
        for needle, replacement in ((b"the ", b"THE "), (b"a ", b"A ")):
            index = self.span.find(needle)
            if index >= 0:
                span = self.span[:index] + replacement + self.span[index + len(needle) :]
                break
        else:
            raise ProverError("found no same-length substitution inside the reviewed span")
        edited = self.source[: self.start] + span + self.source[self.end :]
        if len(edited) != len(self.source):
            raise ProverError("the in-span substitution changed the file length")
        if edited[self.start : self.end] == self.span:
            raise ProverError("the in-span substitution left the reviewed span unchanged")
        return edited

    def span_moved(self, edited: bytes) -> bool:
        return edited[self.start : self.end] != self.span

    # --- the throwaway copy ----------------------------------------------

    def copy_tree(self, scratch: Path) -> Path:
        """Everything `check` reads, and nothing else, under a fresh root."""
        tree = scratch / "tree"
        (tree / "scripts").mkdir(parents=True)
        shutil.copytree(self.root / FIXTURE_ROOT, tree / FIXTURE_ROOT)
        shutil.copy2(self.root / CHECKER, tree / CHECKER)
        for entry in self.manifest["fixtures"]:
            relative = entry["source"]["path"]
            destination = tree / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(self.root / relative, destination)
        if digest(self.checker.read_confined(tree, CHECKER)) != digest(self.checker_bytes):
            raise ProverError("the copied checker does not match the repository's")
        return tree

    def _write(self, tree: Path, relative: str, data: bytes) -> None:
        """Confined by the checker's own writer, rooted at the copy."""
        self.checker.write_confined_atomic(tree, relative, data)

    def apply_passes(
        self,
        tree: Path,
        edited: bytes,
        *,
        skip: tuple[str, ...] = (),
        rebind_span: bool = False,
        rebind_measurement_corpus: bool = False,
    ) -> dict[str, Any]:
        """Write the edit into the copy and apply the mechanical passes.

        `skip` leaves out one named pass. That is how each pass is shown to
        be needed: leave one out and a refusal comes back, and it names the
        pass that is missing. Returns the manifest as written.
        """
        for name in skip:
            if name not in MECHANICAL_PASSES:
                raise ProverError(f"unknown mechanical pass {name}")

        manifest = json.loads(json.dumps(self.manifest))
        fixture = self._subject_fixture(manifest)
        new_digest = digest(edited)

        self._write(tree, self.source_path, edited)

        if "manifest-source" not in skip:
            fixture["source"]["sha256"] = new_digest
        if rebind_span:
            # Not a mechanical pass. The reviewed span digest is the review
            # boundary, and moving it is what a re-review means. `span-shift`
            # uses it only to show the refusal that waits behind it.
            fixture["source"]["span_sha256"] = digest(edited[self.start : self.end])

        substitutions = {"model": "model", "source-spans": "source_spans"}
        for pass_name, artifact in substitutions.items():
            relative = fixture["artifacts"][artifact]["path"]
            raw = self._live_bytes(relative)
            if pass_name not in skip:
                occurrences = raw.count(self.old_digest.encode("ascii"))
                if occurrences != 1:
                    raise ProverError(
                        f"{relative} carries the source digest {occurrences} times, expected 1"
                    )
                raw = raw.replace(self.old_digest.encode("ascii"), new_digest.encode("ascii"))
            self._write(tree, relative, raw)

        compact_relative = fixture["artifacts"]["compact"]["path"]
        if "compact" in skip:
            self._write(tree, compact_relative, self._live_bytes(compact_relative))
        else:
            # Regenerated rather than substituted: the compact document is a
            # derived view of the model, and `format` is what derives it.
            self.run_checker(
                tree,
                ["format", "--root", ".", "--input", fixture["artifacts"]["model"]["path"],
                 "--output", compact_relative],
            )

        if "manifest-artifacts" not in skip:
            for artifact in ("model", "compact", "source_spans"):
                relative = fixture["artifacts"][artifact]["path"]
                fixture["artifacts"][artifact]["sha256"] = digest(
                    self.checker.read_confined(tree, relative)
                )

        if rebind_measurement_corpus:
            # Move the measurement record's recorded corpus digest onto the
            # recomputed one. Not a reissue: no count and no date is touched,
            # and no model is consulted. It exists so the refusal waiting at
            # `$.evidence.parity_record` is reachable, the checker comparing
            # the measurement record first.
            measurement = self.checker.load_canonical_record(
                self.checker.read_confined(tree, MEASUREMENT), allow_integers=True
            )
            measurement["corpus_sha256"] = self.checker._corpus_sha256(manifest)
            written = self.checker.canonical_record_bytes(measurement, allow_integers=True)
            self._write(tree, MEASUREMENT, written)
            manifest["evidence"]["measurement_record"]["sha256"] = digest(written)

        self._write(tree, MANIFEST, self.checker.canonical_record_bytes(manifest))
        return manifest

    # --- the checker, as a subprocess ------------------------------------

    def run_checker(self, tree: Path, arguments: list[str]) -> tuple[int, list[dict[str, Any]]]:
        """The checker over the copy: argument list, no shell, fixed environment."""
        completed = subprocess.run(  # noqa: S603 - argument list, no shell, fixed env
            [sys.executable, CHECKER, *arguments],
            cwd=str(tree),
            env={
                "PATH": "/usr/bin:/bin",
                "LC_ALL": "C.UTF-8",
                "PYTHONIOENCODING": "utf-8",
                "PYTHONDONTWRITEBYTECODE": "1",
            },
            capture_output=True,
            timeout=CHECK_TIMEOUT_SECONDS,
            check=False,
        )
        if len(completed.stdout) > MAX_OUTPUT_BYTES:
            raise ProverError("the checker wrote more output than this tool will parse")
        records = []
        for line in completed.stdout.decode("utf-8", "replace").splitlines():
            line = line.strip()
            if line.startswith("{"):
                records.append(json.loads(line))
        return completed.returncode, records

    def check(self, tree: Path) -> tuple[int, list[dict[str, Any]]]:
        return self.run_checker(tree, ["check", "--root", ".", "--manifest", MANIFEST])

    @staticmethod
    def refusals(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [record for record in records if record.get("outcome") == "refused"]

    # --- the corpus digest, as the checker computes it -------------------

    def corpus_digest(self, manifest: dict[str, Any]) -> str:
        return self.checker._corpus_sha256(manifest)

    def recorded_corpus_digests(self) -> dict[str, str]:
        return {
            "measurement_record": self._live_record(MEASUREMENT, allow_integers=True)[
                "corpus_sha256"
            ],
            "parity_record": self._live_record(PARITY, allow_integers=True)["corpus_sha256"],
        }

    # --- one reconciliation, start to finish ----------------------------

    def reconcile(self, edited: bytes, **options) -> dict[str, Any]:
        """Copy, edit, apply the passes, and report what `check` said."""
        with tempfile.TemporaryDirectory(prefix="prove-agent-instruction-") as scratch:
            tree = self.copy_tree(Path(scratch))
            manifest = self.apply_passes(tree, edited, **options)
            exit_code, records = self.check(tree)
            outcome = {
                "exit": exit_code,
                "accepted": exit_code == 0,
                "corpus_sha256": self.corpus_digest(manifest),
                "refusals": [
                    {"code": record.get("code"), "node_path": record.get("node_path")}
                    for record in self.refusals(records)
                ],
            }
        return outcome


# --- the three subcommands ---------------------------------------------


def prove_offline(reconciliation: Reconciliation) -> tuple[bool, dict[str, Any], bool]:
    """An out-of-span edit, every mechanical pass applied, no model consulted.

    Met when the reconciliation leaves the tree accepted. Until the corpus
    subject moves, it does not, and this reports that rather than routing
    around it.
    """
    edited = reconciliation.edited_source(AFTER_SPAN_PLACEMENT)
    if reconciliation.span_moved(edited):
        raise ProverError("the out-of-span edit moved the reviewed span")
    outcome = reconciliation.reconcile(edited)
    return outcome["accepted"], outcome, outcome["accepted"]


def prove_span_shift(reconciliation: Reconciliation) -> tuple[int, dict[str, Any], bool]:
    """The span placements whose reconciliation outcome is proved here.

    An edit before a reviewed span start moves every recorded binding offset
    and an edit after it moves none, so the two placements are separate claims
    and the value counts placements rather than cases. The runbook schedules
    the before-span placement at step 4; until it is covered this reports the
    criterion unmet, because a count that reached its threshold while a
    placement went unexercised would be the wrong kind of green.

    The in-span cases travel in the detail rather than the count. They are
    characterisation of the boundary the placements sit either side of, not a
    placement of their own.
    """
    placements: dict[str, Any] = {
        AFTER_SPAN_PLACEMENT: reconciliation.reconcile(
            reconciliation.edited_source(AFTER_SPAN_PLACEMENT)
        ),
    }
    uncovered = [name for name in (BEFORE_SPAN_PLACEMENT,) if name not in placements]

    in_span = reconciliation.in_span_source()
    detail = {
        "placements": placements,
        "uncovered": uncovered,
        "in_span": {
            "every-mechanical-pass": reconciliation.reconcile(in_span),
            "span-digest-also-rebound": reconciliation.reconcile(in_span, rebind_span=True),
        },
    }
    return len(placements), detail, not uncovered


def prove_selftest(reconciliation: Reconciliation) -> tuple[int, dict[str, Any], bool]:
    """This tool's own machinery, before any claim it makes is worth reading."""
    checks: dict[str, Any] = {}

    before = reconciliation.live_digests()

    # A no-op reconciliation reproduces the committed bytes: the passes are a
    # rewrite of the digest and nothing else, so an unedited source leaves the
    # tree accepted.
    unedited = reconciliation.reconcile(reconciliation.source)
    checks["no-op-reconciliation-accepted"] = unedited["accepted"]
    if not unedited["accepted"]:
        raise ProverError(f"a no-op reconciliation did not go green: {unedited['refusals']}")

    # No mechanical pass can be dropped, and each one's refusal names it.
    edited = reconciliation.edited_source(AFTER_SPAN_PLACEMENT)
    complete = reconciliation.reconcile(edited)
    signatures: dict[str, Any] = {}
    for name in MECHANICAL_PASSES:
        omitted = reconciliation.reconcile(edited, skip=(name,))
        if omitted["accepted"]:
            raise ProverError(f"omitting the {name} pass left the tree accepted")
        signatures[name] = omitted["refusals"][0]
    distinct = {json.dumps(value, sort_keys=True) for value in signatures.values()}
    if len(distinct) != len(MECHANICAL_PASSES):
        raise ProverError("two mechanical passes share a refusal signature")
    checks["mechanical-pass-signatures"] = signatures
    checks["complete-reconciliation-refusal"] = complete["refusals"][0]

    # The confinement refuses what it is there to refuse, rather than being
    # trusted because it is imported.
    escapes = (
        "../escape",
        "/etc/passwd",
        "tests/../../escape",
        "tests\\escape",
        "",
    )
    refused = []
    with tempfile.TemporaryDirectory(prefix="prove-agent-instruction-confinement-") as scratch:
        tree = Path(scratch) / "tree"
        tree.mkdir()
        for candidate in escapes:
            try:
                reconciliation.checker.write_confined_atomic(tree, candidate, b"x\n")
            except reconciliation.checker.CodecError as error:
                refused.append({"path": candidate, "code": error.code})
            else:
                raise ProverError(f"the confinement accepted {candidate!r}")
        if list(tree.iterdir()):
            raise ProverError("a refused write left something behind")
    checks["confinement-refusals"] = refused

    # The live tree came through every one of those runs untouched.
    after = reconciliation.live_digests()
    if before != after:
        moved = sorted(path for path in before if before[path] != after[path])
        raise ProverError(f"the live tree changed during a proof: {moved}")
    checks["live-tree-unchanged"] = sorted(before)

    # The sixth pass a live reconciliation owes, named rather than assumed.
    checks[UNOBSERVED_PASS] = list(reconciliation.coverage_bound_artifacts())

    # Every check above raises rather than returning false, so reaching here
    # is the pass condition.
    return len(checks), checks, True


SUBCOMMANDS = {
    "offline": ("offline-reconciliation-green", "boolean", prove_offline),
    "span-shift": ("span-shift-regression", "count", prove_span_shift),
    "selftest": ("prover-selftest", "count", prove_selftest),
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prove what a bound instruction-document edit costs, with no model.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Closed at parser-build time against the design record beside this script,
    # so an unknown candidate is a usage error before any proof runs.
    choices = candidate_choices(Path(__file__).resolve().parents[1])
    subparsers = parser.add_subparsers(dest="command")
    for name in SUBCOMMANDS:
        subparser = subparsers.add_parser(name)
        subparser.add_argument("--root", default=".")
        subparser.add_argument("--candidate", default="digest-neutral-corpus", choices=choices)
        subparser.add_argument("--report")
        subparser.add_argument("--detail", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(argv)
    if arguments.command is None:
        parser.print_help()
        return 0

    criterion, unit, prove = SUBCOMMANDS[arguments.command]
    root = Path(arguments.root).resolve()
    command = " ".join(
        [
            "python3",
            "scripts/prove_agent_instruction_reconciliation.py",
            arguments.command,
            "--root",
            str(root),
            "--candidate",
            arguments.candidate,
        ]
        + (["--report", arguments.report] if arguments.report else [])
    )

    try:
        reconciliation = Reconciliation(root)
        value, detail, met = prove(reconciliation)
    except ProverError as error:
        print(f"prove_agent_instruction_reconciliation: {error}", file=sys.stderr)
        return 2

    record = {
        "candidate": arguments.candidate,
        "command": command,
        "criterion": criterion,
        "exit": 0 if met else 1,
        "schema": SCHEMA,
        "unit": unit,
        "value": value,
    }
    written = report_bytes(record)

    if arguments.report:
        try:
            write_report(
                reconciliation.checker,
                root,
                arguments.report,
                written,
                bound_targets(root, reconciliation.manifest),
            )
        except ProverError as error:
            print(
                f"prove_agent_instruction_reconciliation: refused to write "
                f"{arguments.report}: {error}",
                file=sys.stderr,
            )
            return 2
        except reconciliation.checker.CodecError as error:
            print(
                f"prove_agent_instruction_reconciliation: refused to write "
                f"{arguments.report}: {error.code}",
                file=sys.stderr,
            )
            return 2
    else:
        sys.stdout.write(written.decode("utf-8"))

    if arguments.detail:
        sys.stderr.write(json.dumps(detail, indent=2, sort_keys=True) + "\n")
    return record["exit"]


if __name__ == "__main__":
    raise SystemExit(main())
