#!/usr/bin/env python3
"""Prove what a bound-source edit costs, without consulting a model.

Three instruction documents are bound into `tests/fixtures/agent-instruction-v1`
by whole-file SHA-256.  Editing one starts the reconciliation sequence
skills#1030 records.  This tool runs that sequence against a throwaway copy of
the tree and reports what the repository's own checker says afterwards, so the
cost of an edit is observed rather than argued about.

    offline      an out-of-span edit *after* the reviewed span end, every
                 mechanical pass applied: does `agent_instruction.py check` go
                 green with no model consulted?  It answers for that placement
                 and says nothing about the other one.
    span-shift   the edit placements whose reconciliation outcome is proved,
                 because only an edit before a reviewed span start moves the
                 recorded binding offsets.  Its count is placements covered,
                 not placements green, and the two do not agree: the after-span
                 placement reconciles accepted, and the before-span placement
                 refuses `WAI-E-DIGEST.CORPUS` at
                 `$.evidence.measurement_record` once its offsets are
                 reconciled.  The seven-key report carries the count and the
                 exit; the outcome of each placement is on `--detail`.
    selftest     the tool's own machinery: fixture-copy isolation, a no-op
                 reconciliation that reproduces the committed bytes, and the
                 path confinement that keeps every write inside the copy.

Each subcommand writes one closed `protasis-design-report/v1` object, the same
seven-key shape `.hexaemeron/scripts/design_probe.py` writes, either to
`--report` or to stdout.

The mechanical passes, applied in this order and named so a missing one is
identifiable from the refusal it produces:

    manifest-source      manifest `fixtures[i].source.sha256`
    model                `<fixture>/model.json` `sources[0].sha256`
    source-spans         `<fixture>/source-spans.json` `source.sha256`
    compact              `<fixture>/compact.wai`, regenerated by the checker's
                         own `format`, because it embeds the digest as `h64:`
    manifest-artifacts   manifest `artifacts.{compact,model,source_spans}.sha256`

One further pass runs beside those five, and only an edit before a reviewed
span start needs it:

    span-offsets         the manifest's `source.start` and `source.end`, every
                         `source-spans.json` span's `start` and `end`, and every
                         `model.json` binding's `start` and `end`

It is not in `MECHANICAL_PASSES` because it is a no-op for the placement those
five were characterised against: an edit after the reviewed span moves no
offset, so skipping it there leaves the tree accepted and it cannot be shown to
be needed the way the five are. `span-shift` shows it needed where it is needed,
against a before-span edit. What it writes is re-derived rather than shifted:
each recorded span is located in the edited source by its own bytes, whose
digest an out-of-span edit does not move, and the offsets are read off from
where those bytes now are. Adding a byte delta to each recorded number would
produce the same integers here while proving nothing about where the span went,
so `rederive_offsets` computes the uniform delta from the anchor and then checks
every independently located span against it rather than assuming it.

What a test can separate from arithmetic is bounded by the fixture. A prepend
moves every span by one uniform delta, so a node located by its own bytes and a
node moved by `delta` land on the same integers, and no assertion on the
integers can tell the two apart. What separates them is the refusal a shift has
no opinion about: bytes that occur more than once inside the reviewed span
identify no offset, and the node loop refuses instead of taking the first
occurrence. `test_a_before_span_edit_has_its_offsets_re_derived_rather_than_shifted`
pins that refusal for a node as well as for the anchor, which is where the claim
in this paragraph is held rather than merely stated.

A live reconciliation owes one more pass this tool does not exercise: the
matching digests in the `agent_instruction` row of
`tests/promise_machine_coverage.json`.  `agent_instruction.py check` never
reads that file, so a fixture copy cannot observe it; `tests/test_agent_instruction.py`
is what holds it current.  `coverage_bound_artifacts` reports which paths that
row binds so the pass is not forgotten.

Boundaries this tool holds to, per the study's `reconcile-tool-writes` entry:

- Every write inside the copy goes through the checker's own
  `write_confined_atomic`, and every read through its `read_confined`, rather
  than through a reimplementation.  Both refuse an absolute path, a `..`
  component, a backslash, a control character and a symlinked component.
- The bound sources in the live repository are never written.  The edit is
  applied to the copy, and `selftest` proves the live tree's digests are
  unchanged across a run.
- `--report` is the one write this tool makes outside the copy, so it refuses a
  target the manifest binds by digest.  The bound set is derived from the
  manifest rather than listed here, and `tests/test_agent_instruction_corpus.py`
  exercises the refusal against a throwaway copy.
- The checker runs as a subprocess with an argument list, no shell, a
  constructed environment rather than the ambient one, the copy as its working
  directory, a wall-clock timeout and a cap on the output parsed.
- The checker's bytes are digest-checked against the repository copy before it
  is executed, so the subprocess runs bytes this tool verified.
- Nothing here opens a socket, starts a model, or reads a credential.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


SCHEMA = "protasis-design-report/v1"

FIXTURE_ROOT = "tests/fixtures/agent-instruction-v1"
MANIFEST = f"{FIXTURE_ROOT}/manifest.json"
MEASUREMENT = f"{FIXTURE_ROOT}/evidence/measurement.json"
PARITY = f"{FIXTURE_ROOT}/evidence/parity.json"
CHECKER = "scripts/agent_instruction.py"
COVERAGE = "tests/promise_machine_coverage.json"

# The fixture whose bound source these proofs edit. The other two are left
# alone deliberately: an edit to one bound document must not invalidate the
# recorded counts of the other two either.
SUBJECT = "fiat-study-runbook-phase"

# The mechanical passes, in application order.
MECHANICAL_PASSES = (
    "manifest-source",
    "model",
    "source-spans",
    "compact",
    "manifest-artifacts",
)

# The pass that re-derives the recorded offsets. Kept out of MECHANICAL_PASSES
# deliberately: it is a no-op after the reviewed span, so omitting it there
# leaves the tree accepted and `prove_selftest`'s five-way omission loop cannot
# demonstrate it. Its own demonstration is against a before-span edit.
OFFSET_PASS = "span-offsets"

# The pass a live reconciliation owes that a fixture copy cannot observe,
# because `agent_instruction.py check` does not read the coverage register.
UNOBSERVED_PASS = "coverage-register"

# The out-of-span edit, applied at either placement. Prepended it lands before
# the reviewed span start and moves every recorded offset; appended it lands
# after the reviewed span end and moves none.
OUT_OF_SPAN_EDIT = b"\n<!-- prove: skills#1098 out-of-span edit -->\n"

# The two placements an out-of-span edit can take relative to the reviewed span.
# `span-shift` covers both, because they are separate claims: only the first
# moves the recorded binding offsets, which is #1098's third acceptance check.
BEFORE_SPAN_PLACEMENT = "before-span"
AFTER_SPAN_PLACEMENT = "after-span"
SPAN_PLACEMENTS = (BEFORE_SPAN_PLACEMENT, AFTER_SPAN_PLACEMENT)

CHECK_TIMEOUT_SECONDS = 600
MAX_OUTPUT_BYTES = 1 << 20

# The run's design record, read to close `--candidate`.
DESIGN_EVIDENCE = ".hexaemeron/design-evidence.json"
MAX_DESIGN_EVIDENCE_BYTES = 1 << 20

# The closed candidate set, used only when the run's design record is not
# readable, because this tool is runnable outside a Fiat run.
# `.hexaemeron/scripts/design_probe.py` closes the same flag over the same ids.
FALLBACK_CANDIDATES = (
    "deterministic-tokenizer",
    "digest-neutral-corpus",
    "evidence-outside-corpus",
    "published-profile",
)


class ProverError(RuntimeError):
    """The tool cannot complete a check, so it reports nothing rather than a guess."""


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def recorded_offset(value: Any, label: str, limit: int) -> int:
    """One offset, read the way the canonical records write it.

    An unsigned ASCII decimal with no padding, inside the file it indexes.
    `int()` on its own would take `"+1"`, `" 1"`, `"1_0"`, a Unicode digit and
    a run of digits of any length, and it raises `ValueError` rather than a
    `ProverError` on the rest -- so a record that had drifted would reach the
    reader as a crash instead of a refusal naming the field. These records are
    read from a tree this tool does not control, which is the whole reason the
    constructor checks the tree against itself first.
    """
    if not isinstance(value, str) or not value.isascii() or not value.isdigit():
        raise ProverError(f"{label} is not a recorded decimal offset")
    if len(value) > 1 and value.startswith("0"):
        raise ProverError(f"{label} is a padded decimal, which no record writes")
    number = int(value)
    if number > limit:
        raise ProverError(f"{label} is past the end of the source it indexes")
    return number


def report_bytes(record: dict[str, Any]) -> bytes:
    """The exact canonical shape design_probe.py writes its reports in."""
    return (
        json.dumps(
            record,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode("utf-8")


def candidate_choices(root: Path) -> tuple[str, ...]:
    """The candidate ids the run's design record declares.

    Read from the record rather than listed here, so the flag tracks the design
    this run actually selected from. `--candidate` is closed over the result, so
    a typo is a usage error rather than a `protasis-design-report/v1` object
    naming a candidate no design record contains.

    Falls back to the closed set above when the record is absent, oversized or
    malformed, because the flag must stay closed even where the record is not
    there to close it.
    """
    path = Path(root) / DESIGN_EVIDENCE
    try:
        if path.stat().st_size > MAX_DESIGN_EVIDENCE_BYTES:
            return FALLBACK_CANDIDATES
        record = json.loads(path.read_bytes())
        ids = tuple(str(entry["id"]) for entry in record["candidates"])
    except (OSError, ValueError, KeyError, TypeError):
        return FALLBACK_CANDIDATES
    return ids or FALLBACK_CANDIDATES


def bound_digests(manifest: dict[str, Any]) -> tuple[tuple[str, str], ...]:
    """Every path the manifest binds by digest, with the digest it binds.

    One enumeration serves both the constructor's self-consistency check and
    the `--report` guard, so the two cannot drift apart: a path the manifest
    starts binding is checked and protected in the same commit that adds it.
    """
    entries: list[tuple[str, str]] = []
    for entry in manifest["fixtures"]:
        entries.append((entry["source"]["path"], entry["source"]["sha256"]))
        for name in sorted(entry["artifacts"]):
            artifact = entry["artifacts"][name]
            entries.append((artifact["path"], artifact["sha256"]))
    return tuple(sorted(set(entries)))


def bound_targets(root: Path, manifest: dict[str, Any]) -> frozenset[Path]:
    """Every path the manifest binds by digest, resolved absolute.

    Derived from the manifest rather than listed here, so the guard tracks what
    the manifest binds instead of drifting from it. Both sides are resolved, so
    a symlinked route to a bound path is the same path.
    """
    relative = {MANIFEST} | {path for path, _ in bound_digests(manifest)}
    return frozenset((Path(root) / path).resolve() for path in sorted(relative))


def write_report(checker, root: Path, target: str, data: bytes, bound: frozenset[Path]) -> None:
    """Write one report through the checker's confined atomic writer.

    A relative `--report` is confined to `--root`, which is how the design
    record's own resolver commands name it: `.hexaemeron/reports/<criterion>.json`.
    An absolute one is confined to the directory the operator named, so a
    caller can write outside the repository without the writer losing its
    `O_NOFOLLOW` parent walk, its refusal of a non-regular leaf, or its
    atomic replace. Either way the leaf goes through `_safe_relative_path`,
    so `..`, a backslash, a control character and an empty name refuse.

    The path is operator argv, not data read from outside the process, so the
    writer's own controls are about symlinks and half-written files rather than
    about which directory an operator may choose. One choice is not the
    operator's to make: this is the only write the tool performs outside its
    throwaway copy, and the study's "Never" list rules out editing a bound
    document. A target the manifest binds is therefore refused before anything
    is opened, so `--report PROMISE_MACHINE.md --root .` cannot replace a bound
    document with a JSON report.
    """
    path = Path(target)
    absolute = path if path.is_absolute() else Path(root) / path
    if absolute.resolve() in bound:
        raise ProverError(
            f"{target} is a path the manifest binds by digest; "
            "writing a report over it would destroy bound bytes"
        )
    if path.is_absolute():
        checker.write_confined_atomic(path.parent, path.name, data)
    else:
        checker.write_confined_atomic(root, target, data)


def load_checker(root: Path):
    """The repository's own checker, as a module.

    Loaded rather than reimplemented so the corpus digest this tool reasons
    about is the digest the checker computes, and so its path confinement is
    the audited code rather than a copy of it.
    """
    script = root / CHECKER
    spec = importlib.util.spec_from_file_location("agent_instruction", script)
    if spec is None or spec.loader is None:
        raise ProverError(f"cannot load the checker at {script}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class Reconciliation:
    """One bound-source edit, reconciled inside a throwaway copy of the tree.

    Construction reads the live tree and verifies it agrees with itself before
    anything is copied, so a proof never runs against a tree that was already
    inconsistent. "Agrees with itself" means every path `bound_digests` reports:
    each fixture's source and each of its artefacts, not only the subject
    fixture's rewritten ones. Nothing here writes to the live tree.
    """

    def __init__(self, root: Path, checker=None) -> None:
        self.root = Path(root).resolve()
        self.checker = checker if checker is not None else load_checker(self.root)
        self.checker_bytes = self._live_bytes(CHECKER)

        self.manifest = self._live_record(MANIFEST)
        self.fixture = self._subject_fixture(self.manifest)
        self.source_path = self.fixture["source"]["path"]
        self.source = self._live_bytes(self.source_path)
        self.old_digest = self.fixture["source"]["sha256"]

        if digest(self.source) != self.old_digest:
            raise ProverError(
                f"{self.source_path} is already off its manifest digest; "
                "reconcile the live tree before proving anything about it"
            )

        # Read the way every other recorded offset in this tool is read. These
        # two are the anchor the whole re-derivation hangs off, so leaving them
        # on bare `int()` would exempt the one pair that matters most from the
        # rule `recorded_offset` exists to state.
        limit = len(self.source)
        self.start = recorded_offset(
            self.fixture["source"]["start"], "the reviewed span's start", limit
        )
        self.end = recorded_offset(
            self.fixture["source"]["end"], "the reviewed span's end", limit
        )
        if self.end <= self.start:
            raise ProverError(
                f"{self.source_path} has a reviewed span that ends at or before it starts"
            )
        self.span = self.source[self.start : self.end]
        if digest(self.span) != self.fixture["source"]["span_sha256"]:
            raise ProverError(f"{self.source_path} has a reviewed span off its manifest digest")

        # Every bound path, not just the subject fixture's rewritten artefacts.
        # A proof that started against a tree already off one of these would
        # report a refusal caused by pre-existing drift as though the edit
        # caused it, which is the confusion this check exists to prevent.
        for relative, expected in bound_digests(self.manifest):
            if digest(self._live_bytes(relative)) != expected:
                raise ProverError(f"{relative} is off its manifest digest")

        # Every path this tool copies, so `selftest` can prove the live tree
        # came through a run byte-identical.
        self.live_paths = tuple(
            sorted(
                {MANIFEST, CHECKER, MEASUREMENT, PARITY}
                | {entry["source"]["path"] for entry in self.manifest["fixtures"]}
                | {
                    artifact["path"]
                    for entry in self.manifest["fixtures"]
                    for artifact in entry["artifacts"].values()
                }
            )
        )

    # --- the live tree, read through the checker's confinement -----------

    def _live_bytes(self, relative: str) -> bytes:
        return self.checker.read_confined(self.root, relative)

    def _live_record(self, relative: str, *, allow_integers: bool = False) -> dict[str, Any]:
        return self.checker.load_canonical_record(
            self._live_bytes(relative), allow_integers=allow_integers
        )

    @staticmethod
    def _subject_fixture(manifest: dict[str, Any]) -> dict[str, Any]:
        for entry in manifest["fixtures"]:
            if entry["id"] == SUBJECT:
                return entry
        raise ProverError(f"the manifest binds no fixture {SUBJECT}")

    def live_digests(self) -> dict[str, str]:
        return {path: digest(self._live_bytes(path)) for path in self.live_paths}

    def coverage_bound_artifacts(self) -> tuple[str, ...]:
        """The subject fixture's paths the coverage register binds by digest.

        The sixth mechanical pass a live reconciliation owes, reported so it is
        visible even though a fixture copy cannot exercise it.
        """
        row = json.loads(self._live_bytes(COVERAGE))["agent_instruction"]
        prefix = f"{FIXTURE_ROOT}/{SUBJECT}/"
        bound = {entry["path"] for entry in row["fixtures"] if entry["path"].startswith(prefix)}
        return tuple(sorted(bound | {row["manifest"]["path"]}))

    # --- edit shapes ------------------------------------------------------

    def edited_source(self, placement: str) -> bytes:
        """The bound source after one out-of-span edit at the named placement."""
        if placement == AFTER_SPAN_PLACEMENT:
            edited = self.source + OUT_OF_SPAN_EDIT
        elif placement == BEFORE_SPAN_PLACEMENT:
            edited = OUT_OF_SPAN_EDIT + self.source
        else:
            raise ProverError(f"unknown span placement {placement}")
        return edited

    def in_span_source(self) -> bytes:
        """The bound source after an edit inside the reviewed span.

        Same length, so nothing but the reviewed bytes changes: this isolates
        "the reviewed bytes moved" from "the offsets moved".
        """
        for needle, replacement in ((b"the ", b"THE "), (b"a ", b"A ")):
            index = self.span.find(needle)
            if index >= 0:
                span = self.span[:index] + replacement + self.span[index + len(needle) :]
                break
        else:
            raise ProverError("found no same-length substitution inside the reviewed span")
        edited = self.source[: self.start] + span + self.source[self.end :]
        if len(edited) != len(self.source):
            raise ProverError("the in-span substitution changed the file length")
        if edited[self.start : self.end] == self.span:
            raise ProverError("the in-span substitution left the reviewed span unchanged")
        return edited

    def span_moved(self, edited: bytes) -> bool:
        return edited[self.start : self.end] != self.span

    # --- re-deriving the recorded offsets ---------------------------------

    @staticmethod
    def _locate(haystack: bytes, needle: bytes, label: str, base: int = 0) -> int:
        """Where `needle` sits in `haystack`, refusing anything but one answer.

        Absent means the edit reached inside the reviewed bytes, so there is no
        span to re-derive an offset for. More than once means the bytes do not
        identify a position, and picking the first would be a guess dressed as a
        measurement. Both refuse rather than returning a number.
        """
        first = haystack.find(needle)
        if first < 0:
            raise ProverError(f"the recorded bytes of {label} are not in the edited source")
        if haystack.find(needle, first + 1) >= 0:
            raise ProverError(
                f"the recorded bytes of {label} occur more than once in the edited "
                "source, so they do not identify an offset"
            )
        return base + first

    def rederive_offsets(self, edited: bytes) -> dict[str, Any] | None:
        """Where every recorded span sits in the edited source, read off its bytes.

        The reviewed span digest is the anchor. An edit outside the reviewed
        span leaves the span's bytes intact, so the span can be found in the
        edited source and its new offsets read off from where it was found;
        `span_sha256` is recomputed at those offsets rather than carried over,
        so a location that is not the reviewed span refuses instead of being
        recorded.

        Each node span is then located the same way, inside the re-derived
        reviewed span rather than the whole file, and each one's own recorded
        `sha256` is checked at its new offsets. So every number written back
        comes from a located, digest-checked position.

        The uniform delta is computed from the anchor and used as a check, not
        as the source of the answer: if an independently located node has not
        moved by the same delta as the reviewed span, the recorded offsets and
        the bytes disagree about the document's shape, and that is a finding
        rather than something to average away. It refuses.

        Returns `None` when the anchor's bytes are gone from the edited source.
        That is an in-span edit, where there is nothing to re-derive: the
        reviewed bytes themselves changed, and `check` refuses at
        `WAI-E-DIGEST.SOURCE_SPAN` for that reason and not for a stale offset.
        """
        if self.span not in edited:
            return None

        anchor = self.fixture["source"]["span_sha256"]
        governed_start = self._locate(edited, self.span, "the reviewed span")
        governed_end = governed_start + len(self.span)
        if digest(edited[governed_start:governed_end]) != anchor:
            raise ProverError("the re-derived reviewed span is off its recorded digest")
        delta = governed_start - self.start

        spans = self._live_record(self.fixture["artifacts"]["source_spans"]["path"])
        governed = edited[governed_start:governed_end]
        nodes: dict[str, dict[str, Any]] = {}
        for entry in spans["spans"]:
            node = str(entry["node"])
            limit = len(self.source)
            start = recorded_offset(entry["start"], f"{node}.start", limit)
            end = recorded_offset(entry["end"], f"{node}.end", limit)
            if end <= start:
                raise ProverError(f"the recorded span for {node} ends at or before it starts")
            recorded = self.source[start:end]
            if digest(recorded) != entry["sha256"]:
                raise ProverError(f"the recorded span for {node} is off its own digest")
            new_start = self._locate(governed, recorded, node, base=governed_start)
            new_end = new_start + len(recorded)
            if digest(edited[new_start:new_end]) != entry["sha256"]:
                raise ProverError(f"the re-derived span for {node} is off its recorded digest")
            if new_start - start != delta:
                raise ProverError(
                    f"the re-derived span for {node} moved by {new_start - start} bytes "
                    f"and the reviewed span moved by {delta}; the recorded offsets and "
                    "the source disagree about the document's shape"
                )
            nodes[node] = {
                "recorded": [start, end],
                "rederived": [new_start, new_end],
                "sha256": entry["sha256"],
            }

        return {
            "anchor_sha256": anchor,
            "delta": delta,
            "governed": {
                "recorded": [self.start, self.end],
                "rederived": [governed_start, governed_end],
            },
            "nodes": nodes,
        }

    def _write_rederived_offsets(
        self, entries: list[dict[str, Any]], offsets: dict[str, Any]
    ) -> None:
        """Write each entry's re-derived offsets back, keyed on where it was.

        Keyed on the recorded pair rather than on the node alone, because two
        nodes may cover the same bytes, and keyed at all rather than adding
        `delta`, so an entry the re-derivation did not locate refuses instead of
        being moved by arithmetic.
        """
        located = {
            (node, tuple(value["recorded"])): value["rederived"]
            for node, value in offsets["nodes"].items()
        }
        for entry in entries:
            node = str(entry["node"])
            limit = len(self.source)
            key = (
                node,
                (
                    recorded_offset(entry["start"], f"{node}.start", limit),
                    recorded_offset(entry["end"], f"{node}.end", limit),
                ),
            )
            if key not in located:
                raise ProverError(f"no re-derived offset for {key[0]} at {key[1]}")
            start, end = located[key]
            entry["start"] = str(start)
            entry["end"] = str(end)

    def _rewritten_offsets(self, artifact: str, raw: bytes, offsets: dict[str, Any]) -> bytes:
        """One artefact's bytes with its recorded offsets re-derived.

        Round-tripped through the checker's own canonical serialiser, and the
        untouched record is required to reproduce its own bytes first, so a
        rewrite cannot smuggle in a formatting difference and call it an offset
        change.
        """
        if artifact == "source_spans":
            record = self.checker.load_canonical_record(raw)
            if self.checker.canonical_record_bytes(record) != raw:
                raise ProverError("source-spans.json is not its own canonical bytes")
            self._write_rederived_offsets(record["spans"], offsets)
            return self.checker.canonical_record_bytes(record)
        if artifact == "model":
            model = self.checker.load_canonical_json(raw)
            if self.checker.canonical_json_bytes(model) != raw:
                raise ProverError("model.json is not its own canonical bytes")
            self._write_rederived_offsets(model["bindings"], offsets)
            return self.checker.canonical_json_bytes(model)
        raise ProverError(f"no offsets are recorded in {artifact}")

    # --- the throwaway copy ----------------------------------------------

    def copy_tree(self, scratch: Path) -> Path:
        """Everything `check` reads, and nothing else, under a fresh root."""
        tree = scratch / "tree"
        (tree / "scripts").mkdir(parents=True)
        shutil.copytree(self.root / FIXTURE_ROOT, tree / FIXTURE_ROOT)
        shutil.copy2(self.root / CHECKER, tree / CHECKER)
        for entry in self.manifest["fixtures"]:
            relative = entry["source"]["path"]
            destination = tree / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(self.root / relative, destination)
        if digest(self.checker.read_confined(tree, CHECKER)) != digest(self.checker_bytes):
            raise ProverError("the copied checker does not match the repository's")
        return tree

    def _write(self, tree: Path, relative: str, data: bytes) -> None:
        """Confined by the checker's own writer, rooted at the copy."""
        self.checker.write_confined_atomic(tree, relative, data)

    def apply_passes(
        self,
        tree: Path,
        edited: bytes,
        *,
        skip: tuple[str, ...] = (),
        rebind_span: bool = False,
        rebind_measurement_corpus: bool = False,
    ) -> dict[str, Any]:
        """Write the edit into the copy and apply the mechanical passes.

        `skip` leaves out one named pass. That is how each pass is shown to
        be needed: leave one out and a refusal comes back, and it names the
        pass that is missing. `OFFSET_PASS` is skippable on the same terms,
        which is how a before-span edit is shown to need it. Returns the
        manifest as written.
        """
        for name in skip:
            if name not in MECHANICAL_PASSES and name != OFFSET_PASS:
                raise ProverError(f"unknown mechanical pass {name}")

        manifest = json.loads(json.dumps(self.manifest))
        fixture = self._subject_fixture(manifest)
        new_digest = digest(edited)

        # Re-derived before anything is written, so a refusal to locate the
        # spans stops the reconciliation rather than leaving a half-rewritten
        # copy behind. `None` means the reviewed bytes themselves changed, and
        # there is no offset to re-derive.
        offsets = None if OFFSET_PASS in skip else self.rederive_offsets(edited)
        span_start, span_end = self.start, self.end
        if offsets is not None:
            span_start, span_end = offsets["governed"]["rederived"]

        self._write(tree, self.source_path, edited)

        if "manifest-source" not in skip:
            fixture["source"]["sha256"] = new_digest
        if offsets is not None:
            fixture["source"]["start"] = str(span_start)
            fixture["source"]["end"] = str(span_end)
        if rebind_span:
            # Not a mechanical pass. The reviewed span digest is the review
            # boundary, and moving it is what a re-review means. `span-shift`
            # uses it only to show the refusal that waits behind it. Taken at
            # the effective offsets, so it rebinds the reviewed span and not
            # whatever the edit pushed into its old position.
            fixture["source"]["span_sha256"] = digest(edited[span_start:span_end])

        substitutions = {"model": "model", "source-spans": "source_spans"}
        for pass_name, artifact in substitutions.items():
            relative = fixture["artifacts"][artifact]["path"]
            raw = self._live_bytes(relative)
            if pass_name not in skip:
                occurrences = raw.count(self.old_digest.encode("ascii"))
                if occurrences != 1:
                    raise ProverError(
                        f"{relative} carries the source digest {occurrences} times, expected 1"
                    )
                raw = raw.replace(self.old_digest.encode("ascii"), new_digest.encode("ascii"))
            if offsets is not None:
                raw = self._rewritten_offsets(artifact, raw, offsets)
            self._write(tree, relative, raw)

        compact_relative = fixture["artifacts"]["compact"]["path"]
        if "compact" in skip:
            self._write(tree, compact_relative, self._live_bytes(compact_relative))
        else:
            # Regenerated rather than substituted: the compact document is a
            # derived view of the model, and `format` is what derives it.
            self.run_checker(
                tree,
                ["format", "--root", ".", "--input", fixture["artifacts"]["model"]["path"],
                 "--output", compact_relative],
            )

        if "manifest-artifacts" not in skip:
            for artifact in ("model", "compact", "source_spans"):
                relative = fixture["artifacts"][artifact]["path"]
                fixture["artifacts"][artifact]["sha256"] = digest(
                    self.checker.read_confined(tree, relative)
                )

        if rebind_measurement_corpus:
            # Move the measurement record's recorded corpus digest onto the
            # recomputed one. Not a reissue: no count and no date is touched,
            # and no model is consulted. It exists so the refusal waiting at
            # `$.evidence.parity_record` is reachable, the checker comparing
            # the measurement record first.
            measurement = self.checker.load_canonical_record(
                self.checker.read_confined(tree, MEASUREMENT), allow_integers=True
            )
            measurement["corpus_sha256"] = self.checker._corpus_sha256(manifest)
            written = self.checker.canonical_record_bytes(measurement, allow_integers=True)
            self._write(tree, MEASUREMENT, written)
            manifest["evidence"]["measurement_record"]["sha256"] = digest(written)

        self._write(tree, MANIFEST, self.checker.canonical_record_bytes(manifest))
        return manifest

    # --- the checker, as a subprocess ------------------------------------

    def run_checker(self, tree: Path, arguments: list[str]) -> tuple[int, list[dict[str, Any]]]:
        """The checker over the copy: argument list, no shell, fixed environment."""
        completed = subprocess.run(  # noqa: S603 - argument list, no shell, fixed env
            [sys.executable, CHECKER, *arguments],
            cwd=str(tree),
            env={
                "PATH": "/usr/bin:/bin",
                "LC_ALL": "C.UTF-8",
                "PYTHONIOENCODING": "utf-8",
                "PYTHONDONTWRITEBYTECODE": "1",
            },
            capture_output=True,
            timeout=CHECK_TIMEOUT_SECONDS,
            check=False,
        )
        if len(completed.stdout) > MAX_OUTPUT_BYTES:
            raise ProverError("the checker wrote more output than this tool will parse")
        records = []
        for line in completed.stdout.decode("utf-8", "replace").splitlines():
            line = line.strip()
            if line.startswith("{"):
                records.append(json.loads(line))
        return completed.returncode, records

    def check(self, tree: Path) -> tuple[int, list[dict[str, Any]]]:
        return self.run_checker(tree, ["check", "--root", ".", "--manifest", MANIFEST])

    @staticmethod
    def refusals(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [record for record in records if record.get("outcome") == "refused"]

    # --- the corpus digest, as the checker computes it -------------------

    def corpus_digest(self, manifest: dict[str, Any]) -> str:
        return self.checker._corpus_sha256(manifest)

    def recorded_corpus_digests(self) -> dict[str, str]:
        return {
            "measurement_record": self._live_record(MEASUREMENT, allow_integers=True)[
                "corpus_sha256"
            ],
            "parity_record": self._live_record(PARITY, allow_integers=True)["corpus_sha256"],
        }

    # --- one reconciliation, start to finish ----------------------------

    def reconcile(self, edited: bytes, **options) -> dict[str, Any]:
        """Copy, edit, apply the passes, and report what `check` said."""
        with tempfile.TemporaryDirectory(prefix="prove-agent-instruction-") as scratch:
            tree = self.copy_tree(Path(scratch))
            manifest = self.apply_passes(tree, edited, **options)
            exit_code, records = self.check(tree)
            outcome = {
                "exit": exit_code,
                "accepted": exit_code == 0,
                "corpus_sha256": self.corpus_digest(manifest),
                "refusals": [
                    {"code": record.get("code"), "node_path": record.get("node_path")}
                    for record in self.refusals(records)
                ],
            }
        return outcome


class LiveReconciliation:
    """The six mechanical passes, applied to the live tree rather than a copy.

    `Reconciliation` proves the reconciliation is possible offline and never
    writes the repository. This performs it. The two are deliberately separate
    classes: a prover that could write the tree it proves things about would be
    one flag away from proving a claim it had arranged.

    Construction expects exactly the state the demo path leaves behind: the
    subject's bound source off its recorded digest, every other bound path on
    its own. A tree off somewhere else is refused rather than reconciled around,
    because the passes below would then rebind drift nobody asked about.

    Only the after-span placement is reconcilable here. Re-deriving a recorded
    offset needs the pre-edit bytes to locate, and a tree already carrying the
    edit no longer has them. That is not a gap this tool can close by trying
    harder: the offsets are located by their own recorded bytes, and those bytes
    are what the edit displaced. A moved reviewed span refuses and says so.
    """

    def __init__(self, root: Path, checker=None) -> None:
        self.root = Path(root).resolve()
        self.checker = checker if checker is not None else load_checker(self.root)

        self.manifest = self._record(MANIFEST)
        self.fixture = self._subject_fixture()
        self.source_path = self.fixture["source"]["path"]
        self.old_digest = self.fixture["source"]["sha256"]
        self.source = self._bytes(self.source_path)
        self.new_digest = digest(self.source)

        limit = len(self.source)
        self.start = recorded_offset(
            self.fixture["source"]["start"], "the reviewed span's start", limit
        )
        self.end = recorded_offset(
            self.fixture["source"]["end"], "the reviewed span's end", limit
        )
        if self.end <= self.start:
            raise ProverError(
                f"{self.source_path} has a reviewed span that ends at or before it starts"
            )

        # Every bound path except the subject's own source, which is the one
        # the edit is expected to have moved.
        for relative, expected in bound_digests(self.manifest):
            if relative == self.source_path:
                continue
            if digest(self._bytes(relative)) != expected:
                raise ProverError(
                    f"{relative} is off its manifest digest; this tool reconciles one "
                    "edited source and refuses a tree that has drifted elsewhere"
                )

    def _bytes(self, relative: str) -> bytes:
        return self.checker.read_confined(self.root, relative)

    def _record(self, relative: str, *, allow_integers: bool = False) -> dict[str, Any]:
        return self.checker.load_canonical_record(
            self._bytes(relative), allow_integers=allow_integers
        )

    def _write(self, relative: str, data: bytes) -> None:
        self.checker.write_confined_atomic(self.root, relative, data)

    def _subject_fixture(self) -> dict[str, Any]:
        for entry in self.manifest["fixtures"]:
            if entry["id"] == SUBJECT:
                return entry
        raise ProverError(f"the manifest binds no fixture {SUBJECT}")

    def unchanged(self) -> bool:
        return self.new_digest == self.old_digest

    def check_span_held(self) -> None:
        """Refuse unless the reviewed bytes are still at their recorded offsets.

        Two faults land here and this does not try to tell them apart, because
        it cannot do so soundly. The manifest records the reviewed span's digest
        and not its bytes, so a tree already carrying the edit gives no way to
        search for where those bytes went; distinguishing "moved" from "changed"
        would be a guess presented as a diagnosis. Both causes and both remedies
        are named instead, and the reader has the edit in front of them.
        """
        span = self.source[self.start : self.end]
        if digest(span) == self.fixture["source"]["span_sha256"]:
            return
        raise ProverError(
            f"{self.source_path} is off its recorded reviewed-span digest at the recorded "
            f"offsets {self.start}-{self.end}, so this edit either changed the reviewed "
            "bytes or moved them. Neither is reconcilable here. Changed reviewed bytes are "
            "what the recorded token counts are counts of, and only agent_instruction.py "
            "measure can reissue those counts, on the machine the tokenizer profile pins. "
            "Moved reviewed bytes need their offsets re-derived from the pre-edit source, "
            "which this tree no longer holds; see wildcat-finance/skills#1192"
        )

    def apply(self) -> dict[str, Any]:
        """The six passes, in order, over the live tree."""
        self.check_span_held()

        manifest = json.loads(json.dumps(self.manifest))
        fixture = None
        for entry in manifest["fixtures"]:
            if entry["id"] == SUBJECT:
                fixture = entry
        written: list[str] = []
        applied: list[str] = []

        fixture["source"]["sha256"] = self.new_digest
        applied.append("manifest-source")

        for pass_name, artifact in (("model", "model"), ("source-spans", "source_spans")):
            relative = fixture["artifacts"][artifact]["path"]
            raw = self._bytes(relative)
            occurrences = raw.count(self.old_digest.encode("ascii"))
            if occurrences != 1:
                raise ProverError(
                    f"{relative} carries the source digest {occurrences} times, expected 1"
                )
            raw = raw.replace(self.old_digest.encode("ascii"), self.new_digest.encode("ascii"))
            self._write(relative, raw)
            written.append(relative)
            applied.append(pass_name)

        compact_relative = fixture["artifacts"]["compact"]["path"]
        self._run_checker(
            ["format", "--root", ".", "--input", fixture["artifacts"]["model"]["path"],
             "--output", compact_relative],
        )
        written.append(compact_relative)
        applied.append("compact")

        for artifact in ("model", "compact", "source_spans"):
            relative = fixture["artifacts"][artifact]["path"]
            fixture["artifacts"][artifact]["sha256"] = digest(self._bytes(relative))
        applied.append("manifest-artifacts")

        manifest_bytes = self.checker.canonical_record_bytes(manifest)
        self._write(MANIFEST, manifest_bytes)
        written.append(MANIFEST)

        rebound = self._rebind_coverage(manifest_bytes)
        written.append(COVERAGE)
        applied.append(UNOBSERVED_PASS)

        return {
            "applied": applied,
            "coverage_rebound": rebound,
            "source": self.source_path,
            "source_sha256": {"from": self.old_digest, "to": self.new_digest},
            "written": sorted(set(written)),
        }

    def _rebind_coverage(self, manifest_bytes: bytes) -> list[str]:
        """The pass a fixture copy cannot observe, because `check` never reads it.

        `agent_instruction.py check` is green without this and
        `tests/test_agent_instruction.py` is not, which is the whole reason the
        demo path ends in the test suite rather than in the checker.
        """
        raw = self._bytes(COVERAGE)
        register = json.loads(raw)
        row = register["agent_instruction"]
        rebound: list[str] = []
        replacements: list[tuple[str, str]] = []

        if row["manifest"]["path"] != MANIFEST:
            raise ProverError(f"the coverage register binds a manifest at {row['manifest']['path']}")
        if row["manifest"]["sha256"] != digest(manifest_bytes):
            replacements.append((row["manifest"]["sha256"], digest(manifest_bytes)))
            rebound.append(MANIFEST)

        for entry in row["fixtures"]:
            current = digest(self._bytes(entry["path"]))
            if entry["sha256"] != current:
                replacements.append((entry["sha256"], current))
                rebound.append(entry["path"])

        # Substituted in the register's own bytes rather than re-serialised from
        # the parsed object. Re-serialising would impose this file's key order
        # and indentation on a register that is hand-maintained in its own, and
        # a reconciliation that reformats 300 lines to change two is one nobody
        # can review.
        for old_digest, new_digest in replacements:
            occurrences = raw.count(old_digest.encode("ascii"))
            if occurrences != 1:
                raise ProverError(
                    f"{COVERAGE} carries {old_digest} {occurrences} times, expected 1"
                )
            raw = raw.replace(old_digest.encode("ascii"), new_digest.encode("ascii"))
        if replacements:
            self._write(COVERAGE, raw)
        return sorted(rebound)

    def _run_checker(self, arguments: list[str]) -> None:
        completed = subprocess.run(  # noqa: S603 - argument list, no shell, fixed env
            [sys.executable, CHECKER, *arguments],
            cwd=str(self.root),
            env={
                "PATH": "/usr/bin:/bin",
                "LC_ALL": "C.UTF-8",
                "PYTHONIOENCODING": "utf-8",
                "PYTHONDONTWRITEBYTECODE": "1",
            },
            capture_output=True,
            timeout=CHECK_TIMEOUT_SECONDS,
            check=False,
        )
        if completed.returncode != 0:
            raise ProverError(
                f"{CHECKER} {arguments[0]} exited {completed.returncode}: "
                f"{completed.stderr.decode('utf-8', 'replace')[:400]}"
            )


def run_reconcile(root: Path) -> int:
    """The demo path's second command: reconcile the live tree, say what moved."""
    try:
        live = LiveReconciliation(root)
        if live.unchanged():
            sys.stdout.write(
                json.dumps(
                    {"applied": [], "outcome": "nothing-to-reconcile", "written": []},
                    indent=2,
                    sort_keys=True,
                )
                + "\n"
            )
            return 0
        result = live.apply()
    except ProverError as error:
        print(f"prove_agent_instruction_reconciliation: {error}", file=sys.stderr)
        return 2
    result["outcome"] = "reconciled"
    sys.stdout.write(json.dumps(result, indent=2, sort_keys=True) + "\n")
    return 0


# --- the three subcommands ---------------------------------------------


def prove_offline(reconciliation: Reconciliation) -> tuple[bool, dict[str, Any], bool]:
    """An out-of-span edit, every mechanical pass applied, no model consulted.

    Met when the reconciliation leaves the tree accepted. Until the corpus
    subject moves, it does not, and this reports that rather than routing
    around it.
    """
    edited = reconciliation.edited_source(AFTER_SPAN_PLACEMENT)
    if reconciliation.span_moved(edited):
        raise ProverError("the out-of-span edit moved the reviewed span")
    outcome = reconciliation.reconcile(edited)
    return outcome["accepted"], outcome, outcome["accepted"]


def prove_span_shift(reconciliation: Reconciliation) -> tuple[int, dict[str, Any], bool]:
    """The span placements whose reconciliation outcome is proved here.

    An edit before a reviewed span start moves every recorded binding offset
    and an edit after it moves none, so the two placements are separate claims
    and the value counts placements rather than cases. Both are covered here,
    which is #1098's third acceptance check; a count that reached its threshold
    while a placement went unexercised would be the wrong kind of green, so
    `uncovered` is derived from `SPAN_PLACEMENTS` rather than assumed empty.

    The before-span placement carries its own evidence in `offsets`: what each
    recorded offset was, where the span's bytes were found in the edited source,
    and the uniform delta the anchor moved by, against which every
    independently located span was checked. `offset-pass-omitted` is the same
    edit with the re-derivation skipped, which is what makes the pass load-
    bearing rather than merely present.

    The in-span cases travel in the detail rather than the count. They are
    characterisation of the boundary the placements sit either side of, not a
    placement of their own.
    """
    before = reconciliation.edited_source(BEFORE_SPAN_PLACEMENT)
    after = reconciliation.edited_source(AFTER_SPAN_PLACEMENT)
    placements: dict[str, Any] = {
        BEFORE_SPAN_PLACEMENT: reconciliation.reconcile(before),
        AFTER_SPAN_PLACEMENT: reconciliation.reconcile(after),
    }
    uncovered = [name for name in SPAN_PLACEMENTS if name not in placements]

    in_span = reconciliation.in_span_source()
    detail = {
        "placements": placements,
        "uncovered": uncovered,
        "offsets": reconciliation.rederive_offsets(before),
        "offset-pass-omitted": reconciliation.reconcile(before, skip=(OFFSET_PASS,)),
        "in_span": {
            "every-mechanical-pass": reconciliation.reconcile(in_span),
            "span-digest-also-rebound": reconciliation.reconcile(in_span, rebind_span=True),
        },
    }
    return len(placements), detail, not uncovered


def prove_selftest(reconciliation: Reconciliation) -> tuple[int, dict[str, Any], bool]:
    """This tool's own machinery, before any claim it makes is worth reading."""
    checks: dict[str, Any] = {}

    before = reconciliation.live_digests()

    # A no-op reconciliation reproduces the committed bytes: the passes are a
    # rewrite of the digest and nothing else, so an unedited source leaves the
    # tree accepted.
    unedited = reconciliation.reconcile(reconciliation.source)
    checks["no-op-reconciliation-accepted"] = unedited["accepted"]
    if not unedited["accepted"]:
        raise ProverError(f"a no-op reconciliation did not go green: {unedited['refusals']}")

    # No mechanical pass can be dropped, and each one's refusal names it.
    edited = reconciliation.edited_source(AFTER_SPAN_PLACEMENT)
    complete = reconciliation.reconcile(edited)
    signatures: dict[str, Any] = {}
    for name in MECHANICAL_PASSES:
        omitted = reconciliation.reconcile(edited, skip=(name,))
        if omitted["accepted"]:
            raise ProverError(f"omitting the {name} pass left the tree accepted")
        signatures[name] = omitted["refusals"][0]
    distinct = {json.dumps(value, sort_keys=True) for value in signatures.values()}
    if len(distinct) != len(MECHANICAL_PASSES):
        raise ProverError("two mechanical passes share a refusal signature")
    checks["mechanical-pass-signatures"] = signatures

    # Step 1 recorded a refusal here: a complete reconciliation of an
    # out-of-span edit still refused, because the corpus subject carried the
    # bound whole-file digest and the measurement counted raw artefact bytes.
    # Step 3 removed both, so the same reconciliation now goes green and the
    # check asserts that instead. A refusal here means the projection stopped
    # reaching something it reaches today.
    checks["complete-reconciliation-accepted"] = complete["accepted"]
    if not complete["accepted"]:
        raise ProverError(
            "a complete reconciliation of an out-of-span edit refused: "
            f"{complete['refusals']}"
        )

    # The offsets pass, shown to be needed where it is needed. It is a no-op
    # after the reviewed span, so the loop above cannot reach it; a before-span
    # edit with it omitted leaves the recorded offsets pointing at bytes the
    # edit displaced, and the reviewed span digest is what catches that.
    before_span = reconciliation.edited_source(BEFORE_SPAN_PLACEMENT)
    omitted = reconciliation.reconcile(before_span, skip=(OFFSET_PASS,))
    if omitted["accepted"]:
        raise ProverError(f"omitting the {OFFSET_PASS} pass left the tree accepted")
    if omitted["refusals"][0] != {
        "code": "WAI-E-DIGEST.SOURCE_SPAN",
        "node_path": f"$.fixtures.{SUBJECT}.source.span_sha256",
    }:
        raise ProverError(
            f"omitting the {OFFSET_PASS} pass refused somewhere else: {omitted['refusals']}"
        )
    checks[OFFSET_PASS] = omitted["refusals"][0]

    # The confinement refuses what it is there to refuse, rather than being
    # trusted because it is imported.
    escapes = (
        "../escape",
        "/etc/passwd",
        "tests/../../escape",
        "tests\\escape",
        "",
    )
    refused = []
    with tempfile.TemporaryDirectory(prefix="prove-agent-instruction-confinement-") as scratch:
        tree = Path(scratch) / "tree"
        tree.mkdir()
        for candidate in escapes:
            try:
                reconciliation.checker.write_confined_atomic(tree, candidate, b"x\n")
            except reconciliation.checker.CodecError as error:
                refused.append({"path": candidate, "code": error.code})
            else:
                raise ProverError(f"the confinement accepted {candidate!r}")
        if list(tree.iterdir()):
            raise ProverError("a refused write left something behind")
    checks["confinement-refusals"] = refused

    # The live tree came through every one of those runs untouched.
    after = reconciliation.live_digests()
    if before != after:
        moved = sorted(path for path in before if before[path] != after[path])
        raise ProverError(f"the live tree changed during a proof: {moved}")
    checks["live-tree-unchanged"] = sorted(before)

    # The sixth pass a live reconciliation owes, named rather than assumed.
    checks[UNOBSERVED_PASS] = list(reconciliation.coverage_bound_artifacts())

    # Every check above raises rather than returning false, so reaching here
    # is the pass condition.
    return len(checks), checks, True


# The one subcommand that writes the repository. Named here so the parser, the
# dispatch and the tests all reach for the same string.
RECONCILE = "reconcile"

SUBCOMMANDS = {
    "offline": ("offline-reconciliation-green", "boolean", prove_offline),
    "span-shift": ("span-shift-regression", "count", prove_span_shift),
    "selftest": ("prover-selftest", "count", prove_selftest),
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prove what a bound instruction-document edit costs, with no model.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Closed at parser-build time against the design record beside this script,
    # so an unknown candidate is a usage error before any proof runs.
    choices = candidate_choices(Path(__file__).resolve().parents[1])
    subparsers = parser.add_subparsers(dest="command")
    for name in SUBCOMMANDS:
        subparser = subparsers.add_parser(name)
        subparser.add_argument("--root", default=".")
        subparser.add_argument("--candidate", default="digest-neutral-corpus", choices=choices)
        subparser.add_argument("--report")
        subparser.add_argument("--detail", action="store_true")
    # Not a proof and not design-report shaped: it writes the tree and reports
    # what it moved, so it takes neither --candidate nor --report.
    reconcile_parser = subparsers.add_parser(RECONCILE)
    reconcile_parser.add_argument("--root", default=".")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(argv)
    if arguments.command is None:
        parser.print_help()
        return 0

    root = Path(arguments.root).resolve()
    if arguments.command == RECONCILE:
        return run_reconcile(root)

    criterion, unit, prove = SUBCOMMANDS[arguments.command]
    command = " ".join(
        [
            "python3",
            "scripts/prove_agent_instruction_reconciliation.py",
            arguments.command,
            "--root",
            str(root),
            "--candidate",
            arguments.candidate,
        ]
        + (["--report", arguments.report] if arguments.report else [])
    )

    try:
        reconciliation = Reconciliation(root)
        value, detail, met = prove(reconciliation)
    except ProverError as error:
        print(f"prove_agent_instruction_reconciliation: {error}", file=sys.stderr)
        return 2

    record = {
        "candidate": arguments.candidate,
        "command": command,
        "criterion": criterion,
        "exit": 0 if met else 1,
        "schema": SCHEMA,
        "unit": unit,
        "value": value,
    }
    written = report_bytes(record)

    if arguments.report:
        try:
            write_report(
                reconciliation.checker,
                root,
                arguments.report,
                written,
                bound_targets(root, reconciliation.manifest),
            )
        except ProverError as error:
            print(
                f"prove_agent_instruction_reconciliation: refused to write "
                f"{arguments.report}: {error}",
                file=sys.stderr,
            )
            return 2
        except reconciliation.checker.CodecError as error:
            print(
                f"prove_agent_instruction_reconciliation: refused to write "
                f"{arguments.report}: {error.code}",
                file=sys.stderr,
            )
            return 2
    else:
        sys.stdout.write(written.decode("utf-8"))

    if arguments.detail:
        sys.stderr.write(json.dumps(detail, indent=2, sort_keys=True) + "\n")
    return record["exit"]


if __name__ == "__main__":
    raise SystemExit(main())
