"""Signature-only admission cases loaded by ``test_hexctl``."""


class HostIdentityRefusalCases:
    """Legacy runtime-host shapes are accepted when verification is valid."""

    def test_signature_only_accepts_every_local_attribution_shape(self):
        module = hexctl_module()
        commit = "a" * 40
        for mode in (
            "success", "no-trailers", "coauthor-only", "missing-trailer",
            "duplicate-trailer", "host-author",
            "host-committer", "host-coauthor", "host-byline",
        ):
            with self.subTest(mode=mode), mock.patch.dict(
                os.environ, {"PATH": self.env["PATH"], "FAKE_GIT_MODE": mode}
            ):
                self.assertEqual(module.verify_local_commit(self.dir, commit, "step"), commit)

    def test_signature_only_still_refuses_invalid_local_and_platform_evidence(self):
        module = hexctl_module()
        commit = "a" * 40
        with mock.patch.dict(
            os.environ, {"PATH": self.env["PATH"], "FAKE_GIT_MODE": "nonzero"}
        ):
            with self.assertRaises(SystemExit):
                module.verify_local_commit(self.dir, commit, "step")
        with mock.patch.dict(
            os.environ, {"PATH": self.env["PATH"], "FAKE_GH_MODE": "verified-false"}
        ):
            with self.assertRaises(SystemExit):
                module.verify_github_commits(self.dir, [commit])

    def test_authenticated_connector_object_enters_the_same_bounded_checker(self):
        module = hexctl_module()
        payload = {"sha": "a" * 40, "commit": {"verification": {"verified": True}}}
        self.assertIs(module.checked_github_object(payload, "/commits/a", "connector"), payload)
        with self.assertRaises(SystemExit):
            module.checked_github_object([payload], "/commits/a", "connector")

    def test_signature_only_accepts_runtime_host_pull_request_surfaces(self):
        module = hexctl_module()
        url = "https://github.com/wildcat-finance/example/pull/1"
        branch, base, head = "fiat/run-step-1", "fiat/run", "a" * 40
        payload = self.fake_pr(url, branch, base, head)
        for mode in ("host-pr-author", "host-pr-byline"):
            with self.subTest(mode=mode), mock.patch.dict(
                os.environ,
                {"PATH": self.env["PATH"], "FAKE_GH_MODE": mode,
                 "FAKE_GH_PRS": json.dumps({url: payload})},
            ):
                record = module.inspect_pull_request(
                    self.dir, url, expected_head=branch, expected_base=base,
                    expected_head_sha=head, expected_merge_sha=None,
                )
                self.assertEqual(record["head_sha"], head)

    def test_platform_verification_accepts_runtime_host_attribution(self):
        module = hexctl_module()
        commit = "a" * 40
        for mode in (
            "attribution-host-account", "attribution-host-author",
            "attribution-host-committer-account", "attribution-host-committer",
            "attribution-host-coauthor",
        ):
            with self.subTest(mode=mode), mock.patch.dict(
                os.environ, {"PATH": self.env["PATH"], "FAKE_GH_MODE": mode}
            ):
                verified, attribution = module.verified_github_attribution(self.dir, [commit])
                self.assertEqual(verified, [commit])
                self.assertEqual(attribution[0]["commit"], commit)


class FooterReappearanceCases:
    """Attribution bylines remain accepted when read back at later receipts."""

    STEP_URL = "https://github.com/wildcat-finance/example/pull/1"
    RUN_URL = "https://github.com/wildcat-finance/example/pull/2"
    WEB_FOOTER = "_Generated by [Claude Code](https://claude.ai/code/session_x)_"
    TERMINAL_FOOTER = "Generated with [Claude Code](https://claude.com/claude-code)"

    def merge_step_footer_lifecycle(self, footer):
        self.to_merge_step()
        self.prime_step_merge()
        self.fake_prs[self.STEP_URL]["body"] += "\n\n" + footer
        self.run_ctl(
            "done", "merge-step", "--step", "1", "--merge-commit", "e" * 40,
        )
        self.assertEqual(
            self.state()["integrate"]["merges"]["1"]["merge_commit"], "e" * 40
        )

    def test_merge_step_accepts_the_web_footer_that_reappeared_after_push(self):
        self.merge_step_footer_lifecycle(self.WEB_FOOTER)

    def test_merge_step_accepts_the_terminal_attribution_line_that_reappeared_after_push(self):
        self.merge_step_footer_lifecycle(self.TERMINAL_FOOTER)

    def test_integrate_accepts_the_web_footer_on_the_run_pull_request(self):
        self.to_integrate()
        state = self.state()
        run_branch = state["run_branch"]
        self.fake_refs[run_branch] = "e" * 40
        pull_request = self.fake_pr(
            self.RUN_URL, run_branch, self.integration_base(state), "e" * 40, "f" * 40
        )
        pull_request["body"] += "\n\n" + self.WEB_FOOTER
        self.fake_prs[self.RUN_URL] = pull_request
        self.run_ctl(
            "done", "integrate", "--pr-url", self.RUN_URL,
            "--merge-commit", "f" * 40,
        )
        self.assertEqual(self.state()["phase"], "done")


def build_host_identity_cases(context):
    globals().update(
        {name: value for name, value in context.items() if not name.startswith("__")}
    )
    return HostIdentityRefusalCases, FooterReappearanceCases
